"""
Product Brands source data for supercenter retail profile.

This data is 100% synthetic and safe for demo/POC purposes.
Each brand is uniquely assigned to a parent company within its category.
"""

PRODUCT_BRANDS = [
    {'Brand': 'Fresh Select', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Quality Choice', 'Company': 'Pure Taste Industries', 'Category': 'Food'},
    {'Brand': 'Natural Best', 'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Brand': 'Pure Simple', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Golden Choice', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Sunny Best', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Healthy Select', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Organic Pure', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Fresh Start', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Green Pure', 'Company': 'Pure Taste Industries', 'Category': 'Food'},
    {'Brand': 'Prime Choice', 'Company': 'PureLife', 'Category': 'Food'},
    {'Brand': 'Harvest Gold', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Farm Pure', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Nature Prime', 'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Brand': 'Pure Select', 'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Brand': 'Vital Choice', 'Company': 'Natura Best Foods', 'Category': 'Food'},
    {'Brand': 'Wholesome Best', 'Company': 'Quality Foods Ltd', 'Category': 'Food'},
    {'Brand': 'Fresh Prime', 'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Brand': 'Clean Select', 'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Brand': 'Health Prime', 'Company': 'Healthy Choice Foods', 'Category': 'Food'},
    {'Brand': 'Pure Prime', 'Company': 'Wholesome Goods Inc', 'Category': 'Food'},
    {'Brand': 'Green Best', 'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Brand': 'Healthy Best', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Mega Value', 'Company': 'BulkBuy Wholesale', 'Category': 'Retail'},
    {'Brand': 'Store Select', 'Company': 'MarketPlace Super Centers', 'Category': 'Retail'},
    {'Brand': 'Value Choice', 'Company': 'FastStop LLC', 'Category': 'Retail'},
    {'Brand': 'Bulk Best', 'Company': 'BulkBuy Wholesale', 'Category': 'Retail'},
    {'Brand': 'Quick Select', 'Company': 'GeneralStore Inc', 'Category': 'Retail'},
    {'Brand': 'Circle Choice', 'Company': 'ConvenientStop Inc', 'Category': 'Retail'},
    {'Brand': 'Fast Value', 'Company': 'MegaMart Retail Inc', 'Category': 'Retail'},
    {'Brand': 'General Best', 'Company': 'ValueMart Company', 'Category': 'Retail'},
    {'Brand': 'Market Prime', 'Company': 'FastStop LLC', 'Category': 'Retail'},
    {'Brand': 'Tech Choice', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Tech Pad', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Game Box', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Home Tech', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Soft Pro', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Computer Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Tech Pro', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Notebook Elite', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Device Pro', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Print Master', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Sport Flex', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Active Flex', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Performance Wear', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Denim Style', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Choice', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Casual Flex', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Youth Style', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Style Pro', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Fast Style', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Trendy Flex', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Care Choice', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Clean Pro', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Beauty Choice', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Oral Pro', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Cosmetic Choice', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Health Choice', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Pharma Select', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Medi Choice', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Pet Choice', 'Company': 'DogFood Co', 'Category': 'Pet'},
    {'Brand': 'Animal Care', 'Company': 'PetVitality Corp', 'Category': 'Pet'},
    {'Brand': 'Pet Health', 'Company': 'CatTreats Company', 'Category': 'Pet'},
    {'Brand': 'Blue Paws', 'Company': 'PetVitality Corp', 'Category': 'Pet'},
    {'Brand': 'Dog Choice', 'Company': 'BluePaws Co', 'Category': 'Pet'},
    {'Brand': 'Cat Treats', 'Company': 'AnimalCare Corp', 'Category': 'Pet'},
    {'Brand': 'Pro Pet', 'Company': 'PetFood Nutrition', 'Category': 'Pet'},
    {'Brand': 'Royal Paws', 'Company': 'BluePaws Co', 'Category': 'Pet'},
    {'Brand': 'Pet Wellness', 'Company': 'DogFood Co', 'Category': 'Pet'},
    {'Brand': 'Pet Vital', 'Company': 'AnimalCare Corp', 'Category': 'Pet'},
    {'Brand': 'Motor Pro', 'Company': 'PetroProducts America', 'Category': 'Automotive'},
    {'Brand': 'Engine Pro', 'Company': 'EngineLube Oil', 'Category': 'Automotive'},
    {'Brand': 'Fluid Choice', 'Company': 'PetroProducts America', 'Category': 'Automotive'},
    {'Brand': 'Fuel Pro', 'Company': 'MotorOil Inc', 'Category': 'Automotive'},
    {'Brand': 'Energy Choice', 'Company': 'FuelOil Products', 'Category': 'Automotive'},
    {'Brand': 'Fuel Choice', 'Company': 'FluidCare Limited', 'Category': 'Automotive'},
    {'Brand': 'Petro Choice', 'Company': 'FuelOil Products', 'Category': 'Automotive'},
    {'Brand': 'Office Choice', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Work Choice', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Business Choice', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Package Pro', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Adhesive Pro', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Label Choice', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Write Pro', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Pen Choice', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Write Master', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Greeting Choice', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Card Choice', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Party Choice', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Celebration Pro', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Event Choice', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Sport Choice', 'Company': 'Athletic Inc', 'Category': 'Sports'},
    {'Brand': 'Ball Pro', 'Company': 'GolfBalls Corp', 'Category': 'Sports'},
    {'Brand': 'Golf Choice', 'Company': 'GolfClub Co', 'Category': 'Sports'},
    {'Brand': 'Swing Pro', 'Company': 'GolfBalls Corp', 'Category': 'Sports'},
    {'Brand': 'Club Choice', 'Company': 'GolfBalls Corp', 'Category': 'Sports'},
    {'Brand': 'Golf Pro', 'Company': 'SwingCorp Company', 'Category': 'Sports'},
    {'Brand': 'Club Master', 'Company': 'Athletic Inc', 'Category': 'Sports'},
    {'Brand': 'Baseball Pro', 'Company': 'MaxCl Co', 'Category': 'Sports'},
    {'Brand': 'Bat Choice', 'Company': 'Athletic Inc', 'Category': 'Sports'},
    {'Brand': 'Sport Pro', 'Company': 'Athletic Inc', 'Category': 'Sports'},
    {'Brand': 'Athletic Choice', 'Company': 'BallSports Inc', 'Category': 'Sports'},
    {'Brand': 'Home Choice', 'Company': 'BuildMart Inc', 'Category': 'Home'},
    {'Brand': 'Bargain Choice', 'Company': 'BuildMart Inc', 'Category': 'Home'},
    {'Brand': 'Value Home', 'Company': 'BuildMart Inc', 'Category': 'Home'},
    {'Brand': 'Family Choice', 'Company': 'BuildMart Inc', 'Category': 'Home'},
    {'Brand': 'Economy Choice', 'Company': 'HealthPrime Foods', 'Category': 'Food'},
    {'Brand': 'Smart Select', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Budget Best', 'Company': 'Sunny Fields Corp', 'Category': 'Food'},
    {'Brand': 'Fair Trade', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Natura Best', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Farm Fresh', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Garden Pure', 'Company': 'Sunny Fields Corp', 'Category': 'Food'},
    {'Brand': 'Organic Select', 'Company': 'Pure Essence Ltd', 'Category': 'Food'},
    {'Brand': 'Fresh Choice', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Pure Valley', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Country Best', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Home Grown', 'Company': 'FreshMart Foods', 'Category': 'Food'},
    {'Brand': 'Simple Choice', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Natural Select', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Healthy Pick', 'Company': 'PureLife', 'Category': 'Food'},
    {'Brand': 'Fresh Valley', 'Company': 'Prime Produce Inc', 'Category': 'Food'},
    {'Brand': 'Pure Garden', 'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Brand': 'Golden Select', 'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Brand': 'Sunshine Pure', 'Company': 'Quality Foods Ltd', 'Category': 'Food'},
    {'Brand': 'Morning Fresh', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Daily Choice', 'Company': 'Quality Foods Ltd', 'Category': 'Food'},
    {'Brand': 'Kitchen Best', 'Company': 'Prime Produce Inc', 'Category': 'Food'},
    {'Brand': 'Home Pure', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Table Select', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Meal Choice', 'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Brand': 'Cook\'s Best', 'Company': 'Healthy Choice Foods', 'Category': 'Food'},
    {'Brand': 'Chef Select', 'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Brand': 'Recipe Pure', 'Company': 'FreshMart Foods', 'Category': 'Food'},
    {'Brand': 'Flavor Choice', 'Company': 'Prime Produce Inc', 'Category': 'Food'},
    {'Brand': 'Taste Best', 'Company': 'Healthy Choice Foods', 'Category': 'Food'},
    {'Brand': 'Gourmet Select', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Premium Pure', 'Company': 'Vital Nutrition Co', 'Category': 'Food'},
    {'Brand': 'Deluxe Choice', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Classic Best', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Traditional Pure', 'Company': 'Pure Essence Ltd', 'Category': 'Food'},
    {'Brand': 'Heritage Select', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Old Style', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Time Tested', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Proven Choice', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Reliable Best', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Trusted Pure', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Dependable Select', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Sure Choice', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Safe Best', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Clean Pure', 'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Brand': 'Clear Select', 'Company': 'Natura Best Foods', 'Category': 'Food'},
    {'Brand': 'Bright Choice', 'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Brand': 'Brilliant Best', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Perfect Pure', 'Company': 'Harvest Time Foods', 'Category': 'Food'},
    {'Brand': 'Excel Select', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Superior Choice', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Elite Best', 'Company': 'Wholesome Goods Inc', 'Category': 'Food'},
    {'Brand': 'Premier Pure', 'Company': 'Vital Nutrition Co', 'Category': 'Food'},
    {'Brand': 'Select Choice', 'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Brand': 'First Best', 'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Brand': 'Prime Select', 'Company': 'Quality Foods Ltd', 'Category': 'Food'},
    {'Brand': 'Top Choice', 'Company': 'Pure Taste Industries', 'Category': 'Food'},
    {'Brand': 'Peak Best', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Summit Pure', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Crown Select', 'Company': 'Sunny Fields Corp', 'Category': 'Food'},
    {'Brand': 'Royal Choice', 'Company': 'PureLife', 'Category': 'Food'},
    {'Brand': 'Noble Best', 'Company': 'Natura Best Foods', 'Category': 'Food'},
    {'Brand': 'Grand Pure', 'Company': 'HealthPrime Foods', 'Category': 'Food'},
    {'Brand': 'Majestic Select', 'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Brand': 'Imperial Choice', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Regal Best', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Supreme Pure', 'Company': 'HealthPrime Foods', 'Category': 'Food'},
    {'Brand': 'Ultimate Select', 'Company': 'Pure Essence Ltd', 'Category': 'Food'},
    {'Brand': 'Final Choice', 'Company': 'Wholesome Goods Inc', 'Category': 'Food'},
    {'Brand': 'Last Best', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'End Pure', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Complete Select', 'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Brand': 'Total Choice', 'Company': 'PureLife', 'Category': 'Food'},
    {'Brand': 'Full Best', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Whole Pure', 'Company': 'Pure Taste Industries', 'Category': 'Food'},
    {'Brand': 'Entire Select', 'Company': 'PureLife', 'Category': 'Food'},
    {'Brand': 'Global Choice', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'World Best', 'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Brand': 'Universal Pure', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Cosmic Select', 'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Brand': 'Space Choice', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Digital Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Smart Tech', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Modern Electronics', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Future Tech', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Advanced Choice', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'High Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Ultra Electronics', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Super Tech', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Mega Choice', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Power Electronics', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Strong Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Solid Choice', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Firm Electronics', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Stable Tech', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Steady Choice', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Reliable Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Trusty Tech', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Safe Choice', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Secure Electronics', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Protected Tech', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Guarded Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Shielded Electronics', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Armored Tech', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Fortified Choice', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Defended Electronics', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Resistant Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Tough Choice', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Hard Electronics', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Durable Tech', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Lasting Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Permanent Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Eternal Tech', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Forever Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Always Electronics', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Constant Tech', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Continuous Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Endless Electronics', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Infinite Tech', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Boundless Choice', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Limitless Electronics', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Unlimited Tech', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Unrestricted Choice', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Free Electronics', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Open Tech', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Clear Choice', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Transparent Electronics', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Visible Tech', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Obvious Choice', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Plain Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Simple Tech', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Easy Choice', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Effortless Electronics', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Smooth Tech', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Gentle Choice', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Soft Electronics', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Mild Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Light Choice', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Bright Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Shine Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Glow Choice', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Radiant Electronics', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Brilliant Tech', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Dazzling Choice', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Sparkling Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Glittering Tech', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Twinkling Choice', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Flashing Electronics', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Blinking Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Pulsing Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Beating Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Throbbing Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Vibrating Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Shaking Electronics', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Moving Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Dynamic Choice', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Active Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Energetic Tech', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Lively Choice', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Animated Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Spirited Tech', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Vigorous Choice', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Robust Electronics', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Powerful Tech', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Strong Choice', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Mighty Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Forceful Tech', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Intense Choice', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Extreme Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Radical Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Wild Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Crazy Electronics', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Mad Tech', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Insane Choice', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Wicked Electronics', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Evil Tech', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Dark Choice', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Shadow Electronics', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Black Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Night Choice', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Midnight Electronics', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Dawn Tech', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Morning Choice', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Day Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Noon Tech', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Afternoon Choice', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Evening Electronics', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Sunset Tech', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Twilight Choice', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Dusk Electronics', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Fashion Choice', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Trend Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Mode Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Look Pure', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Wear Choice', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Dress Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Outfit Select', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Attire Pure', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Garment Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Apparel Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Clothing Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Thread Pure', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Fabric Choice', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Material Best', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Textile Select', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Fiber Pure', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Yarn Choice', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'String Best', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Cord Select', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Rope Pure', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Line Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Wire Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Cable Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Chain Pure', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Link Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Bond Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Tie Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Knot Pure', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Loop Choice', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Circle Best', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Ring Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Band Pure', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Strip Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Belt Best', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Strap Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Ribbon Pure', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Bow Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Lace Best', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Trim Select', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Edge Pure', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Border Choice', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Frame Best', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Outline Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Shape Pure', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Form Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Figure Best', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Body Select', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Frame Pure', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Build Choice', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Structure Best', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Design Select', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Pattern Pure', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Plan Choice', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Scheme Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'System Select', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Method Pure', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Way Choice', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Path Best', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Road Select', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Route Pure', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Track Choice', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Trail Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Course Select', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Direction Pure', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Guide Choice', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Lead Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Follow Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Behind Pure', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Back Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Rear Best', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'End Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Final Pure', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Last Choice', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Ultimate Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Supreme Select', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Top Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Peak Choice', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'High Best', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Upper Select', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Above Pure', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Over Choice', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Beyond Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Past Select', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Future Pure', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Next Choice', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Coming Best', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Approaching Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Near Pure', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Close Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Tight Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Fit Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Ideal Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Dream Best', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Wish Select', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Hope Pure', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Faith Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Trust Best', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Believe Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Know Pure', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Think Choice', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Mind Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Brain Select', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Smart Pure', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Clever Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Wise Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Bright Select', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Brilliant Pure', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Genius Choice', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Excellent Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Outstanding Pure', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Amazing Choice', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Wonderful Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Fantastic Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Incredible Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Awesome Choice', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Great Best', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Good Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Fine Pure', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Nice Choice', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Sweet Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Kind Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Gentle Pure', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Soft Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Smooth Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Calm Select', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Peaceful Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Quiet Choice', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Silent Best', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Still Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Rest Pure', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Relax Choice', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Easy Best', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Simple Select', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Plain Pure', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Basic Choice', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Standard Best', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Normal Select', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Regular Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Common Choice', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Usual Best', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Typical Select', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Average Pure', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Medium Choice', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Middle Best', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Center Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Core Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Heart Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Soul Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Spirit Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Life Pure', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Living Choice', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Active Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Moving Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Running Pure', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Quick Choice', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Fast Best', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Speed Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Rapid Pure', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Swift Choice', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Hasty Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Rush Select', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Hurry Pure', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Urgent Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Press Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Push Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Force Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Power Choice', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Energy Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Strength Select', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Muscle Pure', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Tough Best', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Hard Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Solid Pure', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Firm Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Stable Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Steady Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Fixed Pure', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Set Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Placed Best', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Put Select', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Located Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Positioned Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Situated Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Established Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Founded Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Created Choice', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Made Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Built Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Constructed Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Assembled Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Joined Best', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Connected Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Linked Pure', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Bonded Choice', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'United Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Combined Select', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Mixed Pure', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Blended Choice', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Merged Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Fused Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Welded Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Sealed Choice', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Closed Best', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Shut Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Locked Pure', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Secured Choice', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Protected Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Guarded Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Defended Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Shielded Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Covered Select', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Hidden Pure', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Secret Choice', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Private Best', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Personal Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Individual Pure', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Single Choice', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'One Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'First Select', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Primary Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Main Choice', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Chief Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Leader Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Boss Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Master Choice', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Expert Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Pro Select', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Professional Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Skilled Choice', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Trained Best', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Educated Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Learned Pure', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Studied Choice', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Academic Best', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Scholarly Select', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Scientific Pure', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Research Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Discovery Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Finding Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Result Pure', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Outcome Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Effect Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Impact Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Influence Pure', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Control Best', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Command Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Order Pure', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Rule Choice', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Law Best', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Legal Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Official Pure', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Formal Choice', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Proper Best', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Correct Select', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Right Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'True Choice', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Best', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Genuine Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Authentic Pure', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Original Choice', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Clean Choice', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Fresh Best', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'New Select', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Modern Pure', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Current Choice', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Present Best', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Today Select', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Now Pure', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Instant Choice', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Immediate Best', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Fast Choice', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Speed Best', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Swift Select', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Sharp Pure', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Keen Choice', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Acute Best', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Intense Select', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Strong Pure', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Powerful Choice', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Mighty Best', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Great Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Magnificent Choice', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Glorious Best', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Splendid Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Radiant Choice', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Shining Best', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Light Pure', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Transparent Best', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Visible Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Obvious Pure', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Plain Choice', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Simple Best', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Basic Select', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Essential Pure', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Important Best', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Significant Select', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Major Pure', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Big Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Large Best', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Huge Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Giant Pure', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Massive Choice', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Enormous Best', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Immense Select', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Vast Pure', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Wide Choice', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Broad Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Extensive Select', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Comprehensive Pure', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Complete Choice', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Total Best', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Full Select', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
]
