"""
Product Companies source data for supercenter retail profile.

This data is 100% synthetic and safe for demo/POC purposes.
"""

PRODUCT_COMPANIES = [
    {'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Company': 'Quality Foods Ltd', 'Category': 'Food'},
    {'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Company': 'Pure Taste Industries', 'Category': 'Food'},
    {'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Company': 'Sunny Fields Corp', 'Category': 'Food'},
    {'Company': 'Healthy Choice Foods', 'Category': 'Food'},
    {'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Company': 'Green Leaf Enterprises', 'Category': 'Food'},
    {'Company': 'Prime Produce Inc', 'Category': 'Food'},
    {'Company': 'Harvest Time Foods', 'Category': 'Food'},
    {'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Company': 'Natura Best Foods', 'Category': 'Food'},
    {'Company': 'Pure Essence Ltd', 'Category': 'Food'},
    {'Company': 'Vital Nutrition Co', 'Category': 'Food'},
    {'Company': 'Wholesome Goods Inc', 'Category': 'Food'},
    {'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Company': 'HealthPrime Foods', 'Category': 'Food'},
    {'Company': 'NaturalWay', 'Category': 'Food'},
    {'Company': 'PureLife', 'Category': 'Food'},
    {'Company': 'FreshMart Foods', 'Category': 'Food'},
    {'Company': 'GreenChoice', 'Category': 'Food'},
    {'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Company': 'MegaMart Retail Inc', 'Category': 'Retail'},
    {'Company': 'SuperShop Corporation', 'Category': 'Retail'},
    {'Company': 'ValueMart Company', 'Category': 'Retail'},
    {'Company': 'BulkBuy Wholesale', 'Category': 'Retail'},
    {'Company': 'ConvenientStop Inc', 'Category': 'Retail'},
    {'Company': 'CircleShop Stores', 'Category': 'Retail'},
    {'Company': 'FastStop LLC', 'Category': 'Retail'},
    {'Company': 'GeneralStore Inc', 'Category': 'Retail'},
    {'Company': 'MarketPlace Super Centers', 'Category': 'Retail'},
    {'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Company': 'PersonalCare Corp', 'Category': 'Health'},
    {'Company': 'CleanCorp Co', 'Category': 'Health'},
    {'Company': 'BeautyGlobal NV', 'Category': 'Health'},
    {'Company': 'OralCare Co', 'Category': 'Health'},
    {'Company': 'CosmeticsCorp SA', 'Category': 'Health'},
    {'Company': 'HealthStore Alliance', 'Category': 'Health'},
    {'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Company': 'MediStore Corporation', 'Category': 'Health'},
    {'Company': 'PetFood Nutrition', 'Category': 'Pet'},
    {'Company': 'AnimalCare Corp', 'Category': 'Pet'},
    {'Company': 'PetHealth Nutrition', 'Category': 'Pet'},
    {'Company': 'BluePaws Co', 'Category': 'Pet'},
    {'Company': 'DogFood Co', 'Category': 'Pet'},
    {'Company': 'CatTreats Company', 'Category': 'Pet'},
    {'Company': 'ProPet Plan', 'Category': 'Pet'},
    {'Company': 'RoyalPaws USA', 'Category': 'Pet'},
    {'Company': 'PetWellness Company', 'Category': 'Pet'},
    {'Company': 'PetVitality Corp', 'Category': 'Pet'},
    {'Company': 'MotorOil Inc', 'Category': 'Automotive'},
    {'Company': 'EngineLube Oil', 'Category': 'Automotive'},
    {'Company': 'FluidCare Limited', 'Category': 'Automotive'},
    {'Company': 'FuelOil Products', 'Category': 'Automotive'},
    {'Company': 'PowerFluid Industries', 'Category': 'Automotive'},
    {'Company': 'FuelCorp Corporation', 'Category': 'Automotive'},
    {'Company': 'PetroProducts America', 'Category': 'Automotive'},
    {'Company': 'OfficeSupply Inc', 'Category': 'Office'},
    {'Company': 'WorkSpace Inc', 'Category': 'Office'},
    {'Company': 'OfficeSupply Inc', 'Category': 'Office'},
    {'Company': 'BusinessCenter Office', 'Category': 'Office'},
    {'Company': 'PackageShip Inc', 'Category': 'Office'},
    {'Company': 'AdhesiveTech Company', 'Category': 'Office'},
    {'Company': 'LabelCorp Corp', 'Category': 'Office'},
    {'Company': 'WritingTools Inc', 'Category': 'Office'},
    {'Company': 'PenCraft Corporation', 'Category': 'Office'},
    {'Company': 'WriteMaster Corp', 'Category': 'Office'},
    {'Company': 'GreetingCorp Inc', 'Category': 'Office'},
    {'Company': 'CardCorp Inc', 'Category': 'Office'},
    {'Company': 'PartySupply Holdings', 'Category': 'Office'},
    {'Company': 'CelebrationStore Inc', 'Category': 'Office'},
    {'Company': 'EventSupply Corp', 'Category': 'Office'},
    {'Company': 'SportEquip Worldwide', 'Category': 'Sports'},
    {'Company': 'BallSports Inc', 'Category': 'Sports'},
    {'Company': 'GolfClub Co', 'Category': 'Sports'},
    {'Company': 'SwingCorp Company', 'Category': 'Sports'},
    {'Company': 'MaxCl Co', 'Category': 'Sports'},
    {'Company': 'GolfBalls Corp', 'Category': 'Sports'},
    {'Company': 'ClubMaster Inc', 'Category': 'Sports'},
    {'Company': 'BaseballGear Inc', 'Category': 'Sports'},
    {'Company': 'BatCorp Inc', 'Category': 'Sports'},
    {'Company': 'SportGear Inc', 'Category': 'Sports'},
    {'Company': 'Athletic Inc', 'Category': 'Sports'},
    {'Company': 'HomeCenter Inc', 'Category': 'Home'},
    {'Company': 'BargainStore Corporation', 'Category': 'Home'},
    {'Company': 'ValueTree Inc', 'Category': 'Home'},
    {'Company': 'FamilyMark Stores', 'Category': 'Home'},
    {'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Company': 'BuildMart Inc', 'Category': 'Home'},
]
