"""
Tax Rates source data for supercenter retail profile.

This data is 100% synthetic and safe for demo/POC purposes.
"""

TAX_RATES = [
    {'StateCode': 'AL', 'County': 'Jefferson', 'City': 'Birmingham', 'CombinedRate': '0.0900'},
    {'StateCode': 'AL', 'County': 'Mobile', 'City': 'Mobile', 'CombinedRate': '0.1000'},
    {'StateCode': 'AL', 'County': 'Montgomery', 'City': 'Montgomery', 'CombinedRate': '0.0950'},
    {'StateCode': 'AK', 'County': 'Anchorage', 'City': 'Anchorage', 'CombinedRate': '0.0000'},
    {'StateCode': 'AK', 'County': 'Fairbanks', 'City': 'Fairbanks', 'CombinedRate': '0.0000'},
    {'StateCode': 'AK', 'County': 'Juneau', 'City': 'Juneau', 'CombinedRate': '0.0500'},
    {'StateCode': 'AZ', 'County': 'Maricopa', 'City': 'Phoenix', 'CombinedRate': '0.0830'},
    {'StateCode': 'AZ', 'County': 'Pima', 'City': 'Tucson', 'CombinedRate': '0.0870'},
    {'StateCode': 'AZ', 'County': 'Yuma', 'City': 'Yuma', 'CombinedRate': '0.0780'},
    {'StateCode': 'AR', 'County': 'Pulaski', 'City': 'Little Rock', 'CombinedRate': '0.0925'},
    {'StateCode': 'AR', 'County': 'Washington', 'City': 'Fayetteville', 'CombinedRate': '0.0900'},
    {'StateCode': 'AR', 'County': 'Benton', 'City': 'Bentonville', 'CombinedRate': '0.0900'},
    {'StateCode': 'CA', 'County': 'Los Angeles', 'City': 'Los Angeles', 'CombinedRate': '0.0950'},
    {'StateCode': 'CA', 'County': 'San Francisco', 'City': 'San Francisco', 'CombinedRate': '0.0863'},
    {'StateCode': 'CA', 'County': 'San Diego', 'City': 'San Diego', 'CombinedRate': '0.0775'},
    {'StateCode': 'CA', 'County': 'Alameda', 'City': 'Oakland', 'CombinedRate': '0.0975'},
    {'StateCode': 'CA', 'County': 'Orange', 'City': 'Anaheim', 'CombinedRate': '0.0775'},
    {'StateCode': 'CA', 'County': 'Sacramento', 'City': 'Sacramento', 'CombinedRate': '0.0825'},
    {'StateCode': 'CA', 'County': 'Santa Clara', 'City': 'San Jose', 'CombinedRate': '0.0913'},
    {'StateCode': 'CA', 'County': 'Riverside', 'City': 'Riverside', 'CombinedRate': '0.0775'},
    {'StateCode': 'CO', 'County': 'Denver', 'City': 'Denver', 'CombinedRate': '0.0810'},
    {'StateCode': 'CO', 'County': 'El Paso', 'City': 'Colorado Springs', 'CombinedRate': '0.0730'},
    {'StateCode': 'CO', 'County': 'Boulder', 'City': 'Boulder', 'CombinedRate': '0.0865'},
    {'StateCode': 'CT', 'County': 'Hartford', 'City': 'Hartford', 'CombinedRate': '0.0635'},
    {'StateCode': 'CT', 'County': 'New Haven', 'City': 'New Haven', 'CombinedRate': '0.0635'},
    {'StateCode': 'CT', 'County': 'Fairfield', 'City': 'Bridgeport', 'CombinedRate': '0.0635'},
    {'StateCode': 'DE', 'County': 'New Castle', 'City': 'Wilmington', 'CombinedRate': '0.0000'},
    {'StateCode': 'DE', 'County': 'Kent', 'City': 'Dover', 'CombinedRate': '0.0000'},
    {'StateCode': 'DE', 'County': 'Sussex', 'City': 'Georgetown', 'CombinedRate': '0.0000'},
    {'StateCode': 'FL', 'County': 'Miami-Dade', 'City': 'Miami', 'CombinedRate': '0.0700'},
    {'StateCode': 'FL', 'County': 'Orange', 'City': 'Orlando', 'CombinedRate': '0.0650'},
    {'StateCode': 'FL', 'County': 'Hillsborough', 'City': 'Tampa', 'CombinedRate': '0.0850'},
    {'StateCode': 'FL', 'County': 'Duval', 'City': 'Jacksonville', 'CombinedRate': '0.0700'},
    {'StateCode': 'FL', 'County': 'Palm Beach', 'City': 'West Palm Beach', 'CombinedRate': '0.0700'},
    {'StateCode': 'FL', 'County': 'Broward', 'City': 'Fort Lauderdale', 'CombinedRate': '0.0700'},
    {'StateCode': 'GA', 'County': 'Fulton', 'City': 'Atlanta', 'CombinedRate': '0.0890'},
    {'StateCode': 'GA', 'County': 'Gwinnett', 'City': 'Lawrenceville', 'CombinedRate': '0.0770'},
    {'StateCode': 'GA', 'County': 'Cobb', 'City': 'Marietta', 'CombinedRate': '0.0700'},
    {'StateCode': 'HI', 'County': 'Honolulu', 'City': 'Honolulu', 'CombinedRate': '0.0450'},
    {'StateCode': 'HI', 'County': 'Maui', 'City': 'Kahului', 'CombinedRate': '0.0450'},
    {'StateCode': 'HI', 'County': 'Hawaii', 'City': 'Hilo', 'CombinedRate': '0.0450'},
    {'StateCode': 'ID', 'County': 'Ada', 'City': 'Boise', 'CombinedRate': '0.0600'},
    {'StateCode': 'ID', 'County': 'Canyon', 'City': 'Nampa', 'CombinedRate': '0.0600'},
    {'StateCode': 'ID', 'County': 'Kootenai', 'City': "Coeur d'Alene", 'CombinedRate': '0.0610'},
    {'StateCode': 'IL', 'County': 'Cook', 'City': 'Chicago', 'CombinedRate': '0.1025'},
    {'StateCode': 'IL', 'County': 'DuPage', 'City': 'Naperville', 'CombinedRate': '0.0750'},
    {'StateCode': 'IL', 'County': 'Lake', 'City': 'Waukegan', 'CombinedRate': '0.0800'},
    {'StateCode': 'IN', 'County': 'Marion', 'City': 'Indianapolis', 'CombinedRate': '0.0700'},
    {'StateCode': 'IN', 'County': 'Lake', 'City': 'Hammond', 'CombinedRate': '0.0700'},
    {'StateCode': 'IN', 'County': 'Allen', 'City': 'Fort Wayne', 'CombinedRate': '0.0700'},
    {'StateCode': 'IA', 'County': 'Polk', 'City': 'Des Moines', 'CombinedRate': '0.0700'},
    {'StateCode': 'IA', 'County': 'Linn', 'City': 'Cedar Rapids', 'CombinedRate': '0.0700'},
    {'StateCode': 'IA', 'County': 'Scott', 'City': 'Davenport', 'CombinedRate': '0.0700'},
    {'StateCode': 'KS', 'County': 'Sedgwick', 'City': 'Wichita', 'CombinedRate': '0.0765'},
    {'StateCode': 'KS', 'County': 'Johnson', 'City': 'Overland Park', 'CombinedRate': '0.0863'},
    {'StateCode': 'KS', 'County': 'Wyandotte', 'City': 'Kansas City', 'CombinedRate': '0.0963'},
    {'StateCode': 'KY', 'County': 'Jefferson', 'City': 'Louisville', 'CombinedRate': '0.0600'},
    {'StateCode': 'KY', 'County': 'Fayette', 'City': 'Lexington', 'CombinedRate': '0.0600'},
    {'StateCode': 'KY', 'County': 'Kenton', 'City': 'Covington', 'CombinedRate': '0.0600'},
    {'StateCode': 'LA', 'County': 'Orleans', 'City': 'New Orleans', 'CombinedRate': '0.0945'},
    {'StateCode': 'LA', 'County': 'East Baton Rouge', 'City': 'Baton Rouge', 'CombinedRate': '0.0945'},
    {'StateCode': 'LA', 'County': 'Caddo', 'City': 'Shreveport', 'CombinedRate': '0.0945'},
    {'StateCode': 'ME', 'County': 'Cumberland', 'City': 'Portland', 'CombinedRate': '0.0550'},
    {'StateCode': 'ME', 'County': 'Penobscot', 'City': 'Bangor', 'CombinedRate': '0.0550'},
    {'StateCode': 'ME', 'County': 'York', 'City': 'Biddeford', 'CombinedRate': '0.0550'},
    {'StateCode': 'MD', 'County': 'Baltimore City', 'City': 'Baltimore', 'CombinedRate': '0.0600'},
    {'StateCode': 'MD', 'County': 'Montgomery', 'City': 'Rockville', 'CombinedRate': '0.0600'},
    {'StateCode': 'MD', 'County': "Prince George's", 'City': 'Upper Marlboro', 'CombinedRate': '0.0600'},
    {'StateCode': 'MA', 'County': 'Suffolk', 'City': 'Boston', 'CombinedRate': '0.0625'},
    {'StateCode': 'MA', 'County': 'Middlesex', 'City': 'Cambridge', 'CombinedRate': '0.0625'},
    {'StateCode': 'MA', 'County': 'Worcester', 'City': 'Worcester', 'CombinedRate': '0.0625'},
    {'StateCode': 'MI', 'County': 'Wayne', 'City': 'Detroit', 'CombinedRate': '0.0600'},
    {'StateCode': 'MI', 'County': 'Oakland', 'City': 'Pontiac', 'CombinedRate': '0.0600'},
    {'StateCode': 'MI', 'County': 'Kent', 'City': 'Grand Rapids', 'CombinedRate': '0.0600'},
    {'StateCode': 'MN', 'County': 'Hennepin', 'City': 'Minneapolis', 'CombinedRate': '0.0788'},
    {'StateCode': 'MN', 'County': 'Ramsey', 'City': 'Saint Paul', 'CombinedRate': '0.0788'},
    {'StateCode': 'MN', 'County': 'Dakota', 'City': 'Hastings', 'CombinedRate': '0.0788'},
    {'StateCode': 'MS', 'County': 'Hinds', 'City': 'Jackson', 'CombinedRate': '0.0700'},
    {'StateCode': 'MS', 'County': 'Harrison', 'City': 'Gulfport', 'CombinedRate': '0.0700'},
    {'StateCode': 'MS', 'County': 'DeSoto', 'City': 'Hernando', 'CombinedRate': '0.0700'},
    {'StateCode': 'MO', 'County': 'Jackson', 'City': 'Kansas City', 'CombinedRate': '0.0863'},
    {'StateCode': 'MO', 'County': 'St. Louis City', 'City': 'St. Louis', 'CombinedRate': '0.0863'},
    {'StateCode': 'MO', 'County': 'Greene', 'City': 'Springfield', 'CombinedRate': '0.0613'},
    {'StateCode': 'MT', 'County': 'Yellowstone', 'City': 'Billings', 'CombinedRate': '0.0000'},
    {'StateCode': 'MT', 'County': 'Missoula', 'City': 'Missoula', 'CombinedRate': '0.0000'},
    {'StateCode': 'MT', 'County': 'Cascade', 'City': 'Great Falls', 'CombinedRate': '0.0000'},
    {'StateCode': 'NE', 'County': 'Douglas', 'City': 'Omaha', 'CombinedRate': '0.0700'},
    {'StateCode': 'NE', 'County': 'Lancaster', 'City': 'Lincoln', 'CombinedRate': '0.0725'},
    {'StateCode': 'NE', 'County': 'Sarpy', 'City': 'Papillion', 'CombinedRate': '0.0700'},
    {'StateCode': 'NV', 'County': 'Clark', 'City': 'Las Vegas', 'CombinedRate': '0.0825'},
    {'StateCode': 'NV', 'County': 'Washoe', 'City': 'Reno', 'CombinedRate': '0.0825'},
    {'StateCode': 'NV', 'County': 'Carson City', 'City': 'Carson City', 'CombinedRate': '0.0765'},
    {'StateCode': 'NH', 'County': 'Hillsborough', 'City': 'Manchester', 'CombinedRate': '0.0000'},
    {'StateCode': 'NH', 'County': 'Rockingham', 'City': 'Portsmouth', 'CombinedRate': '0.0000'},
    {'StateCode': 'NH', 'County': 'Merrimack', 'City': 'Concord', 'CombinedRate': '0.0000'},
    {'StateCode': 'NJ', 'County': 'Essex', 'City': 'Newark', 'CombinedRate': '0.0663'},
    {'StateCode': 'NJ', 'County': 'Bergen', 'City': 'Hackensack', 'CombinedRate': '0.0663'},
    {'StateCode': 'NJ', 'County': 'Middlesex', 'City': 'New Brunswick', 'CombinedRate': '0.0663'},
    {'StateCode': 'NM', 'County': 'Bernalillo', 'City': 'Albuquerque', 'CombinedRate': '0.0738'},
    {'StateCode': 'NM', 'County': 'Dona Ana', 'City': 'Las Cruces', 'CombinedRate': '0.0713'},
    {'StateCode': 'NM', 'County': 'Santa Fe', 'City': 'Santa Fe', 'CombinedRate': '0.0838'},
    {'StateCode': 'NY', 'County': 'New York', 'City': 'New York City', 'CombinedRate': '0.0875'},
    {'StateCode': 'NY', 'County': 'Erie', 'City': 'Buffalo', 'CombinedRate': '0.0850'},
    {'StateCode': 'NY', 'County': 'Monroe', 'City': 'Rochester', 'CombinedRate': '0.0800'},
    {'StateCode': 'NY', 'County': 'Kings', 'City': 'Brooklyn', 'CombinedRate': '0.0875'},
    {'StateCode': 'NY', 'County': 'Queens', 'City': 'Queens', 'CombinedRate': '0.0875'},
    {'StateCode': 'NC', 'County': 'Mecklenburg', 'City': 'Charlotte', 'CombinedRate': '0.0750'},
    {'StateCode': 'NC', 'County': 'Wake', 'City': 'Raleigh', 'CombinedRate': '0.0725'},
    {'StateCode': 'NC', 'County': 'Guilford', 'City': 'Greensboro', 'CombinedRate': '0.0725'},
    {'StateCode': 'ND', 'County': 'Cass', 'City': 'Fargo', 'CombinedRate': '0.0700'},
    {'StateCode': 'ND', 'County': 'Burleigh', 'City': 'Bismarck', 'CombinedRate': '0.0700'},
    {'StateCode': 'ND', 'County': 'Grand Forks', 'City': 'Grand Forks', 'CombinedRate': '0.0700'},
    {'StateCode': 'OH', 'County': 'Cuyahoga', 'City': 'Cleveland', 'CombinedRate': '0.0800'},
    {'StateCode': 'OH', 'County': 'Franklin', 'City': 'Columbus', 'CombinedRate': '0.0775'},
    {'StateCode': 'OH', 'County': 'Hamilton', 'City': 'Cincinnati', 'CombinedRate': '0.0725'},
    {'StateCode': 'OK', 'County': 'Oklahoma', 'City': 'Oklahoma City', 'CombinedRate': '0.0890'},
    {'StateCode': 'OK', 'County': 'Tulsa', 'City': 'Tulsa', 'CombinedRate': '0.0887'},
    {'StateCode': 'OK', 'County': 'Cleveland', 'City': 'Norman', 'CombinedRate': '0.0890'},
    {'StateCode': 'OR', 'County': 'Multnomah', 'City': 'Portland', 'CombinedRate': '0.0000'},
    {'StateCode': 'OR', 'County': 'Lane', 'City': 'Eugene', 'CombinedRate': '0.0000'},
    {'StateCode': 'OR', 'County': 'Marion', 'City': 'Salem', 'CombinedRate': '0.0000'},
    {'StateCode': 'PA', 'County': 'Philadelphia', 'City': 'Philadelphia', 'CombinedRate': '0.0800'},
    {'StateCode': 'PA', 'County': 'Allegheny', 'City': 'Pittsburgh', 'CombinedRate': '0.0700'},
    {'StateCode': 'PA', 'County': 'Montgomery', 'City': 'Norristown', 'CombinedRate': '0.0600'},
    {'StateCode': 'RI', 'County': 'Providence', 'City': 'Providence', 'CombinedRate': '0.0700'},
    {'StateCode': 'RI', 'County': 'Kent', 'City': 'Warwick', 'CombinedRate': '0.0700'},
    {'StateCode': 'RI', 'County': 'Washington', 'City': 'Wakefield', 'CombinedRate': '0.0700'},
    {'StateCode': 'SC', 'County': 'Richland', 'City': 'Columbia', 'CombinedRate': '0.0800'},
    {'StateCode': 'SC', 'County': 'Charleston', 'City': 'Charleston', 'CombinedRate': '0.0800'},
    {'StateCode': 'SC', 'County': 'Greenville', 'City': 'Greenville', 'CombinedRate': '0.0700'},
    {'StateCode': 'SD', 'County': 'Minnehaha', 'City': 'Sioux Falls', 'CombinedRate': '0.0650'},
    {'StateCode': 'SD', 'County': 'Pennington', 'City': 'Rapid City', 'CombinedRate': '0.0650'},
    {'StateCode': 'SD', 'County': 'Lincoln', 'City': 'Canton', 'CombinedRate': '0.0650'},
    {'StateCode': 'TN', 'County': 'Shelby', 'City': 'Memphis', 'CombinedRate': '0.0925'},
    {'StateCode': 'TN', 'County': 'Davidson', 'City': 'Nashville', 'CombinedRate': '0.0925'},
    {'StateCode': 'TN', 'County': 'Knox', 'City': 'Knoxville', 'CombinedRate': '0.0925'},
    {'StateCode': 'TX', 'County': 'Harris', 'City': 'Houston', 'CombinedRate': '0.0825'},
    {'StateCode': 'TX', 'County': 'Dallas', 'City': 'Dallas', 'CombinedRate': '0.0825'},
    {'StateCode': 'TX', 'County': 'Bexar', 'City': 'San Antonio', 'CombinedRate': '0.0825'},
    {'StateCode': 'TX', 'County': 'Travis', 'City': 'Austin', 'CombinedRate': '0.0825'},
    {'StateCode': 'TX', 'County': 'Tarrant', 'City': 'Fort Worth', 'CombinedRate': '0.0825'},
    {'StateCode': 'TX', 'County': 'Collin', 'City': 'McKinney', 'CombinedRate': '0.0825'},
    {'StateCode': 'UT', 'County': 'Salt Lake', 'City': 'Salt Lake City', 'CombinedRate': '0.0685'},
    {'StateCode': 'UT', 'County': 'Utah', 'City': 'Provo', 'CombinedRate': '0.0625'},
    {'StateCode': 'UT', 'County': 'Davis', 'City': 'Farmington', 'CombinedRate': '0.0635'},
    {'StateCode': 'VT', 'County': 'Chittenden', 'City': 'Burlington', 'CombinedRate': '0.0600'},
    {'StateCode': 'VT', 'County': 'Rutland', 'City': 'Rutland', 'CombinedRate': '0.0600'},
    {'StateCode': 'VT', 'County': 'Washington', 'City': 'Montpelier', 'CombinedRate': '0.0600'},
    {'StateCode': 'VA', 'County': 'Fairfax', 'City': 'Fairfax', 'CombinedRate': '0.0600'},
    {'StateCode': 'VA', 'County': 'Virginia Beach City', 'City': 'Virginia Beach', 'CombinedRate': '0.0600'},
    {'StateCode': 'VA', 'County': 'Arlington', 'City': 'Arlington', 'CombinedRate': '0.0600'},
    {'StateCode': 'WA', 'County': 'King', 'City': 'Seattle', 'CombinedRate': '0.1010'},
    {'StateCode': 'WA', 'County': 'Pierce', 'City': 'Tacoma', 'CombinedRate': '0.0970'},
    {'StateCode': 'WA', 'County': 'Spokane', 'City': 'Spokane', 'CombinedRate': '0.0890'},
    {'StateCode': 'WV', 'County': 'Kanawha', 'City': 'Charleston', 'CombinedRate': '0.0600'},
    {'StateCode': 'WV', 'County': 'Berkeley', 'City': 'Martinsburg', 'CombinedRate': '0.0600'},
    {'StateCode': 'WV', 'County': 'Cabell', 'City': 'Huntington', 'CombinedRate': '0.0600'},
    {'StateCode': 'WI', 'County': 'Milwaukee', 'City': 'Milwaukee', 'CombinedRate': '0.0550'},
    {'StateCode': 'WI', 'County': 'Dane', 'City': 'Madison', 'CombinedRate': '0.0550'},
    {'StateCode': 'WI', 'County': 'Waukesha', 'City': 'Waukesha', 'CombinedRate': '0.0550'},
    {'StateCode': 'WY', 'County': 'Laramie', 'City': 'Cheyenne', 'CombinedRate': '0.0500'},
    {'StateCode': 'WY', 'County': 'Natrona', 'City': 'Casper', 'CombinedRate': '0.0500'},
    {'StateCode': 'WY', 'County': 'Campbell', 'City': 'Gillette', 'CombinedRate': '0.0500'},
]
