"""
Blocklist data for synthetic data validation.

Contains sets of real names, brands, companies, and address patterns
that should be avoided or flagged in synthetic data generation.

CONFIGURATION:
    Set environment variable RETAIL_DATAGEN_DEMO_MODE=true to disable
    name blocklist enforcement, allowing realistic names in demo data.
    This is useful for demos where realistic-looking names are preferred.

SECURITY NOTE:
    When DEMO_MODE is enabled, generated customer names may appear
    similar to real people's names. This is intentional for demo purposes
    but should be documented when demo data is shared externally.
    Brand blocklists remain active regardless of demo mode setting.
"""

import os

# Check for demo mode - when enabled, name blocklists are empty to allow realistic names
_demo_mode = os.getenv("RETAIL_DATAGEN_DEMO_MODE", "").strip().lower() in {
    "1",
    "true",
    "yes",
}

# Common real first names to avoid (disabled in demo mode)
# Note: This set is empty when DEMO_MODE is enabled to allow realistic names in demo data
REAL_FIRST_NAMES: set[str] = (
    set()
    if _demo_mode
    else {
        "john",
        "mary",
        "michael",
        "jennifer",
        "william",
        "elizabeth",
        "david",
        "patricia",
        "robert",
        "linda",
        "christopher",
        "barbara",
        "daniel",
        "sandra",
        "matthew",
        "betty",
        "anthony",
        "helen",
        "mark",
        "nancy",
        "donald",
        "karen",
        "steven",
        "lisa",
        "paul",
        "anna",
        "andrew",
        "brenda",
        "joshua",
        "emma",
        "kenneth",
        "olivia",
        "kevin",
        "sophia",
        "brian",
        "cynthia",
        "george",
        "marie",
        "edward",
        "janet",
        "ronald",
        "catherine",
        "timothy",
        "frances",
        "jason",
        "samantha",
        "jeffrey",
        "debra",
    }
)

# Common real last names to avoid (disabled in demo mode)
# Note: This set is empty when DEMO_MODE is enabled to allow realistic names in demo data
REAL_LAST_NAMES: set[str] = (
    set()
    if _demo_mode
    else {
        "smith",
        "johnson",
        "williams",
        "brown",
        "jones",
        "garcia",
        "miller",
        "davis",
        "rodriguez",
        "martinez",
        "hernandez",
        "lopez",
        "gonzales",
        "wilson",
        "anderson",
        "thomas",
        "taylor",
        "moore",
        "jackson",
        "martin",
        "lee",
        "perez",
        "thompson",
        "white",
        "harris",
        "sanchez",
        "clark",
        "ramirez",
        "lewis",
        "robinson",
        "walker",
        "young",
        "allen",
        "king",
        "wright",
        "scott",
        "torres",
        "nguyen",
        "hill",
        "flores",
        "green",
        "adams",
        "nelson",
        "baker",
        "hall",
        "rivera",
        "campbell",
        "mitchell",
        "carter",
        "roberts",
    }
)

# Real company names to avoid (now empty as all data should be synthetic)
REAL_COMPANIES: set[str] = set()

# Comprehensive real brand blocklist - major retail, technology, automotive, and consumer brands
# NOTE: Brand blocklist remains active regardless of demo mode to prevent trademark issues
REAL_BRANDS = {
    # Technology brands
    "apple",
    "microsoft",
    "google",
    "amazon",
    "meta",
    "facebook",
    "tesla",
    "nvidia",
    "amd",
    "intel",
    "samsung",
    "sony",
    "lg",
    "panasonic",
    "toshiba",
    "canon",
    "nikon",
    "hp",
    "dell",
    "lenovo",
    "asus",
    "acer",
    "cisco",
    "oracle",
    "ibm",
    "adobe",
    "salesforce",
    "vmware",
    "zoom",
    "slack",
    "twitter",
    "x",
    "linkedin",
    "tiktok",
    "snapchat",
    "spotify",
    "netflix",
    "youtube",
    "gmail",
    "outlook",
    "teams",
    "skype",
    "whatsapp",
    "instagram",
    "pinterest",
    "reddit",
    # Automotive brands
    "toyota",
    "honda",
    "ford",
    "chevrolet",
    "chevy",
    "gmc",
    "cadillac",
    "buick",
    "bmw",
    "mercedes",
    "audi",
    "volkswagen",
    "vw",
    "porsche",
    "ferrari",
    "lamborghini",
    "maserati",
    "bentley",
    "rolls-royce",
    "jaguar",
    "land rover",
    "volvo",
    "saab",
    "peugeot",
    "renault",
    "citroen",
    "fiat",
    "alfa romeo",
    "hyundai",
    "kia",
    "mazda",
    "subaru",
    "mitsubishi",
    "nissan",
    "infiniti",
    "lexus",
    "acura",
    "lincoln",
    "dodge",
    "chrysler",
    "jeep",
    "ram",
    "mini",
    "smart",
    # Retail and consumer brands
    "walmart",
    "target",
    "costco",
    "home depot",
    "lowes",
    "best buy",
    "kroger",
    "safeway",
    "publix",
    "whole foods",
    "trader joes",
    "aldi",
    "cvs",
    "walgreens",
    "rite aid",
    "macys",
    "nordstrom",
    "kohls",
    "jcpenney",
    "sears",
    "tj maxx",
    "marshalls",
    "ross",
    "burlington",
    "bed bath beyond",
    "barnes noble",
    "gamestop",
    "petco",
    "petsmart",
    "dollar general",
    "dollar tree",
    "family dollar",
    # Apparel and fashion brands
    "nike",
    "adidas",
    "puma",
    "reebok",
    "under armour",
    "lululemon",
    "gap",
    "old navy",
    "banana republic",
    "american eagle",
    "abercrombie",
    "hollister",
    "forever 21",
    "h&m",
    "zara",
    "uniqlo",
    "calvin klein",
    "tommy hilfiger",
    "polo ralph lauren",
    "levis",
    "wrangler",
    "lee",
    "carhartt",
    "patagonia",
    "north face",
    "columbia",
    "timberland",
    "ugg",
    "vans",
    "converse",
    "jordans",
    "air jordan",
    "yeezy",
    "gucci",
    "prada",
    "louis vuitton",
    "chanel",
    "hermes",
    "burberry",
    "versace",
    "armani",
    "dolce gabbana",
    "valentino",
    "givenchy",
    "balenciaga",
    "saint laurent",
    # Food and beverage brands
    "coca cola",
    "coke",
    "pepsi",
    "sprite",
    "fanta",
    "dr pepper",
    "mountain dew",
    "red bull",
    "monster",
    "rockstar",
    "gatorade",
    "powerade",
    "vitamin water",
    "dasani",
    "aquafina",
    "evian",
    "perrier",
    "la croix",
    "lacroix",
    "mcdonalds",
    "burger king",
    "wendys",
    "subway",
    "taco bell",
    "kfc",
    "pizza hut",
    "dominos",
    "papa johns",
    "starbucks",
    "dunkin",
    "tim hortons",
    "panera",
    "chipotle",
    "qdoba",
    "panda express",
    "olive garden",
    "red lobster",
    "applebees",
    "chilis",
    "tgi fridays",
    "outback",
    "texas roadhouse",
    "cracker barrel",
    "nestle",
    "kraft",
    "heinz",
    "campbells",
    "general mills",
    "kelloggs",
    "post",
    "quaker",
    "cheerios",
    "frosted flakes",
    "corn flakes",
    "rice krispies",
    "lucky charms",
    "honey nut cheerios",
    "cinnamon toast crunch",
    "fruit loops",
    "oreo",
    "chips ahoy",
    "ritz",
    "triscuit",
    "wheat thins",
    "goldfish",
    "cheez its",
    "doritos",
    "lays",
    "pringles",
    "cheetos",
    "fritos",
    "tostitos",
    "ruffles",
    # Consumer goods and household brands
    "procter gamble",
    "pg",
    "unilever",
    "johnson johnson",
    "jj",
    "colgate",
    "palmolive",
    "crest",
    "oral b",
    "listerine",
    "scope",
    "head shoulders",
    "pantene",
    "herbal essences",
    "tresemme",
    "loreal",
    "maybelline",
    "revlon",
    "covergirl",
    "max factor",
    "clinique",
    "estee lauder",
    "mac",
    "nars",
    "urban decay",
    "sephora",
    "ulta",
    "sally beauty",
    "dove",
    "axe",
    "degree",
    "secret",
    "old spice",
    "gillette",
    "venus",
    "schick",
    "bic",
    "chapstick",
    "carmex",
    "burts bees",
    "vaseline",
    "jergens",
    "aveeno",
    "neutrogena",
    "olay",
    "cetaphil",
    "eucerin",
    "lubriderm",
    "nivea",
    "lancome",
    "clarins",
    "tide",
    "gain",
    "downy",
    "bounce",
    "all",
    "arm hammer",
    "oxiclean",
    "clorox",
    "lysol",
    "febreze",
    "glade",
    "air wick",
    "pledge",
    "windex",
    "scrubbing bubbles",
    "fantastik",
    "formula 409",
    "mr clean",
    "pine sol",
    "ajax",
    "comet",
    "soft scrub",
    "kaboom",
    "clr",
    "lime away",
    # Home improvement and hardware brands
    "dewalt",
    "milwaukee",
    "makita",
    "ryobi",
    "black decker",
    "craftsman",
    "stanley",
    "husky",
    "kobalt",
    "ridgid",
    "porter cable",
    "bosch",
    "skil",
    "worx",
    "greenworks",
    "ego",
    "toro",
    "husqvarna",
    "echo",
    "stihl",
    "john deere",
    "cub cadet",
    "troy bilt",
    "snapper",
    "ariens",
    "weber",
    "char broil",
    "traeger",
    "big green egg",
    "napoleon",
    "blackstone",
    "coleman",
    "yeti",
    "igloo",
    "pelican",
    "rtic",
    "hydroflask",
    "contigo",
    "thermos",
    "nalgene",
    "camelbak",
    "osprey",
    "deuter",
    "gregory",
    # Electronics and appliance brands
    "whirlpool",
    "ge",
    "kenmore",
    "frigidaire",
    "maytag",
    "amana",
    "kitchenaid",
    "miele",
    "viking",
    "wolf",
    "sub zero",
    "thermador",
    "dacor",
    "jenn air",
    "electrolux",
    "speed queen",
    "haier",
    "sharp",
    "sanyo",
    "emerson",
    "rca",
    "westinghouse",
    "insignia",
    "dynex",
    "magnavox",
    "philips",
    "sylvania",
    "zenith",
    "durabrand",
    "tcl",
    "hisense",
    "vizio",
    "roku",
    "fire tv",
    "chromecast",
    "apple tv",
    "nvidia shield",
    # Gaming brands
    "playstation",
    "xbox",
    "nintendo",
    "steam",
    "epic games",
    "activision",
    "blizzard",
    "call of duty",
    "world of warcraft",
    "overwatch",
    "diablo",
    "starcraft",
    "hearthstone",
    "candy crush",
    "angry birds",
    "pokemon",
    "mario",
    "zelda",
    "sonic",
    "minecraft",
    "roblox",
    "fortnite",
    "apex legends",
    "valorant",
    "league of legends",
    "dota",
    "counter strike",
    "fifa",
    "madden",
    "nba 2k",
    "grand theft auto",
    "gta",
    "red dead redemption",
    "assassins creed",
    "far cry",
    "battlefield",
    "medal of honor",
    "halo",
    "gears of war",
    "destiny",
    "borderlands",
    "fallout",
    "elder scrolls",
    "skyrim",
    "doom",
    "wolfenstein",
    "dishonored",
    "prey",
    "rage",
    "quake",
    "unreal tournament",
    # Sports brands
    "espn",
    "fox sports",
    "nfl",
    "nba",
    "mlb",
    "nhl",
    "mls",
    "pga",
    "lpga",
    "nascar",
    "formula 1",
    "f1",
    "ufc",
    "wwe",
    "aew",
    "nxt",
    "raw",
    "smackdown",
    "monday night football",
    "sunday night football",
    "thursday night football",
    "march madness",
    "college football playoff",
    "world series",
    "super bowl",
    "stanley cup",
    "nba finals",
    "world cup",
    "olympics",
    "paralympics",
    # Media and entertainment brands
    "disney",
    "pixar",
    "marvel",
    "star wars",
    "lucasfilm",
    "abc",
    "cbs",
    "nbc",
    "fox",
    "cnn",
    "msnbc",
    "fox news",
    "bbc",
    "pbs",
    "hbo",
    "showtime",
    "starz",
    "epix",
    "paramount",
    "universal",
    "warner bros",
    "sony pictures",
    "paramount pictures",
    "columbia pictures",
    "twentieth century fox",
    "dreamworks",
    "illumination",
    "blue sky",
    "laika",
    "studio ghibli",
    "cartoon network",
    "nickelodeon",
    "disney channel",
    "disney junior",
    "nick jr",
    "discovery",
    "history",
    "nat geo",
    "animal planet",
    "food network",
    "hgtv",
    "tlc",
    "bravo",
    "e!",
    "mtv",
    "vh1",
    "comedy central",
    "adult swim",
    "tbs",
    "tnt",
    "usa",
    "syfy",
    "fx",
    "fxx",
    "fxm",
    "lifetime",
    "hallmark",
    "oxygen",
    "we tv",
    "own",
    "bet",
    "cmt",
    "tvland",
    "spike",
    # Financial and insurance brands
    "visa",
    "mastercard",
    "american express",
    "amex",
    "discover",
    "paypal",
    "venmo",
    "zelle",
    "cash app",
    "apple pay",
    "google pay",
    "samsung pay",
    "bank of america",
    "wells fargo",
    "chase",
    "jpmorgan",
    "citibank",
    "citi",
    "us bank",
    "pnc",
    "truist",
    "td bank",
    "fifth third",
    "regions",
    "suntrust",
    "capital one",
    "discover bank",
    "ally",
    "marcus",
    "goldman sachs",
    "morgan stanley",
    "charles schwab",
    "fidelity",
    "vanguard",
    "etrade",
    "robinhood",
    "td ameritrade",
    "interactive brokers",
    "webull",
    "stash",
    "acorns",
    "betterment",
    "wealthfront",
    "mint",
    "quicken",
    "turbotax",
    "hr block",
    "jackson hewitt",
    "liberty tax",
    "credit karma",
    "experian",
    "equifax",
    "transunion",
    "fico",
    "myfico",
    "creditwise",
    "credit sesame",
    "state farm",
    "geico",
    "progressive",
    "allstate",
    "farmers",
    "usaa",
    "liberty mutual",
    "nationwide",
    "travelers",
    "hartford",
    "aig",
    "metlife",
    "prudential",
    "new york life",
    "northwestern mutual",
    "aflac",
    # Airlines and travel brands
    "american airlines",
    "delta",
    "united",
    "southwest",
    "jetblue",
    "alaska",
    "spirit",
    "frontier",
    "allegiant",
    "hawaiian",
    "virgin america",
    "virgin atlantic",
    "british airways",
    "lufthansa",
    "air france",
    "klm",
    "emirates",
    "qatar",
    "singapore airlines",
    "cathay pacific",
    "ana",
    "jal",
    "qantas",
    "air canada",
    "expedia",
    "booking.com",
    "priceline",
    "kayak",
    "travelocity",
    "orbitz",
    "hotels.com",
    "trivago",
    "agoda",
    "airbnb",
    "vrbo",
    "homeaway",
    "marriott",
    "hilton",
    "hyatt",
    "ihg",
    "choice",
    "wyndham",
    "best western",
    "la quinta",
    "red roof",
    "motel 6",
    "super 8",
    "days inn",
    "comfort inn",
    "holiday inn",
    "hampton inn",
    "homewood suites",
    "embassy suites",
    "doubletree",
    "sheraton",
    "westin",
    "st regis",
    "luxury collection",
    "w hotels",
    "aloft",
    "element",
    "residence inn",
    "springhill suites",
    "fairfield inn",
    "courtyard",
    "ac hotels",
    "moxy",
    "edition",
    # Common shortened forms and variants
    "addy",
    "benz",
    "beemer",
    "insta",
    "fb",
    "goog",
    "msft",
    "aapl",
    "tsla",
    "amzn",
    "nflx",
    "nvda",
    "intc",
    "csco",
    "orcl",
    "crm",
    "zm",
    "nke",
    "ko",
    "pep",
    "wmt",
    "tgt",
    "hd",
    "low",
    "cost",
    "bby",
    "kr",
    "jnj",
    "pfe",
    "mrk",
    "abbv",
    "jpm",
    "bac",
    "wfc",
    "c",
    "usb",
    "gs",
    "ms",
    "schw",
    "axa",
    "met",
    "pru",
    "afl",
    "trav",
    "pgr",
    "dal",
    "ual",
    "aal",
    "luv",
    "jblu",
    "alk",
    "save",
    "ulcc",
    "ha",
    "mar",
    "hlt",
    "wynd",
    "bwxt",
}

# Real address patterns to avoid
REAL_ADDRESS_PATTERNS = [
    r".*1600 pennsylvania avenue.*",  # White House
    r".*350 fifth avenue.*",  # Empire State Building
    r".*221b baker street.*",  # Sherlock Holmes
    r".*1 infinite loop.*",  # Apple
    r".*1 microsoft way.*",  # Microsoft
    r".*1600 amphitheatre.*",  # Google
]


def is_demo_mode() -> bool:
    """Check if demo mode is enabled.

    Returns:
        True if RETAIL_DATAGEN_DEMO_MODE environment variable is set to
        a truthy value (1, true, yes), False otherwise.

    Note:
        This function dynamically checks the environment variable each time
        it's called, allowing tests to modify the behavior at runtime.
    """
    return os.getenv("RETAIL_DATAGEN_DEMO_MODE", "").strip().lower() in {
        "1",
        "true",
        "yes",
    }
