table stockout_risk
	lineageTag: c5e6e000-0000-0000-0003-000000000000
	sourceLineageTag: [au].[stockout_risk]

	/// Distinct store/product/horizon positions scored by the stockout model.
	measure 'Stockout Risk SKU Count' = COUNTROWS(SUMMARIZE('stockout_risk', 'stockout_risk'[Store ID], 'stockout_risk'[Product ID], 'stockout_risk'[Forecast Horizon Days]))
		formatString: #,0
		displayFolder: ML\Stockout Risk
		lineageTag: c5e6e000-0000-0000-0003-000000000101

	/// Mean predicted stockout probability across the in-context positions.
	measure 'Avg Stockout Probability' = AVERAGE('stockout_risk'[Stockout Probability])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: ML\Stockout Risk
		lineageTag: c5e6e000-0000-0000-0003-000000000102

	/// Positions classified as high stockout risk by the model.
	measure 'High Risk SKUs' = CALCULATE(COUNTROWS(SUMMARIZE('stockout_risk', 'stockout_risk'[Store ID], 'stockout_risk'[Product ID], 'stockout_risk'[Forecast Horizon Days])), 'stockout_risk'[Risk Level] = "HIGH")
		formatString: #,0
		displayFolder: ML\Stockout Risk
		lineageTag: c5e6e000-0000-0000-0003-000000000103

	/// Average remaining days of inventory across in-context positions.
	measure 'Avg Days of Inventory' = AVERAGE('stockout_risk'[Days of Inventory])
		formatString: #,0.0
		displayFolder: ML\Stockout Risk
		lineageTag: c5e6e000-0000-0000-0003-000000000104

	/// Average daily demand velocity across in-context positions.
	measure 'Avg Daily Demand Velocity' = AVERAGE('stockout_risk'[Demand Velocity Daily])
		formatString: #,0.00
		displayFolder: ML\Stockout Risk
		lineageTag: c5e6e000-0000-0000-0003-000000000105

	/// Inventory snapshot timestamp used to build each current risk score.
	measure 'Stockout Inventory As Of' = MAX('stockout_risk'[Inventory As Of])
		formatString: General Date
		displayFolder: ML\Stockout Risk\Metadata
		lineageTag: c5e6e000-0000-0000-0003-000000000106

	/// Age in hours of the latest inventory snapshot in the current filter context.
	measure 'Stockout Freshness (Hours)' = DATEDIFF(MAX('stockout_risk'[Inventory As Of]), UTCNOW(), HOUR)
		formatString: #,0
		displayFolder: ML\Stockout Risk\Metadata
		lineageTag: c5e6e000-0000-0000-0003-000000000108

	/// Important interpretation boundary for current stockout classifications.
	measure 'Stockout Limitation' = "Scores describe the current store/product/horizon snapshot and depend on observed inventory and demand history; they do not guarantee a future stockout."
		displayFolder: ML\Stockout Risk\Metadata
		lineageTag: c5e6e000-0000-0000-0003-000000000107

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: c5e6e000-0000-0000-0003-000000000001
		sourceLineageTag: store_id
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: c5e6e000-0000-0000-0003-000000000002
		sourceLineageTag: product_id
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column 'Inventory As Of'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: c5e6e000-0000-0000-0003-00000000000e
		sourceLineageTag: inventory_as_of
		summarizeBy: none
		sourceColumn: inventory_as_of

		annotation SummarizationSetBy = Automatic

	column 'Current Inventory'
		dataType: int64
		formatString: 0
		lineageTag: c5e6e000-0000-0000-0003-000000000003
		sourceLineageTag: current_inventory
		summarizeBy: sum
		sourceColumn: current_inventory

		annotation SummarizationSetBy = Automatic

	column 'Demand Velocity Daily'
		dataType: double
		formatString: #,0.00
		lineageTag: c5e6e000-0000-0000-0003-000000000004
		sourceLineageTag: demand_velocity_daily
		summarizeBy: none
		sourceColumn: demand_velocity_daily

		annotation SummarizationSetBy = Automatic

	column 'Days of Inventory'
		dataType: double
		formatString: #,0.0
		lineageTag: c5e6e000-0000-0000-0003-000000000005
		sourceLineageTag: days_of_inventory
		summarizeBy: none
		sourceColumn: days_of_inventory

		annotation SummarizationSetBy = Automatic

	column 'Demand Trend'
		dataType: double
		lineageTag: c5e6e000-0000-0000-0003-000000000006
		sourceLineageTag: demand_trend
		summarizeBy: sum
		sourceColumn: demand_trend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Stockout Probability'
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c5e6e000-0000-0000-0003-000000000007
		sourceLineageTag: stockout_probability
		summarizeBy: none
		sourceColumn: stockout_probability

		annotation SummarizationSetBy = Automatic

	column 'Stockout Predicted'
		dataType: int64
		formatString: 0
		lineageTag: c5e6e000-0000-0000-0003-000000000008
		sourceLineageTag: stockout_predicted
		summarizeBy: none
		sourceColumn: stockout_predicted

		annotation SummarizationSetBy = Automatic

	column 'Risk Score'
		dataType: string
		lineageTag: c5e6e000-0000-0000-0003-000000000009
		sourceLineageTag: risk
		summarizeBy: none
		sourceColumn: risk

		annotation SummarizationSetBy = Automatic

	column 'Risk Ranking'
		dataType: int64
		formatString: 0
		lineageTag: c5e6e000-0000-0000-0003-00000000000a
		sourceLineageTag: ranking
		summarizeBy: none
		sourceColumn: ranking

		annotation SummarizationSetBy = Automatic

	column 'Risk Level'
		dataType: string
		lineageTag: c5e6e000-0000-0000-0003-00000000000b
		sourceLineageTag: risk_level
		summarizeBy: none
		sourceColumn: risk_level

		annotation SummarizationSetBy = Automatic

	column 'Predicted At'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: c5e6e000-0000-0000-0003-00000000000c
		sourceLineageTag: predicted_at
		summarizeBy: none
		sourceColumn: predicted_at

		annotation SummarizationSetBy = Automatic

	column 'Generated At'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: c5e6e000-0000-0000-0003-000000000011
		sourceLineageTag: generated_at
		summarizeBy: none
		sourceColumn: generated_at

		annotation SummarizationSetBy = Automatic

	column 'Forecast Horizon Days'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c5e6e000-0000-0000-0003-00000000000d
		sourceLineageTag: forecast_horizon_days
		summarizeBy: none
		sourceColumn: forecast_horizon_days

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 78bec704-4105-4109-8e1f-ab3d72f62f5d
		sourceLineageTag: Department
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 2bcf67df-5347-44fe-b258-575e1b30a299
		sourceLineageTag: Category
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 344c1d2f-86d0-4e34-a261-e752e039ed85
		sourceLineageTag: Subcategory
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column 'Model Run ID'
		dataType: string
		isHidden
		lineageTag: c5e6e000-0000-0000-0003-00000000000f
		sourceLineageTag: model_run_id
		summarizeBy: none
		sourceColumn: model_run_id

		annotation SummarizationSetBy = Automatic

	column 'Schema Version'
		dataType: string
		isHidden
		lineageTag: c5e6e000-0000-0000-0003-000000000010
		sourceLineageTag: schema_version
		summarizeBy: none
		sourceColumn: schema_version

		annotation SummarizationSetBy = Automatic

	partition stockout_risk = entity
		mode: directLake
		source
			entityName: stockout_risk
			schemaName: au
			expressionSource: 'DirectLake - retail_lakehouse'
