table 'Demand Forecast'
	lineageTag: a1000001-0000-0000-0000-000000000000
	sourceLineageTag: [au].[demand_forecast]

	measure 'Avg Forecast Units' = AVERAGE('Demand Forecast'[Predicted Units])
		formatString: #,0.0
		lineageTag: a1000001-0001-0001-0001-000000000001

	measure 'Total Forecast Units' = SUM('Demand Forecast'[Predicted Units])
		formatString: #,0.0
		lineageTag: a1000001-0001-0001-0001-000000000004

	measure 'Forecast MAPE' = AVERAGE('Demand Forecast'[MAPE])
		formatString: 0.0%
		lineageTag: a1000001-0001-0001-0001-000000000002

	measure 'Forecast Range Width' = AVERAGE('Demand Forecast'[Upper Bound] - 'Demand Forecast'[Lower Bound])
		formatString: #,0.0
		lineageTag: a1000001-0001-0001-0001-000000000003

	measure 'Total Forecast Lower Bound' = SUM('Demand Forecast'[Lower Bound])
		formatString: #,0.0
		lineageTag: a1000001-0001-0001-0001-000000000005

	measure 'Total Forecast Upper Bound' = SUM('Demand Forecast'[Upper Bound])
		formatString: #,0.0
		lineageTag: a1000001-0001-0001-0001-000000000006

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: a1000001-0002-0002-0002-000000000001
		sourceLineageTag: store_id
		summarizeBy: none
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: a1000001-0002-0002-0002-000000000002
		sourceLineageTag: product_id
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Forecast Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: a1000001-0002-0002-0002-000000000003
		sourceLineageTag: forecast_date
		summarizeBy: none
		sourceColumn: forecast_date

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Predicted Units'
		dataType: double
		lineageTag: a1000001-0002-0002-0002-000000000004
		sourceLineageTag: predicted_units
		summarizeBy: sum
		sourceColumn: predicted_units

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lower Bound'
		dataType: double
		lineageTag: a1000001-0002-0002-0002-000000000005
		sourceLineageTag: lower_bound
		summarizeBy: none
		sourceColumn: lower_bound

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Upper Bound'
		dataType: double
		lineageTag: a1000001-0002-0002-0002-000000000006
		sourceLineageTag: upper_bound
		summarizeBy: none
		sourceColumn: upper_bound

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MAPE
		dataType: double
		lineageTag: a1000001-0002-0002-0002-000000000007
		sourceLineageTag: mape
		summarizeBy: none
		sourceColumn: mape

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Generated At'
		dataType: dateTime
		formatString: General Date
		lineageTag: a1000001-0002-0002-0002-000000000008
		sourceLineageTag: generated_at
		summarizeBy: none
		sourceColumn: generated_at

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition 'Demand Forecast' = entity
		mode: directLake
		source
			entityName: demand_forecast
			schemaName: au
			expressionSource: 'DirectLake - retail_lakehouse'
