table Geographies
	lineageTag: 0182aad6-4ad2-40ca-ad96-bccd64f82380
	sourceLineageTag: [ag].[dim_geographies]

	measure '# of Locations' = COUNTROWS(Geographies)
		formatString: #,0
		lineageTag: 01a1a1b6-0001-0001-0001-000000000001

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 86b814c1-1e15-456d-ad2b-cc3b0f83d7e8
		sourceLineageTag: ID
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 57de3111-834e-4204-9f1c-4bfee7fe30ae
		sourceLineageTag: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: c0f70822-4f36-49e2-9587-7f62e0176583
		sourceLineageTag: State
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Zip Code'
		dataType: string
		lineageTag: 00fa76f8-35be-45d4-85ab-485a221637c1
		sourceLineageTag: ZipCode
		summarizeBy: none
		sourceColumn: ZipCode
		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: f70e4d1d-a9eb-4cad-a978-852cdebf824a
		sourceLineageTag: District
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: db8bcaef-9a73-41c4-9a9a-c979c125b87f
		sourceLineageTag: Region
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Geographies = entity
		mode: directLake
		source
			entityName: dim_geographies
			schemaName: ag
			expressionSource: 'DirectLake - retail_lakehouse'

