table 'Dwell Predictions'
	lineageTag: a6000006-0000-0000-0000-000000000000
	sourceLineageTag: [au].[dwell_predictions]

	measure 'Avg Predicted Dwell' = AVERAGE('Dwell Predictions'[Predicted Dwell Minutes])
		formatString: #,0.0
		lineageTag: a6000006-0001-0001-0001-000000000001

	measure 'Avg Prediction Error' = AVERAGE(ABS('Dwell Predictions'[Prediction Error]))
		formatString: #,0.0
		lineageTag: a6000006-0001-0001-0001-000000000002

	measure 'Shipments Outside Band' = CALCULATE(COUNTROWS('Dwell Predictions'), OR('Dwell Predictions'[Dwell Minutes] > 'Dwell Predictions'[Upper Bound Minutes], 'Dwell Predictions'[Dwell Minutes] < 'Dwell Predictions'[Lower Bound Minutes]))
		formatString: #,0
		lineageTag: a6000006-0001-0001-0001-000000000003

	column 'Shipment ID'
		dataType: string
		lineageTag: a6000006-0002-0002-0002-000000000001
		sourceLineageTag: shipment_id
		summarizeBy: none
		sourceColumn: shipment_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Arrived TS'
		dataType: dateTime
		formatString: General Date
		lineageTag: a6000006-0002-0002-0002-000000000002
		sourceLineageTag: arrived_ts
		summarizeBy: none
		sourceColumn: arrived_ts

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Departed TS'
		dataType: dateTime
		formatString: General Date
		lineageTag: a6000006-0002-0002-0002-000000000003
		sourceLineageTag: departed_ts
		summarizeBy: none
		sourceColumn: departed_ts

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Location Type'
		dataType: string
		lineageTag: a6000006-0002-0002-0002-000000000004
		sourceLineageTag: location_type
		summarizeBy: none
		sourceColumn: location_type

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Arrival Hour'
		dataType: int64
		formatString: 0
		lineageTag: a6000006-0002-0002-0002-000000000005
		sourceLineageTag: arrival_hour
		summarizeBy: none
		sourceColumn: arrival_hour

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Arrival Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: a6000006-0002-0002-0002-000000000006
		sourceLineageTag: arrival_day_of_week
		summarizeBy: none
		sourceColumn: arrival_day_of_week

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Dwell Minutes'
		dataType: double
		lineageTag: a6000006-0002-0002-0002-000000000007
		sourceLineageTag: dwell_minutes
		summarizeBy: none
		sourceColumn: dwell_minutes

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Predicted Dwell Minutes'
		dataType: double
		lineageTag: a6000006-0002-0002-0002-000000000008
		sourceLineageTag: predicted_dwell_minutes
		summarizeBy: none
		sourceColumn: predicted_dwell_minutes

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lower Bound Minutes'
		dataType: double
		lineageTag: a6000006-0002-0002-0002-000000000009
		sourceLineageTag: lower_bound_minutes
		summarizeBy: none
		sourceColumn: lower_bound_minutes

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Upper Bound Minutes'
		dataType: double
		lineageTag: a6000006-0002-0002-0002-00000000000a
		sourceLineageTag: upper_bound_minutes
		summarizeBy: none
		sourceColumn: upper_bound_minutes

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Prediction Error'
		dataType: double
		lineageTag: a6000006-0002-0002-0002-00000000000b
		sourceLineageTag: prediction_error
		summarizeBy: none
		sourceColumn: prediction_error

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Prediction Timestamp'
		dataType: dateTime
		formatString: General Date
		lineageTag: a6000006-0002-0002-0002-00000000000c
		sourceLineageTag: prediction_timestamp
		summarizeBy: none
		sourceColumn: prediction_timestamp

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition 'Dwell Predictions' = entity
		mode: directLake
		source
			entityName: dwell_predictions
			schemaName: au
			expressionSource: 'DirectLake - retail_lakehouse'
