table fact_receipt_lines
	lineageTag: aab05dc7-35b4-4318-affd-bc107c21f8f7
	sourceLineageTag: [ag].[fact_receipt_lines]

	measure 'Total Units Sold' = SUM(fact_receipt_lines[quantity])
		formatString: #,0
		lineageTag: 01a1a1a2-0001-0001-0001-000000000001

	measure 'Line Revenue' = SUM(fact_receipt_lines[ext_cents]) / 100
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1a2-0001-0001-0001-000000000002

	measure 'Average Unit Price' = DIVIDE([Line Revenue], [Total Units Sold], 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1a2-0001-0001-0001-000000000003

	measure 'Total Lines' = COUNTROWS(fact_receipt_lines)
		formatString: #,0
		lineageTag: 01a1a1a2-0001-0001-0001-000000000004

	column receipt_id_ext
		dataType: string
		lineageTag: 9a782ca7-2110-4e68-994a-5c56e36c0200
		sourceLineageTag: receipt_id_ext
		summarizeBy: none
		sourceColumn: receipt_id_ext

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 160f5195-0ef4-431a-9e58-e0dda60336f2
		sourceLineageTag: product_id
		summarizeBy: sum
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column line_num
		dataType: int64
		formatString: 0
		lineageTag: bd65b0d0-4508-4f61-8a08-7bc9e337892e
		sourceLineageTag: line_num
		summarizeBy: sum
		sourceColumn: line_num

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: de505fd4-366c-410b-9a65-544528a62890
		sourceLineageTag: quantity
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: string
		lineageTag: 9de741c8-fe8c-43bb-b1d1-3547e0e467e4
		sourceLineageTag: unit_price
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column ext_price
		dataType: string
		lineageTag: a743303d-5bbe-46f7-844b-72b2a53cbd8f
		sourceLineageTag: ext_price
		summarizeBy: none
		sourceColumn: ext_price

		annotation SummarizationSetBy = Automatic

	column unit_cents
		dataType: int64
		formatString: 0
		lineageTag: 5af8a932-d0bb-4d47-9699-705ddf5bbde0
		sourceLineageTag: unit_cents
		summarizeBy: sum
		sourceColumn: unit_cents

		annotation SummarizationSetBy = Automatic

	column ext_cents
		dataType: int64
		formatString: 0
		lineageTag: 669ff8f4-2ed2-4299-9cf5-9730c3bb22e1
		sourceLineageTag: ext_cents
		summarizeBy: sum
		sourceColumn: ext_cents

		annotation SummarizationSetBy = Automatic

	column promo_code
		dataType: string
		lineageTag: 5848e85f-4f07-40c5-9166-5364b4b7c822
		sourceLineageTag: promo_code
		summarizeBy: none
		sourceColumn: promo_code

		annotation SummarizationSetBy = Automatic

	partition fact_receipt_lines = entity
		mode: directLake
		source
			entityName: fact_receipt_lines
			schemaName: ag
			expressionSource: 'DirectLake - retail_lakehouse'

