table 'Store Inventory Position'
	lineageTag: 80253872-c9ec-4d0d-b638-c3c5163306c3
	sourceLineageTag: [au].[inventory_position_current]

	measure 'Total Units on Hand' = SUM('Store Inventory Position'[On Hand])
		formatString: #,0
		lineageTag: 01a1a1a5-0001-0001-0001-000000000001

	measure 'Total Inventory Value' = SUMX('Store Inventory Position', 'Store Inventory Position'[On Hand] * RELATED(Products[Cost]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1a5-0001-0001-0001-000000000002

	measure 'Total Inventory Retail Value' = SUMX('Store Inventory Position', 'Store Inventory Position'[On Hand] * RELATED(Products[Sale Price]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1a5-0001-0001-0001-000000000003

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: 657f2501-30bd-49f7-b3b0-979a5491791c
		sourceLineageTag: store_id
		summarizeBy: sum
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: cbc2790a-4977-4e9b-af30-d485dcdee191
		sourceLineageTag: product_id
		summarizeBy: sum
		sourceColumn: product_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'On Hand'
		dataType: int64
		formatString: 0
		lineageTag: 4ac72f8c-f640-45cd-9cac-8d4f713b4b58
		sourceLineageTag: on_hand
		summarizeBy: sum
		sourceColumn: on_hand

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition 'Store Inventory Position' = entity
		mode: directLake
		source
			entityName: inventory_position_current
			schemaName: au
			expressionSource: 'DirectLake - retail_lakehouse'

