table 'Marketing Cost Daily'
	lineageTag: 4bb353d5-fa0d-4c32-911a-584a960f5482
	sourceLineageTag: [au].[marketing_cost_daily]

	measure 'Marketing Spend (Channel)' = CALCULATE(SUM('Marketing Cost Daily'[Cost]), TREATAS(VALUES(Marketing[Campaign ID]), 'Marketing Cost Daily'[Campaign ID]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 45de4a5d-09b4-4c1c-a32c-862c2cd20aa9

	column 'Campaign ID'
		dataType: string
		lineageTag: b157fd89-f13a-41ea-91db-9be92915c7db
		sourceLineageTag: campaign_id
		summarizeBy: none
		sourceColumn: campaign_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: dateTime
		formatString: General Date
		lineageTag: 601e19ab-304b-46d4-a357-76f8461372b8
		sourceLineageTag: day
		summarizeBy: none
		sourceColumn: day

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Impressions
		dataType: int64
		formatString: 0
		lineageTag: f567b3cc-29dc-4181-a70e-8d1bd45e464a
		sourceLineageTag: impressions
		summarizeBy: sum
		sourceColumn: impressions

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 69e20067-0b0a-4503-b10c-80e75ca38f85
		sourceLineageTag: cost
		summarizeBy: sum
		sourceColumn: cost

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Marketing Cost Daily' = entity
		mode: directLake
		source
			entityName: marketing_cost_daily
			schemaName: au
			expressionSource: 'DirectLake - retail_lakehouse'
