table 'Online Orders'
	lineageTag: 930ea7c8-e0a4-4f4a-a7df-1cf98fbeeefd
	sourceLineageTag: [ag].[fact_online_order_headers]

	measure 'Total Online Sales' = SUM('Online Orders'[Total Cents]) / 100
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1a3-0001-0001-0001-000000000001

	measure 'Total Online Tax' = SUM('Online Orders'[Tax Cents]) / 100
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1a3-0001-0001-0001-000000000002

	measure 'Total Online Subtotal' = SUM('Online Orders'[Subtotal Cents]) / 100
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1a3-0001-0001-0001-000000000003

	measure 'Online Order Count' = COUNTROWS('Online Orders')
		formatString: #,0
		lineageTag: 01a1a1a3-0001-0001-0001-000000000004

	measure 'Average Online Order Value' = DIVIDE([Total Online Sales], [Online Order Count], 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1a3-0001-0001-0001-000000000005

	column 'Event TS'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2cf73f4d-98a3-431e-af08-d2dbdef55a63
		sourceLineageTag: event_ts
		summarizeBy: none
		sourceColumn: event_ts

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Day = DATEVALUE('Online Orders'[Event TS])
		dataType: dateTime
		formatString: Short Date
		lineageTag: 868c5a62-4853-44be-b323-191328ce2f3b
		summarizeBy: none

		changedProperty = Name

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: c6cd591e-21eb-4a48-82fe-be8ca75c1e34
		sourceLineageTag: customer_id
		summarizeBy: sum
		sourceColumn: customer_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Subtotal Cents'
		dataType: int64
		formatString: 0
		lineageTag: 7c45861b-0559-41b0-8f45-d366dc2fc071
		sourceLineageTag: subtotal_cents
		summarizeBy: sum
		sourceColumn: subtotal_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 549cb01f-8401-439b-94a1-03ce546d388c
		sourceLineageTag: order_id_ext
		summarizeBy: none
		sourceColumn: order_id_ext

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		lineageTag: 2c6791b3-9bd0-4cb7-8e8d-172fdbb2bde6
		sourceLineageTag: payment_method
		summarizeBy: none
		sourceColumn: payment_method

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Total Amount'
		dataType: string
		lineageTag: 41239a23-abc8-447a-ace2-d14d407e989c
		sourceLineageTag: total_amount
		summarizeBy: none
		sourceColumn: total_amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Total Cents'
		dataType: int64
		formatString: 0
		lineageTag: 2123d982-0ece-4589-a4cb-d2154af602cd
		sourceLineageTag: total_cents
		summarizeBy: sum
		sourceColumn: total_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Tax Amount'
		dataType: string
		lineageTag: 3d73f23c-7703-4673-a845-52220518b0e5
		sourceLineageTag: tax_amount
		summarizeBy: none
		sourceColumn: tax_amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Subtotal Amount'
		dataType: string
		lineageTag: 18653173-4d8b-4cf3-b061-7399ace2daa0
		sourceLineageTag: subtotal_amount
		summarizeBy: none
		sourceColumn: subtotal_amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Tax Cents'
		dataType: int64
		formatString: 0
		lineageTag: d5a18cad-980f-4839-8303-5bfde6a48bc8
		sourceLineageTag: tax_cents
		summarizeBy: sum
		sourceColumn: tax_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition 'Online Orders' = entity
		mode: directLake
		source
			entityName: fact_online_order_headers
			schemaName: ag
			expressionSource: 'DirectLake - retail_lakehouse'
