table 'Promotion Lift'
	lineageTag: b2000000-0000-0000-0000-000000000000
	sourceLineageTag: [au].[promotion_lift]

	measure 'Avg Incremental Lift %' = AVERAGE('Promotion Lift'[Incremental Lift Pct])
		formatString: 0.0%
		lineageTag: b2000000-0000-0000-0001-000000000001

	measure 'Avg Net Lift %' = AVERAGE('Promotion Lift'[Net Lift Pct])
		formatString: 0.0%
		lineageTag: b2000000-0000-0000-0001-000000000002

	measure 'High ROI Promo Count' = CALCULATE(COUNTROWS('Promotion Lift'), 'Promotion Lift'[ROI Category] = "High")
		formatString: #,0
		lineageTag: b2000000-0000-0000-0001-000000000003

	column 'Promo Code'
		dataType: string
		lineageTag: b2000000-0000-0000-0002-000000000001
		sourceLineageTag: promo_code
		summarizeBy: none
		sourceColumn: promo_code

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: b2000000-0000-0000-0002-000000000002
		sourceLineageTag: product_id
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: b2000000-0000-0000-0002-000000000003
		sourceLineageTag: product_name
		summarizeBy: none
		sourceColumn: product_name

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: b2000000-0000-0000-0002-000000000004
		sourceLineageTag: product_category
		summarizeBy: none
		sourceColumn: product_category

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Discount Type'
		dataType: string
		lineageTag: b2000000-0000-0000-0002-000000000005
		sourceLineageTag: discount_type
		summarizeBy: none
		sourceColumn: discount_type

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Avg Discount'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b2000000-0000-0000-0002-000000000006
		sourceLineageTag: avg_discount
		summarizeBy: none
		sourceColumn: avg_discount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Avg Discount Pct'
		dataType: double
		lineageTag: b2000000-0000-0000-0002-000000000007
		sourceLineageTag: avg_discount_pct
		summarizeBy: none
		sourceColumn: avg_discount_pct

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Promo Start Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b2000000-0000-0000-0002-000000000008
		sourceLineageTag: promo_start_date
		summarizeBy: none
		sourceColumn: promo_start_date

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Promo End Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b2000000-0000-0000-0002-000000000009
		sourceLineageTag: promo_end_date
		summarizeBy: none
		sourceColumn: promo_end_date

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Baseline Daily Quantity'
		dataType: double
		lineageTag: b2000000-0000-0000-0002-00000000000a
		sourceLineageTag: baseline_daily_quantity
		summarizeBy: none
		sourceColumn: baseline_daily_quantity

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Promo Daily Quantity'
		dataType: double
		lineageTag: b2000000-0000-0000-0002-00000000000b
		sourceLineageTag: promo_daily_quantity
		summarizeBy: none
		sourceColumn: promo_daily_quantity

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Post Daily Quantity'
		dataType: double
		lineageTag: b2000000-0000-0000-0002-00000000000c
		sourceLineageTag: post_daily_quantity
		summarizeBy: none
		sourceColumn: post_daily_quantity

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Promoted Quantity'
		dataType: double
		lineageTag: b2000000-0000-0000-0002-00000000000d
		sourceLineageTag: total_promoted_quantity
		summarizeBy: sum
		sourceColumn: total_promoted_quantity

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Promoted Revenue'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b2000000-0000-0000-0002-00000000000e
		sourceLineageTag: total_promoted_revenue
		summarizeBy: sum
		sourceColumn: total_promoted_revenue

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Incremental Lift Pct'
		dataType: double
		lineageTag: b2000000-0000-0000-0002-00000000000f
		sourceLineageTag: incremental_lift_pct
		summarizeBy: none
		sourceColumn: incremental_lift_pct

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cannibalization Pct'
		dataType: double
		lineageTag: b2000000-0000-0000-0002-000000000010
		sourceLineageTag: cannibalization_pct
		summarizeBy: none
		sourceColumn: cannibalization_pct

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Lift Pct'
		dataType: double
		lineageTag: b2000000-0000-0000-0002-000000000011
		sourceLineageTag: net_lift_pct
		summarizeBy: none
		sourceColumn: net_lift_pct

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ROI Category'
		dataType: string
		lineageTag: b2000000-0000-0000-0002-000000000012
		sourceLineageTag: roi_category
		summarizeBy: none
		sourceColumn: roi_category

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Computed At'
		dataType: dateTime
		formatString: General Date
		lineageTag: b2000000-0000-0000-0002-000000000013
		sourceLineageTag: computed_at
		summarizeBy: none
		sourceColumn: computed_at

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition 'Promotion Lift' = entity
		mode: directLake
		source
			entityName: promotion_lift
			schemaName: au
			expressionSource: 'DirectLake - retail_lakehouse'
