table 'Zone Dwell Stats'
	lineageTag: b3000000-0000-0000-0000-000000000000
	sourceLineageTag: [au].[zone_dwell_stats]

	measure 'Avg Zone Dwell (seconds)' = AVERAGE('Zone Dwell Stats'[Avg Dwell Seconds])
		formatString: #,0.0
		lineageTag: b3000000-0000-0000-0001-000000000001

	measure 'Total Zone Visits' = SUM('Zone Dwell Stats'[Visit Count])
		formatString: #,0
		lineageTag: b3000000-0000-0000-0001-000000000002

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: b3000000-0000-0000-0002-000000000001
		sourceLineageTag: store_id
		summarizeBy: none
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: b3000000-0000-0000-0002-000000000002
		sourceLineageTag: zone
		summarizeBy: none
		sourceColumn: zone

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Avg Dwell Seconds'
		dataType: double
		lineageTag: b3000000-0000-0000-0002-000000000003
		sourceLineageTag: avg_dwell_seconds
		summarizeBy: none
		sourceColumn: avg_dwell_seconds

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Median Dwell Seconds'
		dataType: double
		lineageTag: b3000000-0000-0000-0002-000000000004
		sourceLineageTag: median_dwell_seconds
		summarizeBy: none
		sourceColumn: median_dwell_seconds

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Min Dwell Seconds'
		dataType: double
		lineageTag: b3000000-0000-0000-0002-000000000005
		sourceLineageTag: min_dwell_seconds
		summarizeBy: none
		sourceColumn: min_dwell_seconds

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Max Dwell Seconds'
		dataType: double
		lineageTag: b3000000-0000-0000-0002-000000000006
		sourceLineageTag: max_dwell_seconds
		summarizeBy: none
		sourceColumn: max_dwell_seconds

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Visit Count'
		dataType: int64
		formatString: 0
		lineageTag: b3000000-0000-0000-0002-000000000007
		sourceLineageTag: visit_count
		summarizeBy: sum
		sourceColumn: visit_count

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Computed At'
		dataType: dateTime
		formatString: General Date
		lineageTag: b3000000-0000-0000-0002-000000000008
		sourceLineageTag: computed_at
		summarizeBy: none
		sourceColumn: computed_at

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition 'Zone Dwell Stats' = entity
		mode: directLake
		source
			entityName: zone_dwell_stats
			schemaName: au
			expressionSource: 'DirectLake - retail_lakehouse'
