core:
  workspace:
    dev: retail-demo-dev
  repository_directory: ../workspace
  item_types_in_scope:
  - Lakehouse
  - Notebook
  - SemanticModel
  - Report
  - KQLQueryset
  parameter: parameter.yml
publish:
  skip:
    dev: false
unpublish:
  skip:
    dev: true
  exclude_regex:
    dev: ^DO_NOT_DELETE_.*
