# Example configuration for the omnichannel data generator module.

time:
  start: "2025-09-01T00:00:00Z"
  end: "2025-09-30T23:59:59Z"
  snapshot_interval_minutes: 60

network:
  dcs: 3
  stores: 120
  store_accuracy_mean: 0.93
  store_accuracy_std: 0.04
  default_safety_stock: 2

routing:
  allow_split: true
  max_nodes: 2
  shortlist_k: 5
  sla_penalty_lambda: 0.8
  split_penalty: 1.5
  use_inbound_windowing: true
  data_staleness_sec: 300

costs:
  ship_base_dc: 2.0
  ship_base_store: 3.5
  per_km: 0.03
  per_kg: 0.10
  handling_dc: 0.75
  handling_store: 2.00

capacity:
  pick_rate_store_mean: 50
  pick_rate_store_std: 10
  backlog_shock_probability: 0.05

bopis:
  enable: true
  curbside_enable: true
  promise_buffer_minutes: 60
  store_closed_reject: true

noise:
  inventory_miscount_rate: 0.02
  event_latency_seconds_p95: 120
  ooo_events_probability: 0.01
  pick_fail_rate: 0.01
  reroute_enable: true

seasonality:
  weekend_multiplier: 1.2
  promo_days:
    - "2025-09-15"
    - "2025-09-16"
  promo_multiplier: 1.5

reproducibility:
  base_seed: 424242

scenarios:
  - name: promo_spike_sept
    start: "2025-09-15T00:00:00Z"
    end: "2025-09-16T23:59:59Z"
    region: "midwest"
    effect: "promo_spike"
    multiplier: 1.5
