# %% [markdown]
# # Setup 04 — Build gold aggregates
# Part of the retail-demo setup utility. Re-runnable (overwrite-by-design).
#
# Requires setup-03 (facts persisted to the silver schema). The engine cell
# below is generated by `scripts/build_notebooks.py` — edit the package
# sources under `utility/src/retail_setup/`, never the cell.

# %%
# PARAMETERS — rendered by `retail-setup render`; defaults work unrendered
def _param(value: str, default: str) -> str:
    return default if value.startswith("{{") else value

LAKEHOUSE_NAME = _param("{{LAKEHOUSE_NAME}}", "retail_lakehouse")
SILVER_DB = _param("{{SILVER_DB}}", "ag")
GOLD_DB = _param("{{GOLD_DB}}", "au")
STORE_TYPE = _param("{{STORE_TYPE}}", "supercenter")
START_DATE = _param("{{START_DATE}}", "2025-01-01")
END_DATE = _param("{{END_DATE}}", "2025-03-31")
STORE_COUNT = int(_param("{{STORE_COUNT}}", "50"))
SEED = int(_param("{{SEED}}", "42"))
DICTIONARY_REF = _param("{{DICTIONARY_REF}}", "main")

spark.conf.set("spark.sql.session.timeZone", "UTC")  # engine timestamps depend on it

# %% [engine]

# %% [markdown]
# ## Read persisted facts, build the nine gold tables, write

# %%
# Gold derives from what was actually persisted by setup-03 — read the
# source fact tables back from the catalog instead of regenerating.
GOLD_SOURCE_TABLES = [
    "fact_receipts",
    "fact_receipt_lines",
    "fact_online_order_headers",
    "fact_marketing",
    "fact_foot_traffic",
    "fact_truck_moves",
    "fact_store_inventory_txn",
    "fact_dc_inventory_txn",
]
tables = {
    name: spark.table(f"{LAKEHOUSE_NAME}.{SILVER_DB}.{name}")
    for name in GOLD_SOURCE_TABLES
}

gold = generate_gold(spark, tables)

spark.sql(f"CREATE DATABASE IF NOT EXISTS {LAKEHOUSE_NAME}.{GOLD_DB}")
for name in GOLD_TABLES:
    df = gold[name]
    write_to_lakehouse(df, LAKEHOUSE_NAME, GOLD_DB, name)
    print(f"wrote {LAKEHOUSE_NAME}.{GOLD_DB}.{name}: {df.count():,} rows")
