# %% [markdown]
# # Setup 03 — Generate facts
# Part of the retail-demo setup utility. Re-runnable (overwrite-by-design).
#
# Requires setup-01 (dictionaries) and setup-02 (dimensions). The engine cell
# below is generated by `scripts/build_notebooks.py` — edit the package
# sources under `utility/src/retail_setup/`, never the cell.

# %%
# PARAMETERS — rendered by `retail-setup render`; defaults work unrendered
def _param(value: str, default: str) -> str:
    return default if len(value) > 1 and value[0] == value[1] == "{" else value

LAKEHOUSE_NAME = _param("{{LAKEHOUSE_NAME}}", "retail_lakehouse")
SILVER_DB = _param("{{SILVER_DB}}", "ag")
GOLD_DB = _param("{{GOLD_DB}}", "au")
STORE_TYPE = _param("{{STORE_TYPE}}", "supercenter")
START_DATE = _param("{{START_DATE}}", "2025-01-01")
END_DATE = _param("{{END_DATE}}", "2025-03-31")
STORE_COUNT = int(_param("{{STORE_COUNT}}", "50"))
SEED = int(_param("{{SEED}}", "42"))
DICTIONARY_REF = _param("{{DICTIONARY_REF}}", "main")

spark.conf.set("spark.sql.session.timeZone", "UTC")  # engine timestamps depend on it

# %% [engine]

# %% [markdown]
# ## Generate facts, check invariants, write

# %%
from datetime import date

cfg = GenerationConfig(
    store_type=STORE_TYPE,
    start_date=date.fromisoformat(START_DATE),
    end_date=date.fromisoformat(END_DATE),
    store_count=STORE_COUNT,
    seed=SEED,
    silver_db=SILVER_DB,
    gold_db=GOLD_DB,
    dictionary_root="/lakehouse/default/Files/setup/dictionaries",
)
dicts = load_dictionaries(cfg.resolved_dictionary_root, cfg.store_type)

# Dimensions are regenerated in-memory rather than read back from the
# catalog: generation is fully deterministic (same seed => identical dims,
# byte for byte), the engine needs the dim DataFrames as inputs anyway, and
# regenerating is cheaper than a catalog round-trip. setup-02 remains the
# source of the *persisted* dims; the overwrite below re-writes identical
# data at worst.
result = generate_all(spark, dicts, cfg)

# %%
report = run_invariants(spark, result.tables)
print(f"invariant checks run: {len(report.checks)}")
for name, count in sorted(report.row_counts.items()):
    print(f"  {name:40s} {count:>12,} rows")
if not report.passed:
    for failure in report.failures:
        print(f"FAILED: {failure}")
    raise RuntimeError(f"invariant failures: {report.failures}")
print("all invariants passed")

# %%
run_id = f"setup-{STORE_TYPE}-{SEED}"
# Gold is built in setup-04 from the persisted tables — pass an empty dict.
written = write_all(result.tables, {}, cfg, run_id, lakehouse=LAKEHOUSE_NAME)
print(f"wrote {len(written)} tables to {LAKEHOUSE_NAME}.{SILVER_DB} (run_id={run_id})")
