# %% [markdown]
# # Setup 04 — Build gold aggregates
# Part of the retail-demo setup utility. Re-runnable (overwrite-by-design).
#
# Requires setup-03 (facts persisted to the silver schema). The engine cell
# below is generated by `scripts/build_notebooks.py` — edit the package
# sources under `utility/src/retail_setup/`, never the cell.

# %%
# Fabric's Spark runtime ships an OLD typing_extensions and no pydantic, while the
# inlined engine below imports pydantic. Install both on the driver, then make the
# new typing_extensions actually load. Why each step:
#  - subprocess pip (not %pip): a %pip kernel restart tears down the Spark session
#    mid pipeline run and fails the activity.
#  - pin pydantic <2.12: 2.12+ imports typing_extensions.Sentinel.
#  - drop the stale modules from sys.modules: the runtime already imported the old
#    typing_extensions, so the freshly installed copy is shadowed; evicting it lets
#    the engine cell re-import the upgraded versions (pydantic needs symbols such
#    as TypeIs that the runtime's typing_extensions lacks).
#  - pydantic runs only on the driver (engine builds rows, then
#    spark.createDataFrame), so a driver-side install is sufficient.
import importlib
import subprocess
import sys

subprocess.check_call([
    sys.executable, "-m", "pip", "install", "--quiet",
    "annotated-types==0.7.0", "pydantic==2.11.10",
    "pydantic-core==2.33.2", "typing-inspection==0.4.2",
    "typing_extensions==4.15.0",
])
for _name in [m for m in list(sys.modules)
              if m.split(".", 1)[0] in {"typing_extensions", "typing_inspection",
                                        "pydantic", "pydantic_core"}]:
    del sys.modules[_name]
importlib.invalidate_caches()

# %%
# PARAMETERS — rendered by `retail-setup render`; defaults work unrendered
def _param(value: str, default: str) -> str:
    return default if len(value) > 1 and value[0] == value[1] == "{" else value

LAKEHOUSE_NAME = _param("{{LAKEHOUSE_NAME}}", "retail_lakehouse")
SILVER_DB = _param("{{SILVER_DB}}", "ag")
GOLD_DB = _param("{{GOLD_DB}}", "au")
STORE_TYPE = _param("{{STORE_TYPE}}", "supercenter")
START_DATE = _param("{{START_DATE}}", "2025-01-01")
END_DATE = _param("{{END_DATE}}", "2025-03-31")
STORE_COUNT = int(_param("{{STORE_COUNT}}", "50"))
SEED = int(_param("{{SEED}}", "42"))
DICTIONARY_REF = _param("{{DICTIONARY_REF}}", "main")

spark.conf.set("spark.sql.session.timeZone", "UTC")  # engine timestamps depend on it
# Reorder seeded-draw / aggregate math ((a/1e12)*k -> (a*k)/1e12) to cut
# rounding-error propagation and silence Fabric's Spark advisor. The rewrite
# shifts values by <=1 ULP (generation is statistical, no exact-value contracts);
# set in every engine driver so dims and facts stay mutually consistent.
spark.conf.set("spark.advise.divisionExprConvertRule.enable", "true")

# %% [engine]

# %% [markdown]
# ## Read persisted facts, build the ten gold tables, publish

# %%
from datetime import date, datetime, timezone
from uuid import uuid4

# Gold derives from what was actually persisted by setup-03 — read the
# source fact tables back from the catalog instead of regenerating.
GOLD_SOURCE_TABLES = [
    "fact_receipts",
    "fact_receipt_lines",
    "fact_online_order_headers",
    "fact_marketing",
    "fact_foot_traffic",
    "fact_truck_moves",
    "fact_store_inventory_txn",
    "fact_dc_inventory_txn",
]
tables = {
    name: spark.table(f"{LAKEHOUSE_NAME}.{SILVER_DB}.{name}")
    for name in GOLD_SOURCE_TABLES
}

gold = generate_gold(spark, tables)

# cfg only carries run-log metadata here (gold doesn't regenerate from
# dictionaries) — write_all stages every gold table, validates it against
# the in-memory aggregate, and only then promotes to GOLD_DB, rolling back
# any already-promoted table if a later promotion fails.
cfg = GenerationConfig(
    store_type=STORE_TYPE,
    start_date=date.fromisoformat(START_DATE),
    end_date=date.fromisoformat(END_DATE),
    store_count=STORE_COUNT,
    seed=SEED,
    silver_db=SILVER_DB,
    gold_db=GOLD_DB,
    dictionary_root="/lakehouse/default/Files/setup/dictionaries",
)
attempt_ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
run_id = f"setup-gold-{STORE_TYPE}-{SEED}-{attempt_ts}-{uuid4().hex[:8]}"
written = write_all({}, gold, cfg, run_id, lakehouse=LAKEHOUSE_NAME)
for name in written:
    n = spark.table(f"{LAKEHOUSE_NAME}.{GOLD_DB}.{name}").count()
    print(f"wrote {LAKEHOUSE_NAME}.{GOLD_DB}.{name}: {n:,} rows")
print(f"published {len(written)} gold tables (run_id={run_id})")
