model RetailGold
  compatibilityLevel: 1603

  annotation fabric.lakehouseResourceId = "<fabric-lakehouse-resource-id>"

table gold_sales_minute_store

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: sales_minute_store

  measure 'Total Sales' = SUM('gold_sales_minute_store'[total_sales])

  measure Receipts = SUM('gold_sales_minute_store'[receipts])

  measure 'Avg Basket' = DIVIDE([Total Sales], [Receipts])

  measure 'Sales (Last 60m)' = CALCULATE([Total Sales], KEEPFILTERS(DATESINPERIOD('gold_sales_minute_store'[ts], MAX('gold_sales_minute_store'[ts]), -60, MINUTE)))

table gold_top_products_15m

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: top_products_15m

  measure Revenue = SUM('gold_top_products_15m'[revenue])

  measure Units = SUM('gold_top_products_15m'[units])

table gold_inventory_position_current

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: inventory_position_current

  measure 'On Hand' = SUM('gold_inventory_position_current'[on_hand])

table gold_truck_dwell_daily

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: truck_dwell_daily

  measure 'Avg Dwell (min)' = AVERAGE('gold_truck_dwell_daily'[avg_dwell_min])

table dim_stores

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: dim_stores

table dim_products

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: dim_products

table gold_online_sales_daily

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: online_sales_daily

  measure Orders = SUM('gold_online_sales_daily'[orders])

  measure 'Online Total' = SUM('gold_online_sales_daily'[total])

  measure AOV = DIVIDE([Online Total], [Orders])

table gold_zone_dwell_minute

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: zone_dwell_minute

  measure 'Avg Dwell (sec)' = AVERAGE('gold_zone_dwell_minute'[avg_dwell])

  measure 'Customers (Minute)' = SUM('gold_zone_dwell_minute'[customers])

table gold_marketing_cost_daily

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: marketing_cost_daily

  measure Impressions = SUM('gold_marketing_cost_daily'[impressions])

  measure Cost = SUM('gold_marketing_cost_daily'[cost])

table gold_dc_inventory_position_current

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: dc_inventory_position_current

  measure 'DC On Hand' = SUM('gold_dc_inventory_position_current'[on_hand])

table gold_tender_mix_daily

  partition DirectLake
    mode: directLake
    source
      type: entity
      entityName: tender_mix_daily

  measure Transactions = SUM('gold_tender_mix_daily'[transactions])

  measure 'Total Amount' = SUM('gold_tender_mix_daily'[total_amount])

relationship Sales_to_Stores
  fromColumn: gold_sales_minute_store.store_id
  toColumn: dim_stores.ID
  crossFilteringBehavior: oneDirection

relationship InvCurrent_to_Stores
  fromColumn: gold_inventory_position_current.store_id
  toColumn: dim_stores.ID
  crossFilteringBehavior: oneDirection

relationship TopProducts_to_Products
  fromColumn: gold_top_products_15m.product_id
  toColumn: dim_products.ID
  crossFilteringBehavior: oneDirection

relationship InvCurrent_to_Products
  fromColumn: gold_inventory_position_current.product_id
  toColumn: dim_products.ID
  crossFilteringBehavior: oneDirection

perspective Operations

  perspectiveTable gold_sales_minute_store

  perspectiveTable gold_inventory_position_current

  perspectiveTable gold_dc_inventory_position_current

  perspectiveTable dim_stores

  perspectiveTable gold_zone_dwell_minute

  perspectiveTable gold_tender_mix_daily

perspective Merchandising

  perspectiveTable gold_top_products_15m

  perspectiveTable gold_inventory_position_current

  perspectiveTable dim_products

  perspectiveTable gold_online_sales_daily

perspective Logistics

  perspectiveTable gold_truck_dwell_daily

  perspectiveTable gold_dc_inventory_position_current

perspective Marketing

  perspectiveTable gold_marketing_cost_daily
