environment = "dev"
workspace_name = "retail-demo-dev"
workspace_description = "Microsoft Fabric retail demo workspace"
skip_capacity_state_validation = false
role_assignments = []
lakehouse_name = "retail_lakehouse"
lakehouse_enable_schemas = true
eventhouse_name = "retail_eventhouse"
spark_custom_pool_enabled = true
spark_custom_pool_name = "retail_setup_pool"
spark_node_size = "Medium"
spark_min_node_count = 1
spark_max_node_count = 10
tenant_id = "9d379b85-7b26-46a5-bbc8-2ce467f202b8"
capacity_name = "amattas"
