environment = "dev"
workspace_name = "retail-demo-dev"
workspace_description = "Microsoft Fabric retail demo workspace"
skip_capacity_state_validation = false
role_assignments = []
lakehouse_name = "retail_lakehouse"
lakehouse_enable_schemas = true
eventhouse_name = "retail_eventhouse"
kql_database_name = "retail_kql"
eventstream_enabled = false
eventstream_name = "retail_eventstream"
