"""
FastAPI web interface for the retail data generator.
"""

from .export_models import (
    VALID_FACT_TABLES,
    VALID_MASTER_TABLES,
    ExportFormat,
    ExportOperationResult,
    ExportRequest,
    ExportStatus,
    ExportStatusResponse,
    ExportSummaryResponse,
    ExportTableInfo,
    FactExportRequest,
    TableCategory,
    validate_table_names,
)
from .models import (
    ActiveDisruptionsResponse,
    BatchOperationStatus,
    ConfigUpdateRequest,
    ConnectionTestResponse,
    DisruptionRequest,
    DisruptionResponse,
    DisruptionType,
    ErrorResponse,
    GenerationStatus,
    GenerationStatusResponse,
    HealthCheckResponse,
    HistoricalDataRequest,
    MasterDataRequest,
    OperationResult,
    RecentEventsResponse,
    StreamingConfigUpdate,
    StreamingStartRequest,
    StreamingStatisticsResponse,
    StreamingStatus,
    StreamingStatusResponse,
    TableListResponse,
    TablePreviewResponse,
    ValidationErrorResponse,
)

__all__ = [
    # Export models
    "ExportFormat",
    "ExportOperationResult",
    "ExportRequest",
    "ExportStatus",
    "ExportStatusResponse",
    "ExportSummaryResponse",
    "ExportTableInfo",
    "FactExportRequest",
    "TableCategory",
    "validate_table_names",
    "VALID_FACT_TABLES",
    "VALID_MASTER_TABLES",
    # Generation models
    "GenerationStatus",
    "GenerationStatusResponse",
    "MasterDataRequest",
    "HistoricalDataRequest",
    "ConfigUpdateRequest",
    # Streaming models
    "StreamingStatus",
    "StreamingStatusResponse",
    "StreamingStatisticsResponse",
    "StreamingStartRequest",
    "StreamingConfigUpdate",
    # Response models
    "TableListResponse",
    "TablePreviewResponse",
    "HealthCheckResponse",
    "ConnectionTestResponse",
    "ErrorResponse",
    "ValidationErrorResponse",
    "OperationResult",
    "BatchOperationStatus",
    "RecentEventsResponse",
    # Disruption models
    "DisruptionType",
    "DisruptionRequest",
    "DisruptionResponse",
    "ActiveDisruptionsResponse",
]
