"""
Geographies source data for supercenter retail profile.

This data is 100% synthetic and safe for demo/POC purposes.
"""

GEOGRAPHIES = [
    {'City': 'Springfield', 'State': 'IL', 'Zip': '62701', 'District': 'Central Illinois', 'Region': 'Midwest'},
    {'City': 'Franklin', 'State': 'TN', 'Zip': '37067', 'District': 'Middle Tennessee', 'Region': 'Southeast'},
    {'City': 'Riverside', 'State': 'CA', 'Zip': '92501', 'District': 'Inland Empire', 'Region': 'West'},
    {'City': 'Arlington', 'State': 'TX', 'Zip': '76001', 'District': 'North Texas', 'Region': 'Southwest'},
    {'City': 'Madison', 'State': 'WI', 'Zip': '53701', 'District': 'South Central Wisconsin', 'Region': 'Midwest'},
    {'City': 'Fairfield', 'State': 'CT', 'Zip': '06824', 'District': 'Fairfield County', 'Region': 'Northeast'},
    {'City': 'Greenwood', 'State': 'SC', 'Zip': '29646', 'District': 'Upstate South Carolina', 'Region': 'Southeast'},
    {'City': 'Lakewood', 'State': 'CO', 'Zip': '80226', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Burlington', 'State': 'VT', 'Zip': '05401', 'District': 'Chittenden County', 'Region': 'Northeast'},
    {'City': 'Westfield', 'State': 'MA', 'Zip': '01085', 'District': 'Pioneer Valley', 'Region': 'Northeast'},
    {'City': 'Clearwater', 'State': 'FL', 'Zip': '33755', 'District': 'Pinellas County', 'Region': 'Southeast'},
    {'City': 'Newton', 'State': 'KS', 'Zip': '67114', 'District': 'South Central Kansas', 'Region': 'Midwest'},
    {'City': 'Ashland', 'State': 'OR', 'Zip': '97520', 'District': 'Rogue Valley', 'Region': 'West'},
    {'City': 'Chester', 'State': 'PA', 'Zip': '19013', 'District': 'Delaware County', 'Region': 'Northeast'},
    {'City': 'Richmond', 'State': 'VA', 'Zip': '23219', 'District': 'Richmond Metro', 'Region': 'Southeast'},
    {'City': 'Bloomington', 'State': 'IN', 'Zip': '47401', 'District': 'South Central Indiana', 'Region': 'Midwest'},
    {'City': 'Fairview', 'State': 'NJ', 'Zip': '07022', 'District': 'Bergen County', 'Region': 'Northeast'},
    {'City': 'Hillsboro', 'State': 'OR', 'Zip': '97123', 'District': 'Washington County', 'Region': 'West'},
    {'City': 'Georgetown', 'State': 'TX', 'Zip': '78626', 'District': 'Williamson County', 'Region': 'Southwest'},
    {'City': 'Lancaster', 'State': 'PA', 'Zip': '17601', 'District': 'Lancaster County', 'Region': 'Northeast'},
    {'City': 'Marietta', 'State': 'GA', 'Zip': '30060', 'District': 'Cobb County', 'Region': 'Southeast'},
    {'City': 'Plymouth', 'State': 'MN', 'Zip': '55441', 'District': 'Hennepin County', 'Region': 'Midwest'},
    {'City': 'Redwood City', 'State': 'CA', 'Zip': '94061', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Thornton', 'State': 'CO', 'Zip': '80229', 'District': 'Adams County', 'Region': 'West'},
    {'City': 'Bridgeport', 'State': 'CT', 'Zip': '06604', 'District': 'Fairfield County', 'Region': 'Northeast'},
    {'City': 'Columbia', 'State': 'SC', 'Zip': '29201', 'District': 'Midlands South Carolina', 'Region': 'Southeast'},
    {'City': 'Cedar Rapids', 'State': 'IA', 'Zip': '52401', 'District': 'Linn County', 'Region': 'Midwest'},
    {'City': 'Fremont', 'State': 'CA', 'Zip': '94536', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Aurora', 'State': 'IL', 'Zip': '60502', 'District': 'Kane County', 'Region': 'Midwest'},
    {'City': 'Hampton', 'State': 'VA', 'Zip': '23663', 'District': 'Hampton Roads', 'Region': 'Southeast'},
    {'City': 'Mansfield', 'State': 'TX', 'Zip': '76063', 'District': 'Tarrant County', 'Region': 'Southwest'},
    {'City': 'Valdosta', 'State': 'GA', 'Zip': '31601', 'District': 'South Georgia', 'Region': 'Southeast'},
    {'City': 'Watertown', 'State': 'NY', 'Zip': '13601', 'District': 'Jefferson County', 'Region': 'Northeast'},
    {'City': 'Brookfield', 'State': 'WI', 'Zip': '53005', 'District': 'Waukesha County', 'Region': 'Midwest'},
    {'City': 'Huntsville', 'State': 'AL', 'Zip': '35801', 'District': 'North Alabama', 'Region': 'Southeast'},
    {'City': 'Glendale', 'State': 'AZ', 'Zip': '85301', 'District': 'Maricopa County', 'Region': 'Southwest'},
    {'City': 'Milford', 'State': 'CT', 'Zip': '06460', 'District': 'New Haven County', 'Region': 'Northeast'},
    {'City': 'Rockford', 'State': 'IL', 'Zip': '61101', 'District': 'Winnebago County', 'Region': 'Midwest'},
    {'City': 'Salem', 'State': 'OR', 'Zip': '97301', 'District': 'Marion County', 'Region': 'West'},
    {'City': 'Bristol', 'State': 'TN', 'Zip': '37620', 'District': 'Northeast Tennessee', 'Region': 'Southeast'},
    {'City': 'Concord', 'State': 'NH', 'Zip': '03301', 'District': 'Merrimack County', 'Region': 'Northeast'},
    {'City': 'Davenport', 'State': 'IA', 'Zip': '52801', 'District': 'Scott County', 'Region': 'Midwest'},
    {'City': 'Pasadena', 'State': 'CA', 'Zip': '91101', 'District': 'Los Angeles County', 'Region': 'West'},
    {'City': 'Longmont', 'State': 'CO', 'Zip': '80501', 'District': 'Boulder County', 'Region': 'West'},
    {'City': 'Norwalk', 'State': 'CT', 'Zip': '06850', 'District': 'Fairfield County', 'Region': 'Northeast'},
    {'City': 'Savannah', 'State': 'GA', 'Zip': '31401', 'District': 'Coastal Georgia', 'Region': 'Southeast'},
    {'City': 'Elkhart', 'State': 'IN', 'Zip': '46514', 'District': 'Elkhart County', 'Region': 'Midwest'},
    {'City': 'Reno', 'State': 'NV', 'Zip': '89501', 'District': 'Washoe County', 'Region': 'West'},
    {'City': 'Baytown', 'State': 'TX', 'Zip': '77520', 'District': 'Harris County', 'Region': 'Southwest'},
    {'City': 'Danbury', 'State': 'CT', 'Zip': '06810', 'District': 'Fairfield County', 'Region': 'Northeast'},
    {'City': 'Spartanburg', 'State': 'SC', 'Zip': '29301', 'District': 'Upstate South Carolina', 'Region': 'Southeast'},
    {'City': 'Kenosha', 'State': 'WI', 'Zip': '53140', 'District': 'Kenosha County', 'Region': 'Midwest'},
    {'City': 'Chico', 'State': 'CA', 'Zip': '95926', 'District': 'Butte County', 'Region': 'West'},
    {'City': 'Pueblo', 'State': 'CO', 'Zip': '81001', 'District': 'Pueblo County', 'Region': 'West'},
    {'City': 'Middletown', 'State': 'CT', 'Zip': '06457', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Macon', 'State': 'GA', 'Zip': '31201', 'District': 'Central Georgia', 'Region': 'Southeast'},
    {'City': 'Ames', 'State': 'IA', 'Zip': '50010', 'District': 'Story County', 'Region': 'Midwest'},
    {'City': 'Stockton', 'State': 'CA', 'Zip': '95202', 'District': 'San Joaquin County', 'Region': 'West'},
    {'City': 'Tyler', 'State': 'TX', 'Zip': '75701', 'District': 'East Texas', 'Region': 'Southwest'},
    {'City': 'Nashua', 'State': 'NH', 'Zip': '03060', 'District': 'Hillsborough County', 'Region': 'Northeast'},
    {'City': 'Augusta', 'State': 'GA', 'Zip': '30901', 'District': 'Central Savannah River', 'Region': 'Southeast'},
    {'City': 'Racine', 'State': 'WI', 'Zip': '53402', 'District': 'Racine County', 'Region': 'Midwest'},
    {'City': 'Visalia', 'State': 'CA', 'Zip': '93291', 'District': 'Tulare County', 'Region': 'West'},
    {'City': 'Fort Collins', 'State': 'CO', 'Zip': '80521', 'District': 'Larimer County', 'Region': 'West'},
    {'City': 'Stamford', 'State': 'CT', 'Zip': '06901', 'District': 'Fairfield County', 'Region': 'Northeast'},
    {'City': 'Columbus', 'State': 'GA', 'Zip': '31901', 'District': 'Muscogee County', 'Region': 'Southeast'},
    {'City': 'Dubuque', 'State': 'IA', 'Zip': '52001', 'District': 'Dubuque County', 'Region': 'Midwest'},
    {'City': 'Modesto', 'State': 'CA', 'Zip': '95350', 'District': 'Stanislaus County', 'Region': 'West'},
    {'City': 'Lubbock', 'State': 'TX', 'Zip': '79401', 'District': 'West Texas', 'Region': 'Southwest'},
    {'City': 'Manchester', 'State': 'NH', 'Zip': '03101', 'District': 'Hillsborough County', 'Region': 'Northeast'},
    {'City': 'Albany', 'State': 'GA', 'Zip': '31701', 'District': 'Southwest Georgia', 'Region': 'Southeast'},
    {'City': 'La Crosse', 'State': 'WI', 'Zip': '54601', 'District': 'La Crosse County', 'Region': 'Midwest'},
    {'City': 'Salinas', 'State': 'CA', 'Zip': '93901', 'District': 'Monterey County', 'Region': 'West'},
    {'City': 'Boulder', 'State': 'CO', 'Zip': '80301', 'District': 'Boulder County', 'Region': 'West'},
    {'City': 'Hartford', 'State': 'CT', 'Zip': '06101', 'District': 'Hartford County', 'Region': 'Northeast'},
    {'City': 'Warner Robins', 'State': 'GA', 'Zip': '31093', 'District': 'Central Georgia', 'Region': 'Southeast'},
    {'City': 'Cedar Falls', 'State': 'IA', 'Zip': '50613', 'District': 'Black Hawk County', 'Region': 'Midwest'},
    {'City': 'Fresno', 'State': 'CA', 'Zip': '93701', 'District': 'Fresno County', 'Region': 'West'},
    {'City': 'Amarillo', 'State': 'TX', 'Zip': '79101', 'District': 'Texas Panhandle', 'Region': 'Southwest'},
    {'City': 'Concord', 'State': 'NH', 'Zip': '03302', 'District': 'Merrimack County', 'Region': 'Northeast'},
    {'City': 'Valdosta', 'State': 'GA', 'Zip': '31602', 'District': 'South Georgia', 'Region': 'Southeast'},
    {'City': 'Waterloo', 'State': 'IA', 'Zip': '50701', 'District': 'Black Hawk County', 'Region': 'Midwest'},
    {'City': 'Santa Rosa', 'State': 'CA', 'Zip': '95401', 'District': 'Sonoma County', 'Region': 'West'},
    {'City': 'Westminster', 'State': 'CO', 'Zip': '80030', 'District': 'Adams County', 'Region': 'West'},
    {'City': 'New Britain', 'State': 'CT', 'Zip': '06050', 'District': 'Hartford County', 'Region': 'Northeast'},
    {'City': 'Rome', 'State': 'GA', 'Zip': '30161', 'District': 'Northwest Georgia', 'Region': 'Southeast'},
    {'City': 'Mason City', 'State': 'IA', 'Zip': '50401', 'District': 'Cerro Gordo County', 'Region': 'Midwest'},
    {'City': 'Antioch', 'State': 'CA', 'Zip': '94509', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Odessa', 'State': 'TX', 'Zip': '79761', 'District': 'West Texas', 'Region': 'Southwest'},
    {'City': 'Dover', 'State': 'NH', 'Zip': '03820', 'District': 'Strafford County', 'Region': 'Northeast'},
    {'City': 'Gainesville', 'State': 'GA', 'Zip': '30501', 'District': 'North Georgia', 'Region': 'Southeast'},
    {'City': 'Sioux City', 'State': 'IA', 'Zip': '51101', 'District': 'Woodbury County', 'Region': 'Midwest'},
    {'City': 'Concord', 'State': 'CA', 'Zip': '94519', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Grand Junction', 'State': 'CO', 'Zip': '81501', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'Waterbury', 'State': 'CT', 'Zip': '06701', 'District': 'New Haven County', 'Region': 'Northeast'},
    {'City': 'Dalton', 'State': 'GA', 'Zip': '30720', 'District': 'Northwest Georgia', 'Region': 'Southeast'},
    {'City': 'Burlington', 'State': 'IA', 'Zip': '52601', 'District': 'Des Moines County', 'Region': 'Midwest'},
    {'City': 'Richmond', 'State': 'CA', 'Zip': '94801', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Midland', 'State': 'TX', 'Zip': '79701', 'District': 'West Texas', 'Region': 'Southwest'},
    {'City': 'Keene', 'State': 'NH', 'Zip': '03431', 'District': 'Cheshire County', 'Region': 'Northeast'},
    {'City': 'Hinesville', 'State': 'GA', 'Zip': '31313', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Fort Dodge', 'State': 'IA', 'Zip': '50501', 'District': 'Webster County', 'Region': 'Midwest'},
    {'City': 'Fairfield', 'State': 'CA', 'Zip': '94533', 'District': 'Solano County', 'Region': 'West'},
    {'City': 'Lakewood', 'State': 'CO', 'Zip': '80215', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Meriden', 'State': 'CT', 'Zip': '06450', 'District': 'New Haven County', 'Region': 'Northeast'},
    {'City': 'LaGrange', 'State': 'GA', 'Zip': '30240', 'District': 'West Georgia', 'Region': 'Southeast'},
    {'City': 'Ottumwa', 'State': 'IA', 'Zip': '52501', 'District': 'Wapello County', 'Region': 'Midwest'},
    {'City': 'Vallejo', 'State': 'CA', 'Zip': '94590', 'District': 'Solano County', 'Region': 'West'},
    {'City': 'Thornton', 'State': 'CO', 'Zip': '80241', 'District': 'Adams County', 'Region': 'West'},
    {'City': 'New Haven', 'State': 'CT', 'Zip': '06511', 'District': 'New Haven County', 'Region': 'Northeast'},
    {'City': 'Griffin', 'State': 'GA', 'Zip': '30223', 'District': 'Central Georgia', 'Region': 'Southeast'},
    {'City': 'Clinton', 'State': 'IA', 'Zip': '52732', 'District': 'Clinton County', 'Region': 'Midwest'},
    {'City': 'Petaluma', 'State': 'CA', 'Zip': '94952', 'District': 'Sonoma County', 'Region': 'West'},
    {'City': 'Arvada', 'State': 'CO', 'Zip': '80001', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Torrington', 'State': 'CT', 'Zip': '06790', 'District': 'Litchfield County', 'Region': 'Northeast'},
    {'City': 'Carrollton', 'State': 'GA', 'Zip': '30117', 'District': 'West Georgia', 'Region': 'Southeast'},
    {'City': 'Marshalltown', 'State': 'IA', 'Zip': '50158', 'District': 'Marshall County', 'Region': 'Midwest'},
    {'City': 'Napa', 'State': 'CA', 'Zip': '94558', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Englewood', 'State': 'CO', 'Zip': '80110', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'Shelton', 'State': 'CT', 'Zip': '06484', 'District': 'Fairfield County', 'Region': 'Northeast'},
    {'City': 'Douglas', 'State': 'GA', 'Zip': '31533', 'District': 'South Georgia', 'Region': 'Southeast'},
    {'City': 'Newton', 'State': 'IA', 'Zip': '50208', 'District': 'Jasper County', 'Region': 'Midwest'},
    {'City': 'San Rafael', 'State': 'CA', 'Zip': '94901', 'District': 'Marin County', 'Region': 'West'},
    {'City': 'Wheat Ridge', 'State': 'CO', 'Zip': '80033', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Ansonia', 'State': 'CT', 'Zip': '06401', 'District': 'New Haven County', 'Region': 'Northeast'},
    {'City': 'Statesboro', 'State': 'GA', 'Zip': '30458', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Indianola', 'State': 'IA', 'Zip': '50125', 'District': 'Warren County', 'Region': 'Midwest'},
    {'City': 'Hayward', 'State': 'CA', 'Zip': '94541', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Broomfield', 'State': 'CO', 'Zip': '80020', 'District': 'Broomfield County', 'Region': 'West'},
    {'City': 'Winsted', 'State': 'CT', 'Zip': '06098', 'District': 'Litchfield County', 'Region': 'Northeast'},
    {'City': 'Fitzgerald', 'State': 'GA', 'Zip': '31750', 'District': 'South Georgia', 'Region': 'Southeast'},
    {'City': 'Spencer', 'State': 'IA', 'Zip': '51301', 'District': 'Clay County', 'Region': 'Midwest'},
    {'City': 'Union City', 'State': 'CA', 'Zip': '94587', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Louisville', 'State': 'CO', 'Zip': '80027', 'District': 'Boulder County', 'Region': 'West'},
    {'City': 'Willimantic', 'State': 'CT', 'Zip': '06226', 'District': 'Windham County', 'Region': 'Northeast'},
    {'City': 'Tifton', 'State': 'GA', 'Zip': '31794', 'District': 'South Georgia', 'Region': 'Southeast'},
    {'City': 'Storm Lake', 'State': 'IA', 'Zip': '50588', 'District': 'Buena Vista County', 'Region': 'Midwest'},
    {'City': 'Fremont', 'State': 'CA', 'Zip': '94538', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Lafayette', 'State': 'CO', 'Zip': '80026', 'District': 'Boulder County', 'Region': 'West'},
    {'City': 'Plainville', 'State': 'CT', 'Zip': '06062', 'District': 'Hartford County', 'Region': 'Northeast'},
    {'City': 'Thomasville', 'State': 'GA', 'Zip': '31792', 'District': 'South Georgia', 'Region': 'Southeast'},
    {'City': 'Cherokee', 'State': 'IA', 'Zip': '51012', 'District': 'Cherokee County', 'Region': 'Midwest'},
    {'City': 'Newark', 'State': 'CA', 'Zip': '94560', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Superior', 'State': 'CO', 'Zip': '80027', 'District': 'Boulder County', 'Region': 'West'},
    {'City': 'Seymour', 'State': 'CT', 'Zip': '06483', 'District': 'New Haven County', 'Region': 'Northeast'},
    {'City': 'Moultrie', 'State': 'GA', 'Zip': '31768', 'District': 'South Georgia', 'Region': 'Southeast'},
    {'City': 'Creston', 'State': 'IA', 'Zip': '50801', 'District': 'Union County', 'Region': 'Midwest'},
    {'City': 'Milpitas', 'State': 'CA', 'Zip': '95035', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Northglenn', 'State': 'CO', 'Zip': '80233', 'District': 'Adams County', 'Region': 'West'},
    {'City': 'Cromwell', 'State': 'CT', 'Zip': '06416', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Cairo', 'State': 'GA', 'Zip': '39828', 'District': 'Southwest Georgia', 'Region': 'Southeast'},
    {'City': 'Red Oak', 'State': 'IA', 'Zip': '51566', 'District': 'Montgomery County', 'Region': 'Midwest'},
    {'City': 'Mountain View', 'State': 'CA', 'Zip': '94041', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Federal Heights', 'State': 'CO', 'Zip': '80260', 'District': 'Adams County', 'Region': 'West'},
    {'City': 'Old Saybrook', 'State': 'CT', 'Zip': '06475', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Bainbridge', 'State': 'GA', 'Zip': '39819', 'District': 'Southwest Georgia', 'Region': 'Southeast'},
    {'City': 'Harlan', 'State': 'IA', 'Zip': '51537', 'District': 'Shelby County', 'Region': 'Midwest'},
    {'City': 'Sunnyvale', 'State': 'CA', 'Zip': '94086', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Sheridan', 'State': 'CO', 'Zip': '80110', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'Clinton', 'State': 'CT', 'Zip': '06413', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Americus', 'State': 'GA', 'Zip': '31709', 'District': 'Southwest Georgia', 'Region': 'Southeast'},
    {'City': 'Atlantic', 'State': 'IA', 'Zip': '50022', 'District': 'Cass County', 'Region': 'Midwest'},
    {'City': 'Cupertino', 'State': 'CA', 'Zip': '95014', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Edgewater', 'State': 'CO', 'Zip': '80214', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Essex', 'State': 'CT', 'Zip': '06426', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Cordele', 'State': 'GA', 'Zip': '31015', 'District': 'South Georgia', 'Region': 'Southeast'},
    {'City': 'Audubon', 'State': 'IA', 'Zip': '50025', 'District': 'Audubon County', 'Region': 'Midwest'},
    {'City': 'Los Altos', 'State': 'CA', 'Zip': '94022', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Golden', 'State': 'CO', 'Zip': '80401', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Deep River', 'State': 'CT', 'Zip': '06417', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Jesup', 'State': 'GA', 'Zip': '31545', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Carroll', 'State': 'IA', 'Zip': '51401', 'District': 'Carroll County', 'Region': 'Midwest'},
    {'City': 'Palo Alto', 'State': 'CA', 'Zip': '94301', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Morrison', 'State': 'CO', 'Zip': '80465', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'East Hampton', 'State': 'CT', 'Zip': '06424', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Waycross', 'State': 'GA', 'Zip': '31501', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Denison', 'State': 'IA', 'Zip': '51442', 'District': 'Crawford County', 'Region': 'Midwest'},
    {'City': 'Redwood City', 'State': 'CA', 'Zip': '94063', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Lakeside', 'State': 'CO', 'Zip': '80212', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Haddam', 'State': 'CT', 'Zip': '06438', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Blackshear', 'State': 'GA', 'Zip': '31516', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Glenwood', 'State': 'IA', 'Zip': '51534', 'District': 'Mills County', 'Region': 'Midwest'},
    {'City': 'San Carlos', 'State': 'CA', 'Zip': '94070', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Deer Trail', 'State': 'CO', 'Zip': '80105', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'Killingworth', 'State': 'CT', 'Zip': '06419', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Nahunta', 'State': 'GA', 'Zip': '31553', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Clarinda', 'State': 'IA', 'Zip': '51632', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'Belmont', 'State': 'CA', 'Zip': '94002', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Bennett', 'State': 'CO', 'Zip': '80102', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'East Haddam', 'State': 'CT', 'Zip': '06423', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Folkston', 'State': 'GA', 'Zip': '31537', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Shenandoah', 'State': 'IA', 'Zip': '51601', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'Foster City', 'State': 'CA', 'Zip': '94404', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Bow Mar', 'State': 'CO', 'Zip': '80123', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Westbrook', 'State': 'CT', 'Zip': '06498', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Homeland', 'State': 'GA', 'Zip': '31537', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Sidney', 'State': 'IA', 'Zip': '51652', 'District': 'Fremont County', 'Region': 'Midwest'},
    {'City': 'San Mateo', 'State': 'CA', 'Zip': '94401', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Columbine', 'State': 'CO', 'Zip': '80123', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Portland', 'State': 'CT', 'Zip': '06480', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Kingsland', 'State': 'GA', 'Zip': '31548', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Tabor', 'State': 'IA', 'Zip': '51653', 'District': 'Fremont County', 'Region': 'Midwest'},
    {'City': 'Burlingame', 'State': 'CA', 'Zip': '94010', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Ken Caryl', 'State': 'CO', 'Zip': '80127', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Durham', 'State': 'CT', 'Zip': '06422', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'St. Marys', 'State': 'GA', 'Zip': '31558', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Randolph', 'State': 'IA', 'Zip': '51649', 'District': 'Fremont County', 'Region': 'Midwest'},
    {'City': 'Millbrae', 'State': 'CA', 'Zip': '94030', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Littleton', 'State': 'CO', 'Zip': '80120', 'District': 'Jefferson County', 'Region': 'West'},
    {'City': 'Chester', 'State': 'CT', 'Zip': '06412', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Woodbine', 'State': 'GA', 'Zip': '31569', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Hamburg', 'State': 'IA', 'Zip': '51640', 'District': 'Fremont County', 'Region': 'Midwest'},
    {'City': 'Brisbane', 'State': 'CA', 'Zip': '94005', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Centennial', 'State': 'CO', 'Zip': '80112', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'Ivoryton', 'State': 'CT', 'Zip': '06442', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Brunswick', 'State': 'GA', 'Zip': '31520', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Farragut', 'State': 'IA', 'Zip': '51639', 'District': 'Fremont County', 'Region': 'Midwest'},
    {'City': 'Daly City', 'State': 'CA', 'Zip': '94014', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Highlands Ranch', 'State': 'CO', 'Zip': '80129', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Moodus', 'State': 'CT', 'Zip': '06469', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Jekyll Island', 'State': 'GA', 'Zip': '31527', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Imogene', 'State': 'IA', 'Zip': '51645', 'District': 'Fremont County', 'Region': 'Midwest'},
    {'City': 'South San Francisco', 'State': 'CA', 'Zip': '94080', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Castle Pines', 'State': 'CO', 'Zip': '80108', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Cobalt', 'State': 'CT', 'Zip': '06414', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Sea Island', 'State': 'GA', 'Zip': '31561', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Percival', 'State': 'IA', 'Zip': '51648', 'District': 'Fremont County', 'Region': 'Midwest'},
    {'City': 'Pacifica', 'State': 'CA', 'Zip': '94044', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Castle Rock', 'State': 'CO', 'Zip': '80104', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'East Berlin', 'State': 'CT', 'Zip': '06023', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Little St. Simons', 'State': 'GA', 'Zip': '31522', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Thurman', 'State': 'IA', 'Zip': '51654', 'District': 'Fremont County', 'Region': 'Midwest'},
    {'City': 'Half Moon Bay', 'State': 'CA', 'Zip': '94019', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Parker', 'State': 'CO', 'Zip': '80134', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Middlefield', 'State': 'CT', 'Zip': '06455', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'St. Simons Island', 'State': 'GA', 'Zip': '31522', 'District': 'Southeast Georgia', 'Region': 'Southeast'},
    {'City': 'Riverton', 'State': 'IA', 'Zip': '51650', 'District': 'Fremont County', 'Region': 'Midwest'},
    {'City': 'El Granada', 'State': 'CA', 'Zip': '94018', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Lone Tree', 'State': 'CO', 'Zip': '80124', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Rockfall', 'State': 'CT', 'Zip': '06481', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Butler', 'State': 'GA', 'Zip': '31006', 'District': 'Taylor County', 'Region': 'Southeast'},
    {'City': 'Essex', 'State': 'IA', 'Zip': '51638', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'Montara', 'State': 'CA', 'Zip': '94037', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Roxborough', 'State': 'CO', 'Zip': '80125', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Higganum', 'State': 'CT', 'Zip': '06441', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Ideal', 'State': 'GA', 'Zip': '31041', 'District': 'Macon County', 'Region': 'Southeast'},
    {'City': 'Blanchard', 'State': 'IA', 'Zip': '51630', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'Moss Beach', 'State': 'CA', 'Zip': '94038', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'The Pinery', 'State': 'CO', 'Zip': '80126', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Middletown', 'State': 'CT', 'Zip': '06459', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Oglethorpe', 'State': 'GA', 'Zip': '31068', 'District': 'Macon County', 'Region': 'Southeast'},
    {'City': 'Coin', 'State': 'IA', 'Zip': '51636', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'Princeton', 'State': 'CA', 'Zip': '94080', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Stonegate', 'State': 'CO', 'Zip': '80121', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Centerbrook', 'State': 'CT', 'Zip': '06409', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Marshallville', 'State': 'GA', 'Zip': '31057', 'District': 'Macon County', 'Region': 'Southeast'},
    {'City': 'Yorktown', 'State': 'IA', 'Zip': '51656', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'Moss Beach', 'State': 'CA', 'Zip': '94039', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Heritage Hills', 'State': 'CO', 'Zip': '80124', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Westbrook', 'State': 'CT', 'Zip': '06499', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Montezuma', 'State': 'GA', 'Zip': '31063', 'District': 'Macon County', 'Region': 'Southeast'},
    {'City': 'College Springs', 'State': 'IA', 'Zip': '51637', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'Pescadero', 'State': 'CA', 'Zip': '94060', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Inverness', 'State': 'CO', 'Zip': '80112', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'East Hampton', 'State': 'CT', 'Zip': '06425', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Reynolds', 'State': 'GA', 'Zip': '31076', 'District': 'Taylor County', 'Region': 'Southeast'},
    {'City': 'Braddyville', 'State': 'IA', 'Zip': '51631', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'La Honda', 'State': 'CA', 'Zip': '94020', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Greenwood Village', 'State': 'CO', 'Zip': '80111', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'Hadlyme', 'State': 'CT', 'Zip': '06439', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Rupert', 'State': 'GA', 'Zip': '31081', 'District': 'Taylor County', 'Region': 'Southeast'},
    {'City': 'Shambaugh', 'State': 'IA', 'Zip': '51651', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'Loma Mar', 'State': 'CA', 'Zip': '94021', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Cherry Hills Village', 'State': 'CO', 'Zip': '80113', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'Lyme', 'State': 'CT', 'Zip': '06371', 'District': 'New London County', 'Region': 'Northeast'},
    {'City': 'Mauk', 'State': 'GA', 'Zip': '31058', 'District': 'Taylor County', 'Region': 'Southeast'},
    {'City': 'Northboro', 'State': 'IA', 'Zip': '51647', 'District': 'Page County', 'Region': 'Midwest'},
    {'City': 'Woodside', 'State': 'CA', 'Zip': '94062', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Glendale', 'State': 'CO', 'Zip': '80246', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'Hamburg', 'State': 'CT', 'Zip': '06040', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Junction City', 'State': 'GA', 'Zip': '31812', 'District': 'Talbot County', 'Region': 'Southeast'},
    {'City': 'Hopkins', 'State': 'IA', 'Zip': '51464', 'District': 'Nodaway County', 'Region': 'Midwest'},
    {'City': 'Atherton', 'State': 'CA', 'Zip': '94027', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Bow Mar', 'State': 'CO', 'Zip': '80123', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'Haddam Neck', 'State': 'CT', 'Zip': '06424', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Talbotton', 'State': 'GA', 'Zip': '31827', 'District': 'Talbot County', 'Region': 'Southeast'},
    {'City': 'Gravity', 'State': 'IA', 'Zip': '50848', 'District': 'Taylor County', 'Region': 'Midwest'},
    {'City': 'Portola Valley', 'State': 'CA', 'Zip': '94028', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Columbine Valley', 'State': 'CO', 'Zip': '80123', 'District': 'Arapahoe County', 'Region': 'West'},
    {'City': 'Chester', 'State': 'CT', 'Zip': '06411', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Woodland', 'State': 'GA', 'Zip': '31836', 'District': 'Talbot County', 'Region': 'Southeast'},
    {'City': 'Sharpsburg', 'State': 'IA', 'Zip': '50862', 'District': 'Taylor County', 'Region': 'Midwest'},
    {'City': 'Menlo Park', 'State': 'CA', 'Zip': '94025', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Deer Trail', 'State': 'CO', 'Zip': '80105', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Deep River', 'State': 'CT', 'Zip': '06421', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Geneva', 'State': 'GA', 'Zip': '31810', 'District': 'Talbot County', 'Region': 'Southeast'},
    {'City': 'Clearfield', 'State': 'IA', 'Zip': '50840', 'District': 'Taylor County', 'Region': 'Midwest'},
    {'City': 'East Palo Alto', 'State': 'CA', 'Zip': '94303', 'District': 'San Mateo County', 'Region': 'West'},
    {'City': 'Franktown', 'State': 'CO', 'Zip': '80116', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Durham', 'State': 'CT', 'Zip': '06421', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Waverly Hall', 'State': 'GA', 'Zip': '31831', 'District': 'Harris County', 'Region': 'Southeast'},
    {'City': 'Lenox', 'State': 'IA', 'Zip': '50851', 'District': 'Taylor County', 'Region': 'Midwest'},
    {'City': 'Stanford', 'State': 'CA', 'Zip': '94305', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Sedalia', 'State': 'CO', 'Zip': '80135', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'Centerbrook', 'State': 'CT', 'Zip': '06404', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Pine Mountain', 'State': 'GA', 'Zip': '31822', 'District': 'Harris County', 'Region': 'Southeast'},
    {'City': 'New Market', 'State': 'IA', 'Zip': '51646', 'District': 'Taylor County', 'Region': 'Midwest'},
    {'City': 'Los Altos Hills', 'State': 'CA', 'Zip': '94022', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Larkspur', 'State': 'CO', 'Zip': '80118', 'District': 'Douglas County', 'Region': 'West'},
    {'City': 'East Hampton', 'State': 'CT', 'Zip': '06424', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Hamilton', 'State': 'GA', 'Zip': '31811', 'District': 'Harris County', 'Region': 'Southeast'},
    {'City': 'Bedford', 'State': 'IA', 'Zip': '50833', 'District': 'Taylor County', 'Region': 'Midwest'},
    {'City': 'Saratoga', 'State': 'CA', 'Zip': '95070', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Palmer Lake', 'State': 'CO', 'Zip': '80133', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Ivoryton', 'State': 'CT', 'Zip': '06443', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Ellerslie', 'State': 'GA', 'Zip': '31807', 'District': 'Harris County', 'Region': 'Southeast'},
    {'City': 'Blockton', 'State': 'IA', 'Zip': '50836', 'District': 'Taylor County', 'Region': 'Midwest'},
    {'City': 'Monte Sereno', 'State': 'CA', 'Zip': '95030', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Monument', 'State': 'CO', 'Zip': '80132', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Westbrook', 'State': 'CT', 'Zip': '06498', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Cataula', 'State': 'GA', 'Zip': '31804', 'District': 'Harris County', 'Region': 'Southeast'},
    {'City': 'Conway', 'State': 'IA', 'Zip': '50839', 'District': 'Taylor County', 'Region': 'Midwest'},
    {'City': 'Campbell', 'State': 'CA', 'Zip': '95008', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Black Forest', 'State': 'CO', 'Zip': '80908', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Portland', 'State': 'CT', 'Zip': '06483', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Fortson', 'State': 'GA', 'Zip': '31808', 'District': 'Harris County', 'Region': 'Southeast'},
    {'City': 'Diagonal', 'State': 'IA', 'Zip': '50845', 'District': 'Ringgold County', 'Region': 'Midwest'},
    {'City': 'Los Gatos', 'State': 'CA', 'Zip': '95030', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Colorado Springs', 'State': 'CO', 'Zip': '80901', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Chester', 'State': 'CT', 'Zip': '06410', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Midland', 'State': 'GA', 'Zip': '31820', 'District': 'Muscogee County', 'Region': 'Southeast'},
    {'City': 'Mount Ayr', 'State': 'IA', 'Zip': '50854', 'District': 'Ringgold County', 'Region': 'Midwest'},
    {'City': 'San Jose', 'State': 'CA', 'Zip': '95101', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Fountain', 'State': 'CO', 'Zip': '80817', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Deep River', 'State': 'CT', 'Zip': '06419', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Manchester', 'State': 'GA', 'Zip': '31816', 'District': 'Meriwether County', 'Region': 'Southeast'},
    {'City': 'Tingley', 'State': 'IA', 'Zip': '50863', 'District': 'Ringgold County', 'Region': 'Midwest'},
    {'City': 'Santa Clara', 'State': 'CA', 'Zip': '95050', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Security', 'State': 'CO', 'Zip': '80911', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Durham', 'State': 'CT', 'Zip': '06418', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Greenville', 'State': 'GA', 'Zip': '30222', 'District': 'Meriwether County', 'Region': 'Southeast'},
    {'City': 'Kellerton', 'State': 'IA', 'Zip': '50849', 'District': 'Ringgold County', 'Region': 'Midwest'},
    {'City': 'Milpitas', 'State': 'CA', 'Zip': '95036', 'District': 'Santa Clara County', 'Region': 'West'},
    {'City': 'Widefield', 'State': 'CO', 'Zip': '80911', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'East Haddam', 'State': 'CT', 'Zip': '06421', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Gay', 'State': 'GA', 'Zip': '30218', 'District': 'Meriwether County', 'Region': 'Southeast'},
    {'City': 'Redding', 'State': 'IA', 'Zip': '50860', 'District': 'Ringgold County', 'Region': 'Midwest'},
    {'City': 'Fremont', 'State': 'CA', 'Zip': '94539', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Stratmoor Hills', 'State': 'CO', 'Zip': '80906', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Essex', 'State': 'CT', 'Zip': '06427', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Luthersville', 'State': 'GA', 'Zip': '30251', 'District': 'Meriwether County', 'Region': 'Southeast'},
    {'City': 'Ellston', 'State': 'IA', 'Zip': '50846', 'District': 'Ringgold County', 'Region': 'Midwest'},
    {'City': 'Newark', 'State': 'CA', 'Zip': '94561', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Cimarron Hills', 'State': 'CO', 'Zip': '80915', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Haddam', 'State': 'CT', 'Zip': '06440', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Woodbury', 'State': 'GA', 'Zip': '30293', 'District': 'Meriwether County', 'Region': 'Southeast'},
    {'City': 'Maloy', 'State': 'IA', 'Zip': '50853', 'District': 'Ringgold County', 'Region': 'Midwest'},
    {'City': 'Union City', 'State': 'CA', 'Zip': '94588', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Gleneagle', 'State': 'CO', 'Zip': '80921', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Higganum', 'State': 'CT', 'Zip': '06440', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Warm Springs', 'State': 'GA', 'Zip': '31830', 'District': 'Meriwether County', 'Region': 'Southeast'},
    {'City': 'Benton', 'State': 'IA', 'Zip': '50835', 'District': 'Ringgold County', 'Region': 'Midwest'},
    {'City': 'Hayward', 'State': 'CA', 'Zip': '94542', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Air Force Academy', 'State': 'CO', 'Zip': '80840', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Killingworth', 'State': 'CT', 'Zip': '06420', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Lone Oak', 'State': 'GA', 'Zip': '31204', 'District': 'Meriwether County', 'Region': 'Southeast'},
    {'City': 'Delphos', 'State': 'IA', 'Zip': '50847', 'District': 'Ringgold County', 'Region': 'Midwest'},
    {'City': 'San Leandro', 'State': 'CA', 'Zip': '94577', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Manitou Springs', 'State': 'CO', 'Zip': '80829', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Lyme', 'State': 'CT', 'Zip': '06371', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Hogansville', 'State': 'GA', 'Zip': '30230', 'District': 'Troup County', 'Region': 'Southeast'},
    {'City': 'Arispe', 'State': 'IA', 'Zip': '50831', 'District': 'Union County', 'Region': 'Midwest'},
    {'City': 'Castro Valley', 'State': 'CA', 'Zip': '94546', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Cascade', 'State': 'CO', 'Zip': '80809', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Old Lyme', 'State': 'CT', 'Zip': '06371', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'LaGrange', 'State': 'GA', 'Zip': '30241', 'District': 'Troup County', 'Region': 'Southeast'},
    {'City': 'Afton', 'State': 'IA', 'Zip': '50830', 'District': 'Union County', 'Region': 'Midwest'},
    {'City': 'Dublin', 'State': 'CA', 'Zip': '94568', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Chipita Park', 'State': 'CO', 'Zip': '80809', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Old Saybrook', 'State': 'CT', 'Zip': '06476', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'West Point', 'State': 'GA', 'Zip': '31833', 'District': 'Troup County', 'Region': 'Southeast'},
    {'City': 'Thayer', 'State': 'IA', 'Zip': '50864', 'District': 'Union County', 'Region': 'Midwest'},
    {'City': 'Pleasanton', 'State': 'CA', 'Zip': '94566', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Green Mountain Falls', 'State': 'CO', 'Zip': '80819', 'District': 'El Paso County', 'Region': 'West'},
    {'City': 'Portland', 'State': 'CT', 'Zip': '06481', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Pine Mountain', 'State': 'GA', 'Zip': '31823', 'District': 'Troup County', 'Region': 'Southeast'},
    {'City': 'Shannon City', 'State': 'IA', 'Zip': '50861', 'District': 'Union County', 'Region': 'Midwest'},
    {'City': 'Livermore', 'State': 'CA', 'Zip': '94550', 'District': 'Alameda County', 'Region': 'West'},
    {'City': 'Woodland Park', 'State': 'CO', 'Zip': '80863', 'District': 'Teller County', 'Region': 'West'},
    {'City': 'Rockfall', 'State': 'CT', 'Zip': '06481', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Lanett', 'State': 'AL', 'Zip': '36863', 'District': 'Chambers County', 'Region': 'Southeast'},
    {'City': 'Lorimor', 'State': 'IA', 'Zip': '50149', 'District': 'Union County', 'Region': 'Midwest'},
    {'City': 'Danville', 'State': 'CA', 'Zip': '94526', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Victor', 'State': 'CO', 'Zip': '80860', 'District': 'Teller County', 'Region': 'West'},
    {'City': 'Westbrook', 'State': 'CT', 'Zip': '06497', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Valley', 'State': 'AL', 'Zip': '36854', 'District': 'Chambers County', 'Region': 'Southeast'},
    {'City': 'Murray', 'State': 'IA', 'Zip': '50174', 'District': 'Clarke County', 'Region': 'Midwest'},
    {'City': 'San Ramon', 'State': 'CA', 'Zip': '94582', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Cripple Creek', 'State': 'CO', 'Zip': '80813', 'District': 'Teller County', 'Region': 'West'},
    {'City': 'East Hampton', 'State': 'CT', 'Zip': '06423', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Shawmut', 'State': 'AL', 'Zip': '36876', 'District': 'Chambers County', 'Region': 'Southeast'},
    {'City': 'Osceola', 'State': 'IA', 'Zip': '50213', 'District': 'Clarke County', 'Region': 'Midwest'},
    {'City': 'Walnut Creek', 'State': 'CA', 'Zip': '94595', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Divide', 'State': 'CO', 'Zip': '80814', 'District': 'Teller County', 'Region': 'West'},
    {'City': 'Deep River', 'State': 'CT', 'Zip': '06420', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'LaFayette', 'State': 'AL', 'Zip': '36862', 'District': 'Chambers County', 'Region': 'Southeast'},
    {'City': 'Woodburn', 'State': 'IA', 'Zip': '50275', 'District': 'Clarke County', 'Region': 'Midwest'},
    {'City': 'Lafayette', 'State': 'CA', 'Zip': '94549', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Florissant', 'State': 'CO', 'Zip': '80816', 'District': 'Teller County', 'Region': 'West'},
    {'City': 'Durham', 'State': 'CT', 'Zip': '06420', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Cusseta', 'State': 'AL', 'Zip': '36852', 'District': 'Chambers County', 'Region': 'Midwest'},
    {'City': 'Truro', 'State': 'IA', 'Zip': '50257', 'District': 'Madison County', 'Region': 'Midwest'},
    {'City': 'Orinda', 'State': 'CA', 'Zip': '94563', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Lake George', 'State': 'CO', 'Zip': '80827', 'District': 'Park County', 'Region': 'West'},
    {'City': 'Centerbrook', 'State': 'CT', 'Zip': '06406', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Dadeville', 'State': 'AL', 'Zip': '36853', 'District': 'Tallapoosa County', 'Region': 'Southeast'},
    {'City': 'Winterset', 'State': 'IA', 'Zip': '50273', 'District': 'Madison County', 'Region': 'Midwest'},
    {'City': 'Moraga', 'State': 'CA', 'Zip': '94556', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Fairplay', 'State': 'CO', 'Zip': '80440', 'District': 'Park County', 'Region': 'West'},
    {'City': 'Essex', 'State': 'CT', 'Zip': '06428', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Alexander City', 'State': 'AL', 'Zip': '35010', 'District': 'Tallapoosa County', 'Region': 'Southeast'},
    {'City': 'Peru', 'State': 'IA', 'Zip': '50222', 'District': 'Madison County', 'Region': 'Midwest'},
    {'City': 'Martinez', 'State': 'CA', 'Zip': '94553', 'District': 'Contra Costa County', 'Region': 'West'},
    {'City': 'Alma', 'State': 'CO', 'Zip': '80420', 'District': 'Park County', 'Region': 'West'},
    {'City': 'Haddam', 'State': 'CT', 'Zip': '06441', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Daviston', 'State': 'AL', 'Zip': '36256', 'District': 'Tallapoosa County', 'Region': 'Southeast'},
    {'City': 'Macksburg', 'State': 'IA', 'Zip': '50155', 'District': 'Madison County', 'Region': 'Midwest'},
    {'City': 'Benicia', 'State': 'CA', 'Zip': '94510', 'District': 'Solano County', 'Region': 'West'},
    {'City': 'Breckenridge', 'State': 'CO', 'Zip': '80424', 'District': 'Summit County', 'Region': 'West'},
    {'City': 'Higganum', 'State': 'CT', 'Zip': '06441', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Equality', 'State': 'AL', 'Zip': '36026', 'District': 'Elmore County', 'Region': 'Southeast'},
    {'City': 'Bevington', 'State': 'IA', 'Zip': '50033', 'District': 'Madison County', 'Region': 'Midwest'},
    {'City': 'Vallejo', 'State': 'CA', 'Zip': '94591', 'District': 'Solano County', 'Region': 'West'},
    {'City': 'Frisco', 'State': 'CO', 'Zip': '80443', 'District': 'Summit County', 'Region': 'West'},
    {'City': 'Killingworth', 'State': 'CT', 'Zip': '06421', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Wetumpka', 'State': 'AL', 'Zip': '36092', 'District': 'Elmore County', 'Region': 'Southeast'},
    {'City': 'Cumming', 'State': 'IA', 'Zip': '50061', 'District': 'Warren County', 'Region': 'Midwest'},
    {'City': 'Fairfield', 'State': 'CA', 'Zip': '94534', 'District': 'Solano County', 'Region': 'West'},
    {'City': 'Keystone', 'State': 'CO', 'Zip': '80435', 'District': 'Summit County', 'Region': 'West'},
    {'City': 'Lyme', 'State': 'CT', 'Zip': '06370', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Millbrook', 'State': 'AL', 'Zip': '36054', 'District': 'Elmore County', 'Region': 'Southeast'},
    {'City': 'Hartford', 'State': 'IA', 'Zip': '50118', 'District': 'Warren County', 'Region': 'Midwest'},
    {'City': 'Suisun City', 'State': 'CA', 'Zip': '94585', 'District': 'Solano County', 'Region': 'West'},
    {'City': 'Silverthorne', 'State': 'CO', 'Zip': '80498', 'District': 'Summit County', 'Region': 'West'},
    {'City': 'Old Lyme', 'State': 'CT', 'Zip': '06370', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Coosada', 'State': 'AL', 'Zip': '36020', 'District': 'Elmore County', 'Region': 'Southeast'},
    {'City': 'Indianola', 'State': 'IA', 'Zip': '50126', 'District': 'Warren County', 'Region': 'Midwest'},
    {'City': 'Dixon', 'State': 'CA', 'Zip': '95620', 'District': 'Solano County', 'Region': 'West'},
    {'City': 'Dillon', 'State': 'CO', 'Zip': '80424', 'District': 'Summit County', 'Region': 'West'},
    {'City': 'Old Saybrook', 'State': 'CT', 'Zip': '06477', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Deatsville', 'State': 'AL', 'Zip': '36022', 'District': 'Elmore County', 'Region': 'Southeast'},
    {'City': 'Milo', 'State': 'IA', 'Zip': '50166', 'District': 'Warren County', 'Region': 'Midwest'},
    {'City': 'Rio Vista', 'State': 'CA', 'Zip': '94571', 'District': 'Solano County', 'Region': 'West'},
    {'City': 'Copper Mountain', 'State': 'CO', 'Zip': '80443', 'District': 'Summit County', 'Region': 'West'},
    {'City': 'Portland', 'State': 'CT', 'Zip': '06482', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Marbury', 'State': 'AL', 'Zip': '36051', 'District': 'Autauga County', 'Region': 'Southeast'},
    {'City': 'Sandyville', 'State': 'IA', 'Zip': '50252', 'District': 'Warren County', 'Region': 'Midwest'},
    {'City': 'Vacaville', 'State': 'CA', 'Zip': '95687', 'District': 'Solano County', 'Region': 'West'},
    {'City': 'Vail', 'State': 'CO', 'Zip': '81657', 'District': 'Eagle County', 'Region': 'West'},
    {'City': 'Rockfall', 'State': 'CT', 'Zip': '06482', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Prattville', 'State': 'AL', 'Zip': '36066', 'District': 'Autauga County', 'Region': 'Southeast'},
    {'City': 'Ackworth', 'State': 'IA', 'Zip': '50001', 'District': 'Warren County', 'Region': 'Midwest'},
    {'City': 'American Canyon', 'State': 'CA', 'Zip': '94503', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Avon', 'State': 'CO', 'Zip': '81620', 'District': 'Eagle County', 'Region': 'West'},
    {'City': 'Westbrook', 'State': 'CT', 'Zip': '06496', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Autaugaville', 'State': 'AL', 'Zip': '36003', 'District': 'Autauga County', 'Region': 'Southeast'},
    {'City': 'Carlisle', 'State': 'IA', 'Zip': '50047', 'District': 'Warren County', 'Region': 'Midwest'},
    {'City': 'Calistoga', 'State': 'CA', 'Zip': '94515', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Beaver Creek', 'State': 'CO', 'Zip': '81620', 'District': 'Eagle County', 'Region': 'West'},
    {'City': 'East Hampton', 'State': 'CT', 'Zip': '06422', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Billingsley', 'State': 'AL', 'Zip': '36006', 'District': 'Autauga County', 'Region': 'Southeast'},
    {'City': 'Norwalk', 'State': 'IA', 'Zip': '50211', 'District': 'Warren County', 'Region': 'Midwest'},
    {'City': 'St. Helena', 'State': 'CA', 'Zip': '94574', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Edwards', 'State': 'CO', 'Zip': '81632', 'District': 'Eagle County', 'Region': 'West'},
    {'City': 'Deep River', 'State': 'CT', 'Zip': '06421', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Jones', 'State': 'AL', 'Zip': '36749', 'District': 'Autauga County', 'Region': 'Southeast'},
    {'City': 'Swan', 'State': 'IA', 'Zip': '50252', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Yountville', 'State': 'CA', 'Zip': '94599', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Eagle', 'State': 'CO', 'Zip': '81631', 'District': 'Eagle County', 'Region': 'West'},
    {'City': 'Durham', 'State': 'CT', 'Zip': '06421', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Vida', 'State': 'AL', 'Zip': '36083', 'District': 'Autauga County', 'Region': 'Southeast'},
    {'City': 'Knoxville', 'State': 'IA', 'Zip': '50138', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Angwin', 'State': 'CA', 'Zip': '94508', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Gypsum', 'State': 'CO', 'Zip': '81637', 'District': 'Eagle County', 'Region': 'West'},
    {'City': 'Centerbrook', 'State': 'CT', 'Zip': '06407', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Pine Level', 'State': 'AL', 'Zip': '36065', 'District': 'Montgomery County', 'Region': 'Southeast'},
    {'City': 'Pleasantville', 'State': 'IA', 'Zip': '50225', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Deer Park', 'State': 'CA', 'Zip': '94576', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Minturn', 'State': 'CO', 'Zip': '81645', 'District': 'Eagle County', 'Region': 'West'},
    {'City': 'Essex', 'State': 'CT', 'Zip': '06429', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Hope Hull', 'State': 'AL', 'Zip': '36043', 'District': 'Montgomery County', 'Region': 'Southeast'},
    {'City': 'Pella', 'State': 'IA', 'Zip': '50219', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Pope Valley', 'State': 'CA', 'Zip': '94567', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Red Cliff', 'State': 'CO', 'Zip': '81649', 'District': 'Eagle County', 'Region': 'West'},
    {'City': 'Haddam', 'State': 'CT', 'Zip': '06442', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Pike Road', 'State': 'AL', 'Zip': '36064', 'District': 'Montgomery County', 'Region': 'Southeast'},
    {'City': 'Bussey', 'State': 'IA', 'Zip': '50044', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Rutherford', 'State': 'CA', 'Zip': '94573', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Glenwood Springs', 'State': 'CO', 'Zip': '81601', 'District': 'Garfield County', 'Region': 'West'},
    {'City': 'Higganum', 'State': 'CT', 'Zip': '06442', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Mathews', 'State': 'AL', 'Zip': '36052', 'District': 'Montgomery County', 'Region': 'Southeast'},
    {'City': 'Tracy', 'State': 'IA', 'Zip': '50256', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Oakville', 'State': 'CA', 'Zip': '94562', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'Carbondale', 'State': 'CO', 'Zip': '81623', 'District': 'Garfield County', 'Region': 'West'},
    {'City': 'Killingworth', 'State': 'CT', 'Zip': '06422', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Cecil', 'State': 'AL', 'Zip': '36013', 'District': 'Montgomery County', 'Region': 'Southeast'},
    {'City': 'Columbia', 'State': 'IA', 'Zip': '50057', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Napa', 'State': 'CA', 'Zip': '94559', 'District': 'Napa County', 'Region': 'West'},
    {'City': 'New Castle', 'State': 'CO', 'Zip': '81647', 'District': 'Garfield County', 'Region': 'West'},
    {'City': 'Lyme', 'State': 'CT', 'Zip': '06371', 'District': 'New London County', 'Region': 'Northeast'},
    {'City': 'Shorter', 'State': 'AL', 'Zip': '36075', 'District': 'Macon County', 'Region': 'Southeast'},
    {'City': 'Hamilton', 'State': 'IA', 'Zip': '50116', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Browns Valley', 'State': 'CA', 'Zip': '95918', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'Silt', 'State': 'CO', 'Zip': '81652', 'District': 'Garfield County', 'Region': 'West'},
    {'City': 'Old Lyme', 'State': 'CT', 'Zip': '06371', 'District': 'New London County', 'Region': 'Northeast'},
    {'City': 'Tuskegee', 'State': 'AL', 'Zip': '36083', 'District': 'Macon County', 'Region': 'Southeast'},
    {'City': 'Harvey', 'State': 'IA', 'Zip': '50119', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Marysville', 'State': 'CA', 'Zip': '95901', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'Rifle', 'State': 'CO', 'Zip': '81650', 'District': 'Garfield County', 'Region': 'West'},
    {'City': 'Old Saybrook', 'State': 'CT', 'Zip': '06478', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Tuskegee Institute', 'State': 'AL', 'Zip': '36088', 'District': 'Macon County', 'Region': 'Southeast'},
    {'City': 'Otley', 'State': 'IA', 'Zip': '50214', 'District': 'Marion County', 'Region': 'Midwest'},
    {'City': 'Wheatland', 'State': 'CA', 'Zip': '95692', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'Parachute', 'State': 'CO', 'Zip': '81635', 'District': 'Garfield County', 'Region': 'West'},
    {'City': 'Portland', 'State': 'CT', 'Zip': '06484', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Notasulga', 'State': 'AL', 'Zip': '36866', 'District': 'Macon County', 'Region': 'Southeast'},
    {'City': 'Swan', 'State': 'IA', 'Zip': '50254', 'District': 'Mahaska County', 'Region': 'Midwest'},
    {'City': 'Linda', 'State': 'CA', 'Zip': '95901', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'Battlement Mesa', 'State': 'CO', 'Zip': '81635', 'District': 'Garfield County', 'Region': 'West'},
    {'City': 'Rockfall', 'State': 'CT', 'Zip': '06484', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Franklin', 'State': 'AL', 'Zip': '36444', 'District': 'Macon County', 'Region': 'Southeast'},
    {'City': 'Leighton', 'State': 'IA', 'Zip': '50143', 'District': 'Mahaska County', 'Region': 'Midwest'},
    {'City': 'Olivehurst', 'State': 'CA', 'Zip': '95961', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'De Beque', 'State': 'CO', 'Zip': '81630', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'Westbrook', 'State': 'CT', 'Zip': '06495', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Auburn', 'State': 'AL', 'Zip': '36830', 'District': 'Lee County', 'Region': 'Southeast'},
    {'City': 'Oskaloosa', 'State': 'IA', 'Zip': '52577', 'District': 'Mahaska County', 'Region': 'Midwest'},
    {'City': 'Smartsville', 'State': 'CA', 'Zip': '95977', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'Palisade', 'State': 'CO', 'Zip': '81526', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'East Hampton', 'State': 'CT', 'Zip': '06421', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Opelika', 'State': 'AL', 'Zip': '36801', 'District': 'Lee County', 'Region': 'Southeast'},
    {'City': 'Rose Hill', 'State': 'IA', 'Zip': '52586', 'District': 'Mahaska County', 'Region': 'Midwest'},
    {'City': 'Challenge', 'State': 'CA', 'Zip': '95925', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'Clifton', 'State': 'CO', 'Zip': '81520', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'Deep River', 'State': 'CT', 'Zip': '06422', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Smiths Station', 'State': 'AL', 'Zip': '36877', 'District': 'Lee County', 'Region': 'Southeast'},
    {'City': 'Fremont', 'State': 'IA', 'Zip': '52561', 'District': 'Mahaska County', 'Region': 'Midwest'},
    {'City': 'Camptonville', 'State': 'CA', 'Zip': '95922', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'Collbran', 'State': 'CO', 'Zip': '81624', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'Durham', 'State': 'CT', 'Zip': '06422', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Salem', 'State': 'AL', 'Zip': '36874', 'District': 'Lee County', 'Region': 'Southeast'},
    {'City': 'University Park', 'State': 'IA', 'Zip': '52595', 'District': 'Mahaska County', 'Region': 'Midwest'},
    {'City': 'Dobbins', 'State': 'CA', 'Zip': '95935', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'Mesa', 'State': 'CO', 'Zip': '81643', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'Centerbrook', 'State': 'CT', 'Zip': '06408', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Phenix City', 'State': 'AL', 'Zip': '36867', 'District': 'Russell County', 'Region': 'Southeast'},
    {'City': 'New Sharon', 'State': 'IA', 'Zip': '50207', 'District': 'Mahaska County', 'Region': 'Midwest'},
    {'City': 'Forbestown', 'State': 'CA', 'Zip': '95941', 'District': 'Yuba County', 'Region': 'West'},
    {'City': 'Molina', 'State': 'CO', 'Zip': '81646', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'Essex', 'State': 'CT', 'Zip': '06430', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Ladonia', 'State': 'AL', 'Zip': '36854', 'District': 'Russell County', 'Region': 'Southeast'},
    {'City': 'Barnes City', 'State': 'IA', 'Zip': '50027', 'District': 'Mahaska County', 'Region': 'Midwest'},
    {'City': 'French Camp', 'State': 'CA', 'Zip': '95231', 'District': 'San Joaquin County', 'Region': 'West'},
    {'City': 'Gateway', 'State': 'CO', 'Zip': '81522', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'Haddam', 'State': 'CT', 'Zip': '06443', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Seale', 'State': 'AL', 'Zip': '36875', 'District': 'Russell County', 'Region': 'Southeast'},
    {'City': 'Eddyville', 'State': 'IA', 'Zip': '52553', 'District': 'Mahaska County', 'Region': 'Midwest'},
    {'City': 'Lathrop', 'State': 'CA', 'Zip': '95330', 'District': 'San Joaquin County', 'Region': 'West'},
    {'City': 'Loma', 'State': 'CO', 'Zip': '81524', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'Higganum', 'State': 'CT', 'Zip': '06443', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Hurtsboro', 'State': 'AL', 'Zip': '36860', 'District': 'Russell County', 'Region': 'Southeast'},
    {'City': 'What Cheer', 'State': 'IA', 'Zip': '50268', 'District': 'Keokuk County', 'Region': 'Midwest'},
    {'City': 'Manteca', 'State': 'CA', 'Zip': '95336', 'District': 'San Joaquin County', 'Region': 'West'},
    {'City': 'Mack', 'State': 'CO', 'Zip': '81525', 'District': 'Mesa County', 'Region': 'West'},
    {'City': 'Killingworth', 'State': 'CT', 'Zip': '06423', 'District': 'Middlesex County', 'Region': 'Northeast'},
    {'City': 'Cottonton', 'State': 'AL', 'Zip': '36851', 'District': 'Russell County', 'Region': 'Southeast'},
    {'City': 'Sigourney', 'State': 'IA', 'Zip': '52591', 'District': 'Keokuk County', 'Region': 'Midwest'},
    {'City': 'Tracy', 'State': 'CA', 'Zip': '95376', 'District': 'San Joaquin County', 'Region': 'West'},
    {'City': 'Westwater', 'State': 'CO', 'Zip': '81527', 'District': 'Mesa County', 'Region': 'West'},
]
