"""
Product Brands source data for supercenter retail profile.

This data is 100% synthetic and safe for demo/POC purposes.
Each brand is uniquely assigned to a parent company within its category.
Brand names are category-appropriate (e.g., food brands sound like food, clothing like fashion).
"""

PRODUCT_BRANDS = [
    {'Brand': 'Pure Select', 'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Brand': 'Wholesome Premium', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Green Best', 'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Brand': 'Pure Market', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Field Choice', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Meadow Farms', 'Company': 'FreshMart Foods', 'Category': 'Food'},
    {'Brand': 'Natural Select', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Organic Premium', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Green Valley', 'Company': 'Harvest Time Foods', 'Category': 'Food'},
    {'Brand': 'Country Select', 'Company': 'HealthPrime Foods', 'Category': 'Food'},
    {'Brand': 'Field Premium', 'Company': 'Healthy Choice Foods', 'Category': 'Food'},
    {'Brand': 'Field Farms', 'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Brand': 'Green Grove', 'Company': 'Natura Best Foods', 'Category': 'Food'},
    {'Brand': 'Meadow Gold', 'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Brand': 'Fresh Table', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Harvest Kitchen', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Nature Harvest', 'Company': 'Prime Produce Inc', 'Category': 'Food'},
    {'Brand': 'Wholesome Best', 'Company': 'Pure Essence Ltd', 'Category': 'Food'},
    {'Brand': 'Farm Table', 'Company': 'Pure Taste Industries', 'Category': 'Food'},
    {'Brand': 'Prime Choice', 'Company': 'PureLife', 'Category': 'Food'},
    {'Brand': 'Organic Farms', 'Company': 'Quality Foods Ltd', 'Category': 'Food'},
    {'Brand': 'Pure Harvest', 'Company': 'Sunny Fields Corp', 'Category': 'Food'},
    {'Brand': 'Health Fields', 'Company': 'Vital Nutrition Co', 'Category': 'Food'},
    {'Brand': 'Wholesome Table', 'Company': 'Wholesome Goods Inc', 'Category': 'Food'},
    {'Brand': 'Natural Kitchen', 'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Brand': 'Garden Valley', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Pure Goods', 'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Brand': 'Vita Choice', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Field Gold', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Country Goods', 'Company': 'FreshMart Foods', 'Category': 'Food'},
    {'Brand': 'Farm Kitchen', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Organic Select', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Green Table', 'Company': 'Harvest Time Foods', 'Category': 'Food'},
    {'Brand': 'Sunny Choice', 'Company': 'HealthPrime Foods', 'Category': 'Food'},
    {'Brand': 'Green Pantry', 'Company': 'Healthy Choice Foods', 'Category': 'Food'},
    {'Brand': 'Pure Farms', 'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Brand': 'Wholesome Grove', 'Company': 'Natura Best Foods', 'Category': 'Food'},
    {'Brand': 'Health Best', 'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Brand': 'Health Harvest', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Farm Market', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Wholesome Kitchen', 'Company': 'Prime Produce Inc', 'Category': 'Food'},
    {'Brand': 'Organic Fields', 'Company': 'Pure Essence Ltd', 'Category': 'Food'},
    {'Brand': 'Harvest Valley', 'Company': 'Pure Taste Industries', 'Category': 'Food'},
    {'Brand': 'Garden Farms', 'Company': 'PureLife', 'Category': 'Food'},
    {'Brand': 'Wholesome Goods', 'Company': 'Quality Foods Ltd', 'Category': 'Food'},
    {'Brand': 'Prime Pantry', 'Company': 'Sunny Fields Corp', 'Category': 'Food'},
    {'Brand': 'Natural Premium', 'Company': 'Vital Nutrition Co', 'Category': 'Food'},
    {'Brand': 'Natural Table', 'Company': 'Wholesome Goods Inc', 'Category': 'Food'},
    {'Brand': 'Prime Farms', 'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Brand': 'Wholesome Choice', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Farm Goods', 'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Brand': 'Meadow Goods', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Prime Premium', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Valley Farms', 'Company': 'FreshMart Foods', 'Category': 'Food'},
    {'Brand': 'Garden Best', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Green Kitchen', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Field Valley', 'Company': 'Harvest Time Foods', 'Category': 'Food'},
    {'Brand': 'Health Premium', 'Company': 'HealthPrime Foods', 'Category': 'Food'},
    {'Brand': 'Golden Valley', 'Company': 'Healthy Choice Foods', 'Category': 'Food'},
    {'Brand': 'Valley Choice', 'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Brand': 'Natural Pantry', 'Company': 'Natura Best Foods', 'Category': 'Food'},
    {'Brand': 'Pure Best', 'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Brand': 'Harvest Table', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Nature Fields', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Vita Fields', 'Company': 'Prime Produce Inc', 'Category': 'Food'},
    {'Brand': 'Wholesome Valley', 'Company': 'Pure Essence Ltd', 'Category': 'Food'},
    {'Brand': 'Fresh Market', 'Company': 'Pure Taste Industries', 'Category': 'Food'},
    {'Brand': 'Field Table', 'Company': 'PureLife', 'Category': 'Food'},
    {'Brand': 'Sunny Farms', 'Company': 'Quality Foods Ltd', 'Category': 'Food'},
    {'Brand': 'Harvest Grove', 'Company': 'Sunny Fields Corp', 'Category': 'Food'},
    {'Brand': 'Fresh Kitchen', 'Company': 'Vital Nutrition Co', 'Category': 'Food'},
    {'Brand': 'Pure Pantry', 'Company': 'Wholesome Goods Inc', 'Category': 'Food'},
    {'Brand': 'Sunny Pantry', 'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Brand': 'Grove Fields', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Farm Best', 'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Brand': 'Health Table', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Grove Goods', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Fresh Fields', 'Company': 'FreshMart Foods', 'Category': 'Food'},
    {'Brand': 'Prime Grove', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Fresh Choice', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Health Goods', 'Company': 'Harvest Time Foods', 'Category': 'Food'},
    {'Brand': 'Sunny Premium', 'Company': 'HealthPrime Foods', 'Category': 'Food'},
    {'Brand': 'Meadow Choice', 'Company': 'Healthy Choice Foods', 'Category': 'Food'},
    {'Brand': 'Organic Kitchen', 'Company': 'HealthyLiving', 'Category': 'Food'},
    {'Brand': 'Valley Pantry', 'Company': 'Natura Best Foods', 'Category': 'Food'},
    {'Brand': 'Organic Table', 'Company': 'Natural Harvest Co', 'Category': 'Food'},
    {'Brand': 'Golden Best', 'Company': 'NaturalWay', 'Category': 'Food'},
    {'Brand': 'Harvest Gold', 'Company': 'Organic Vitality Co', 'Category': 'Food'},
    {'Brand': 'Grove Pantry', 'Company': 'Prime Produce Inc', 'Category': 'Food'},
    {'Brand': 'Country Farms', 'Company': 'Pure Essence Ltd', 'Category': 'Food'},
    {'Brand': 'Health Grove', 'Company': 'Pure Taste Industries', 'Category': 'Food'},
    {'Brand': 'Pure Premium', 'Company': 'PureLife', 'Category': 'Food'},
    {'Brand': 'Green Choice', 'Company': 'Quality Foods Ltd', 'Category': 'Food'},
    {'Brand': 'Prime Select', 'Company': 'Sunny Fields Corp', 'Category': 'Food'},
    {'Brand': 'Meadow Valley', 'Company': 'Vital Nutrition Co', 'Category': 'Food'},
    {'Brand': 'Green Fields', 'Company': 'Wholesome Goods Inc', 'Category': 'Food'},
    {'Brand': 'Green Select', 'Company': 'Clean Eating Corp', 'Category': 'Food'},
    {'Brand': 'Organic Goods', 'Company': 'Farm-Fresh Products', 'Category': 'Food'},
    {'Brand': 'Grove Premium', 'Company': 'Fresh Corp', 'Category': 'Food'},
    {'Brand': 'Wholesome Market', 'Company': 'Fresh Farms LLC', 'Category': 'Food'},
    {'Brand': 'Valley Premium', 'Company': 'Fresh Start Co.', 'Category': 'Food'},
    {'Brand': 'Field Best', 'Company': 'FreshMart Foods', 'Category': 'Food'},
    {'Brand': 'Meadow Fields', 'Company': 'Golden Grove Farms', 'Category': 'Food'},
    {'Brand': 'Valley Table', 'Company': 'GreenChoice', 'Category': 'Food'},
    {'Brand': 'Nature Premium', 'Company': 'Harvest Time Foods', 'Category': 'Food'},
    {'Brand': 'Pure Choice', 'Company': 'HealthPrime Foods', 'Category': 'Food'},
    {'Brand': 'Nature Farms', 'Company': 'Healthy Choice Foods', 'Category': 'Food'},
    {'Brand': 'Real Wear', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Core Label', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Prime Style', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Street Apparel', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Threads', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Sport Line', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Modern Line', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Chic Collection', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Denim Apparel', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Classic Co', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Fit Line', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Active Collection', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Chic Style', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Street Label', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Chic Outfitters', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Urban Style', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Pure Outfitters', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Elite Fit', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Flex Collection', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Edge Line', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Metro Clothing', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Street Fit', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Metro Wear', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Metro Co', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Fit Co', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Flex Brand', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Fashion', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Chic Label', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'True Collection', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Denim Line', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Style Line', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Street Look', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Designs', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Street Brand', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Fashion Wear', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Edge Designs', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Bold Fit', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Street Designs', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Active Outfitters', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Classic Style', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Vogue Style', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Core Outfitters', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Elite Apparel', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Sport Clothing', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Runway Line', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Runway Look', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Active Apparel', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Core Look', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Runway Designs', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Fashion Clothing', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Trend Line', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Core Brand', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Fashion Line', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Trend Apparel', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Denim Label', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Prime Co', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Fit Threads', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Pure Clothing', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Active Wear', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Fit Look', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Runway Style', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Active Designs', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Modern Designs', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Trend Fit', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Casual Clothing', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Active Clothing', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Elite Threads', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Fit', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Chic Brand', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Look', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Prime Designs', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Urban Label', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Chic Co', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Core Style', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Denim Co', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Sport Brand', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Chic Fit', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Trend Co', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Vogue Line', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'True Threads', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Modern Label', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Prime Outfitters', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Trend Designs', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Edge Co', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Street Style', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Prime Apparel', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Trend Wear', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Urban Threads', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Pure Fit', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Classic Brand', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Fit Designs', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'True Apparel', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Chic Wear', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Sport Style', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'True Clothing', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Denim Designs', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Street Outfitters', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Casual Look', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Flex Fit', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Street Co', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Street Clothing', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Casual Line', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Core Line', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Casual Fashion', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Chic Clothing', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Flex Look', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Real Fit', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Elite Outfitters', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Classic Fashion', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Classic Clothing', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Flex Wear', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Flex Fashion', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Elite Co', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'True Style', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Metro Outfitters', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Modern Outfitters', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Outfitters', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Elite Line', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Modern Apparel', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Fashion Co', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Active Fashion', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Trend Threads', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Metro Label', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Chic Threads', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Runway Co', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Vogue Apparel', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Casual Brand', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Fashion Apparel', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Vogue Designs', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Sport Apparel', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Urban Designs', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Brand', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Label', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Modern Threads', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Flex Style', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Core Clothing', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Fashion Look', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Fashion Label', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Style Designs', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Label', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Flex Threads', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Metro Brand', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Flex Label', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Clothing', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Classic Look', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Metro Designs', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Urban Co', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Prime Threads', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Fit Collection', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Fit Label', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Edge Fashion', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Vogue Threads', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Pure Line', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Elite Fashion', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Modern Fit', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Urban Wear', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Elite Collection', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Vogue Outfitters', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Pure Style', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Fit Apparel', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Prime Look', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Modern Brand', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Edge Apparel', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Prime Brand', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Urban Clothing', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Sport Fashion', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Flex Line', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'True Designs', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Fit Wear', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Chic Line', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Sport Collection', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Denim Fashion', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Bold Designs', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Bold Apparel', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Edge Collection', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Trend Fashion', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Pure Fashion', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Bold Collection', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Prime Line', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Trend Collection', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Active Brand', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Denim Fit', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'True Fit', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'True Line', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Flex Apparel', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Pure Look', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'True Wear', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Metro Collection', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Fashion', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Flex Designs', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Chic Fashion', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Vogue Clothing', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Urban Apparel', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Core Fashion', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Classic Outfitters', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Fit Clothing', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Denim Look', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Metro Look', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Runway Label', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Denim Outfitters', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Metro Threads', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Modern Collection', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Fashion Threads', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Flex Co', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Urban Brand', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Pure Label', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Street Fashion', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Urban Line', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Urban Look', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Denim Collection', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Fit Brand', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Casual Fit', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Vogue Look', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Sport Look', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Metro Apparel', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Active Look', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'True Outfitters', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Pure Co', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Runway Fashion', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Street Threads', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Chic Apparel', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Core Threads', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Urban Outfitters', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Flex Outfitters', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Edge Style', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Prime Clothing', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Bold Label', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Trend Look', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Real Look', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Active Co', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Pure Collection', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Core Apparel', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Edge Outfitters', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Fashion Fit', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Trend Clothing', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Vogue Brand', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Modern Style', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Elite Brand', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Edge Label', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Fit Fashion', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Casual Collection', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Chic Designs', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Casual Apparel', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Real Collection', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Trend Brand', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Bold Look', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Modern Co', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Brand', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Sport Outfitters', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Collection', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Core Wear', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Active Line', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Sport Designs', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Pure Apparel', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Pure Designs', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Runway Apparel', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Vogue Wear', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Classic Line', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Classic Designs', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Active Fit', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Vogue Collection', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Style Wear', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'True Co', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Fit Style', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Elite Label', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Denim Clothing', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Trend Outfitters', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Denim Style', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Real Outfitters', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Runway Clothing', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Urban Fashion', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Prime Collection', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Edge Threads', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Classic Threads', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Street Collection', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Active Threads', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Bold Outfitters', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Pure Wear', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Sport Wear', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Sport Label', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Bold Brand', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Metro Line', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Bold Co', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Co', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Core Collection', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Casual Threads', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Fashion Outfitters', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Elite Look', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Prime Fit', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Edge Wear', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Runway Threads', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Bold Clothing', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Style', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Clothing', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Elite Designs', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Classic Fit', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Edge Clothing', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Runway Fit', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Runway Outfitters', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Vogue Co', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Prime Label', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Style Threads', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Real Apparel', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Casual Designs', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Casual Label', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Sport Fit', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Street Wear', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Elite Clothing', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Runway Brand', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Edge Look', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Casual Style', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Modern Look', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Urban Fit', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Bold Style', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Pure Threads', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Bold Line', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Core Designs', 'Company': 'CasualWear LLC', 'Category': 'Clothing'},
    {'Brand': 'Prime Wear', 'Company': 'DenimCraft Co', 'Category': 'Clothing'},
    {'Brand': 'Edge Brand', 'Company': 'FastFashion Inc', 'Category': 'Clothing'},
    {'Brand': 'Vogue Fit', 'Company': 'Performance Inc', 'Category': 'Clothing'},
    {'Brand': 'Sport Threads', 'Company': 'SportSwear Inc', 'Category': 'Clothing'},
    {'Brand': 'Active Style', 'Company': 'StyleBrand Co', 'Category': 'Clothing'},
    {'Brand': 'Casual Outfitters', 'Company': 'TrendyClothes Inc', 'Category': 'Clothing'},
    {'Brand': 'Casual Co', 'Company': 'YouthFashion Outfitters', 'Category': 'Clothing'},
    {'Brand': 'Street Line', 'Company': 'ActiveWear AG', 'Category': 'Clothing'},
    {'Brand': 'Pixel Sync', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Digital Tech', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Ultra Elite', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Ultra Works', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Power Works', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Hyper Pro', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Tech Link', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Core Plus', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Power Hub', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Circuit Labs', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Pro Wave', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Circuit Digital', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Neo Pro', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Pixel Digital', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Digital Hub', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Smart Digital', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Hyper Sync', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Core Sync', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Pixel Labs', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Core Elite', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Cyber Hub', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Tech Zone', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Mega Works', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Vector Link', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Core Digital', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Cyber Max', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Pixel Wave', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Smart Hub', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Max Labs', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Hyper Max', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Hyper Works', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Mega Pro', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Byte Systems', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Cyber Wave', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Byte Max', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Neo Zone', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Power Max', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Cyber Plus', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Elite Max', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Mega Sync', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Smart Plus', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Data Link', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Logic Works', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Logic Link', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Logic Systems', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Vector Zone', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Hyper Plus', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Quantum Pro', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Max Works', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Elite Sync', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Digital Zone', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Byte Pro', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Max Link', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Quantum Tech', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Max Pro', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Smart Sync', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Vector Wave', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Pixel Link', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Logic Wave', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Digital Link', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Ultra Zone', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Byte Plus', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Cyber Works', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Hyper Labs', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Smart Wave', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Mega Tech', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Pro Labs', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Quantum Link', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Byte Wave', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Vector Plus', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Max Hub', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Core Works', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Hyper Systems', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Vector Tech', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Circuit Systems', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Pixel Elite', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Elite Labs', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Vector Digital', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Power Zone', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Power Solutions', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Neo Elite', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Pixel Plus', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Vector Labs', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Smart Elite', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Circuit Hub', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Hyper Digital', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Power Systems', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Core Wave', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Neo Tech', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Mega Max', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Data Max', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Pro Plus', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Power Pro', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Max Digital', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Byte Tech', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Hyper Solutions', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Vector Hub', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Power Plus', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Mega Digital', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Vector Works', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Mega Labs', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Core Zone', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Pro Link', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Vector Elite', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Quantum Max', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Circuit Max', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Data Solutions', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Quantum Works', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Byte Hub', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Elite Tech', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Data Digital', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Neo Wave', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Cyber Labs', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Byte Digital', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Cyber Elite', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Smart Works', 'Company': 'NotebookPro Group', 'Category': 'Electronics'},
    {'Brand': 'Mega Elite', 'Company': 'PrinterPro America', 'Category': 'Electronics'},
    {'Brand': 'Quantum Solutions', 'Company': 'TechSolutions Inc', 'Category': 'Electronics'},
    {'Brand': 'Core Pro', 'Company': 'TechWorld Electronics', 'Category': 'Electronics'},
    {'Brand': 'Pro Digital', 'Company': 'ComputerPlus Inc', 'Category': 'Electronics'},
    {'Brand': 'Neo Solutions', 'Company': 'DeviceWorks Inc', 'Category': 'Electronics'},
    {'Brand': 'Tech Hub', 'Company': 'HomeElectronics', 'Category': 'Electronics'},
    {'Brand': 'Care Aid', 'Company': 'HealthFirst Labs', 'Category': 'Health'},
    {'Brand': 'Bio Health', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Health Aid', 'Company': 'VitaLife Corp', 'Category': 'Health'},
    {'Brand': 'Well Health', 'Company': 'WellnessPlus Inc', 'Category': 'Health'},
    {'Brand': 'Health Care', 'Company': 'HealthFirst Labs', 'Category': 'Health'},
    {'Brand': 'Clean Plus', 'Company': 'PharmaCare Corporation', 'Category': 'Health'},
    {'Brand': 'Clean Pro', 'Company': 'VitaLife Corp', 'Category': 'Health'},
    {'Brand': 'Vita Care', 'Company': 'WellnessPlus Inc', 'Category': 'Health'},
    {'Brand': 'Cozy Solutions', 'Company': 'BuildMart Inc', 'Category': 'Home'},
    {'Brand': 'Comfort Solutions', 'Company': 'DomesticGoods LLC', 'Category': 'Home'},
    {'Brand': 'Haven Life', 'Company': 'HomeStyle Corp', 'Category': 'Home'},
    {'Brand': 'Home Comfort', 'Company': 'HouseCraft Co', 'Category': 'Home'},
    {'Brand': 'Office Supply', 'Company': 'BusinessSupply Inc', 'Category': 'Office'},
    {'Brand': 'Pro Works', 'Company': 'DeskPro Corp', 'Category': 'Office'},
    {'Brand': 'File Direct', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'File Max', 'Company': 'WorkSpace Solutions', 'Category': 'Office'},
    {'Brand': 'Work Supply', 'Company': 'BusinessSupply Inc', 'Category': 'Office'},
    {'Brand': 'Pro Supply', 'Company': 'DeskPro Corp', 'Category': 'Office'},
    {'Brand': 'Work Pro', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Pro Max', 'Company': 'WorkSpace Solutions', 'Category': 'Office'},
    {'Brand': 'Copy Direct', 'Company': 'BusinessSupply Inc', 'Category': 'Office'},
    {'Brand': 'Note Plus', 'Company': 'DeskPro Corp', 'Category': 'Office'},
    {'Brand': 'Work Smart', 'Company': 'OfficeMart Corp', 'Category': 'Office'},
    {'Brand': 'Print First', 'Company': 'WorkSpace Solutions', 'Category': 'Office'},
    {'Brand': 'Office First', 'Company': 'BusinessSupply Inc', 'Category': 'Office'},
    {'Brand': 'Print Office', 'Company': 'DeskPro Corp', 'Category': 'Office'},
    {'Brand': 'Furry Care', 'Company': 'AnimalCare Corp', 'Category': 'Pet'},
    {'Brand': 'Top Paws', 'Company': 'BluePaws Co', 'Category': 'Pet'},
    {'Brand': 'Lucky Life', 'Company': 'CatTreats Company', 'Category': 'Pet'},
    {'Brand': 'Happy Love', 'Company': 'DogFood Co', 'Category': 'Pet'},
    {'Brand': 'Top Pal', 'Company': 'PetFood Nutrition', 'Category': 'Pet'},
    {'Brand': 'Paw Buddy', 'Company': 'PetVitality Corp', 'Category': 'Pet'},
    {'Brand': 'Best Pet', 'Company': 'AnimalCare Corp', 'Category': 'Pet'},
    {'Brand': 'Golden Buddy', 'Company': 'BluePaws Co', 'Category': 'Pet'},
    {'Brand': 'Golden Paws', 'Company': 'CatTreats Company', 'Category': 'Pet'},
    {'Brand': 'Top Chow', 'Company': 'DogFood Co', 'Category': 'Pet'},
    {'Brand': 'Motor Tech', 'Company': 'EngineLube Oil', 'Category': 'Automotive'},
    {'Brand': 'Motor Drive', 'Company': 'FluidCare Limited', 'Category': 'Automotive'},
    {'Brand': 'Auto Drive', 'Company': 'FuelOil Products', 'Category': 'Automotive'},
    {'Brand': 'Road Max', 'Company': 'MotorOil Inc', 'Category': 'Automotive'},
    {'Brand': 'Race Drive', 'Company': 'PetroProducts America', 'Category': 'Automotive'},
    {'Brand': 'Drive Pro', 'Company': 'EngineLube Oil', 'Category': 'Automotive'},
    {'Brand': 'Engine Zone', 'Company': 'FluidCare Limited', 'Category': 'Automotive'},
    {'Brand': 'Team Gear', 'Company': 'Athletic Inc', 'Category': 'Sports'},
    {'Brand': 'Elite Pro', 'Company': 'BallSports Inc', 'Category': 'Sports'},
    {'Brand': 'Star Athletic', 'Company': 'GolfBalls Corp', 'Category': 'Sports'},
    {'Brand': 'Sport Play', 'Company': 'GolfClub Co', 'Category': 'Sports'},
    {'Brand': 'Champion Sport', 'Company': 'MaxCl Co', 'Category': 'Sports'},
    {'Brand': 'Athletic Play', 'Company': 'SwingCorp Company', 'Category': 'Sports'},
    {'Brand': 'Win Team', 'Company': 'Athletic Inc', 'Category': 'Sports'},
    {'Brand': 'Win Athletic', 'Company': 'BallSports Inc', 'Category': 'Sports'},
    {'Brand': 'Victory Sport', 'Company': 'GolfBalls Corp', 'Category': 'Sports'},
    {'Brand': 'Team Zone', 'Company': 'GolfClub Co', 'Category': 'Sports'},
    {'Brand': 'Victory Game', 'Company': 'MaxCl Co', 'Category': 'Sports'},
]
