"""
Products source data for supercenter retail profile.

This data is 100% synthetic and safe for demo/POC purposes.
"""

PRODUCTS = [
    {'ProductName': 'Organic Whole Wheat Bread', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Bakery', 'Subcategory': 'Bread & Rolls'},
    {'ProductName': 'Free Range Chicken Breast', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Chicken'},
    {'ProductName': 'Almond Milk Unsweetened', 'BasePrice': '4.29', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Plant-Based Milk'},
    {'ProductName': 'Greek Yogurt Vanilla', 'BasePrice': '5.49', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Yogurt'},
    {'ProductName': 'Organic Baby Spinach', 'BasePrice': '3.79', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Premium Ground Coffee', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Coffee & Tea'},
    {'ProductName': 'Artisan Pasta Sauce', 'BasePrice': '6.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Wild Caught Salmon Fillet', 'BasePrice': '15.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Bananas', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Extra Virgin Olive Oil', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Grass Fed Ground Beef', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Beef'},
    {'ProductName': 'Quinoa Ancient Grain', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Grains & Rice'},
    {'ProductName': 'Organic Tomatoes', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Free Range Eggs Large', 'BasePrice': '4.79', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Eggs'},
    {'ProductName': 'Coconut Water Natural', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Water & Hydration'},
    {'ProductName': 'Dark Chocolate Bar', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Snacks & Candy', 'Subcategory': 'Chocolate'},
    {'ProductName': 'Organic Avocados', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Steel Cut Oats', 'BasePrice': '5.49', 'Department': 'Grocery', 'Category': 'Breakfast & Cereal', 'Subcategory': 'Hot Cereal'},
    {'ProductName': 'Fresh Mozzarella Cheese', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Cheese'},
    {'ProductName': 'Organic Blueberries', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Peanut Butter Natural', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Nut Butters & Spreads'},
    {'ProductName': 'Whole Grain Cereal', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Breakfast & Cereal', 'Subcategory': 'Cold Cereal'},
    {'ProductName': 'Organic Strawberries', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Sea Salt Fine', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Raw Honey Wildflower', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sweeteners'},
    {'ProductName': 'Organic Carrots', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Basmati Rice Premium', 'BasePrice': '6.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Grains & Rice'},
    {'ProductName': 'Fresh Atlantic Cod', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Bell Peppers', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Almond Butter Smooth', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Nut Butters & Spreads'},
    {'ProductName': 'Sparkling Water Lemon', 'BasePrice': '1.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Water & Hydration'},
    {'ProductName': 'Organic Apples Gala', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Black Beans Organic', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Canned & Jarred'},
    {'ProductName': 'Coconut Oil Virgin', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Fresh Broccoli Crowns', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Himalayan Pink Salt', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Organic Cucumbers', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Premium Tea Bags', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Coffee & Tea'},
    {'ProductName': 'Free Range Turkey Breast', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Turkey'},
    {'ProductName': 'Organic Sweet Potatoes', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Cashew Milk Vanilla', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Plant-Based Milk'},
    {'ProductName': 'Organic Kale Leaves', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Artisan Crackers', 'BasePrice': '5.49', 'Department': 'Grocery', 'Category': 'Snacks & Candy', 'Subcategory': 'Crackers & Chips'},
    {'ProductName': 'Wild Rice Blend', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Grains & Rice'},
    {'ProductName': 'Organic Zucchini', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Premium Vanilla Extract', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Free Range Chicken Thighs', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Chicken'},
    {'ProductName': 'Organic Lemons', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Chia Seeds Organic', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Fresh Asparagus Spears', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Mushrooms Mixed', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Coconut Flakes Unsweetened', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Balsamic Vinegar', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Organic Grape Tomatoes', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Grass Fed Butter', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Butter & Margarine'},
    {'ProductName': 'Quinoa Flour Organic', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Green Beans', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Onions Yellow', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Maple Syrup Pure', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sweeteners'},
    {'ProductName': 'Free Range Duck Breast', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Duck'},
    {'ProductName': 'Organic Celery Stalks', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Almond Flour Blanched', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Sparkling Water Lime', 'BasePrice': '1.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Water & Hydration'},
    {'ProductName': 'Organic Potatoes Russet', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Lentils Red Organic', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Beans & Legumes'},
    {'ProductName': 'Coconut Milk Canned', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Plant-Based Milk'},
    {'ProductName': 'Fresh Cauliflower Head', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Garlic Bulbs', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Premium Spice Blend', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Wild Mushrooms Fresh', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Beets Fresh', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Tahini Sesame Seed', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Nut Butters & Spreads'},
    {'ProductName': 'Fresh Brussels Sprouts', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Romaine Lettuce', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Coconut Sugar Raw', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Truffle Oil', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Free Range Pork Tenderloin', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Pork'},
    {'ProductName': 'Organic Radishes', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Flax Seeds Ground', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Fresh Artichoke Hearts', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Cabbage Green', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Raw Cacao Powder', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Fish Sauce', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Parsley Fresh', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Hemp Seeds Hulled', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Fresh Corn Sweet', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Cilantro Fresh', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Miso Paste White', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Premium Saffron Threads', 'BasePrice': '49.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Free Range Lamb Chops', 'BasePrice': '22.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Lamb'},
    {'ProductName': 'Organic Mint Fresh', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Nutritional Yeast Flakes', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Pineapple Chunks', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Basil Fresh', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Kombucha Ginger', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Premium Aged Cheese', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Cheese'},
    {'ProductName': 'Organic Dill Fresh', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Apple Cider Vinegar Raw', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Fresh Mango Sliced', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Thyme Fresh', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Bone Broth Chicken', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Chicken'},
    {'ProductName': 'Premium Smoked Salmon', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Oregano Fresh', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Sprouted Grain Bread', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Bakery', 'Subcategory': 'Bread & Rolls'},
    {'ProductName': 'Fresh Papaya Chunks', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Rosemary Fresh', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Kelp Noodles Raw', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Pasta & Noodles'},
    {'ProductName': 'Premium Caviar', 'BasePrice': '89.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Caviar & Roe'},
    {'ProductName': 'Organic Sage Fresh', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Fermented Vegetables', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Canned & Jarred'},
    {'ProductName': 'Fresh Kiwi Fruit', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Tarragon Fresh', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Probiotic Yogurt', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Yogurt'},
    {'ProductName': 'Premium Wagyu Beef', 'BasePrice': '49.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Beef'},
    {'ProductName': 'Organic Chives Fresh', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Spirulina Powder', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Dragon Fruit', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Bay Leaves', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Matcha Green Tea', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Coffee & Tea'},
    {'ProductName': 'Premium Lobster Tail', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Marjoram Fresh', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Herbs'},
    {'ProductName': 'Goji Berries Dried', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Dried Fruit'},
    {'ProductName': 'Fresh Star Fruit', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Cumin Seeds', 'BasePrice': '5.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Chlorella Tablets', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Oysters Fresh', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Fennel Bulb', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Acai Berry Powder', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Passion Fruit', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Coriander Seeds', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Wheatgrass Powder', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Scallops Sea', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Cardamom Pods', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Maca Root Powder', 'BasePrice': '18.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Lychee Fruit', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Turmeric Root', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Ashwagandha Powder', 'BasePrice': '22.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Crab Legs', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Ginger Root', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Moringa Powder', 'BasePrice': '21.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Rambutan', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Cinnamon Sticks', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Reishi Mushroom Powder', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Uni Sea Urchin', 'BasePrice': '59.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Nutmeg Whole', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Cordyceps Mushroom', 'BasePrice': '44.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Durian Fruit', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Cloves Whole', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': "Lion's Mane Mushroom", 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Tuna Sashimi', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Allspice Berries', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Turkey Tail Mushroom', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Turkey'},
    {'ProductName': 'Fresh Jackfruit', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Mustard Seeds', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Chaga Mushroom Extract', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Hamachi', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Fenugreek Seeds', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Shiitake Mushroom Dried', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Soursop', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Anise Seeds', 'BasePrice': '7.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Maitake Mushroom Fresh', 'BasePrice': '18.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Premium Yellowtail', 'BasePrice': '28.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Celery Seeds', 'BasePrice': '5.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Oyster Mushroom Fresh', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Fresh Cherimoya', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Poppy Seeds', 'BasePrice': '9.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Enoki Mushroom Fresh', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Premium Salmon Roe', 'BasePrice': '49.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Sesame Seeds', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'King Oyster Mushroom', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Fresh Custard Apple', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Sunflower Seeds', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Chanterelle Mushroom', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Premium Monkfish', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Pumpkin Seeds', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Morel Mushroom Dried', 'BasePrice': '89.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Longan Fruit', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Pine Nuts', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Porcini Mushroom Dried', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Sea Bass', 'BasePrice': '22.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Pecans Halves', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Black Truffle Fresh', 'BasePrice': '199.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Specialty Items'},
    {'ProductName': 'Fresh Persimmon Fruit', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Walnuts Halves', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'White Truffle Oil', 'BasePrice': '44.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Premium Snapper Red', 'BasePrice': '18.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Brazil Nuts', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Truffle Salt Black', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Fresh Pomegranate Seeds', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Organic Hazelnuts', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Truffle Honey Wild', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sweeteners'},
    {'ProductName': 'Premium Grouper', 'BasePrice': '21.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Macadamia Nuts', 'BasePrice': '21.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Truffle Butter Fresh', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Specialty Butter'},
    {'ProductName': 'Fresh Fig Fruit', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Pistachios', 'BasePrice': '17.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Foie Gras Duck', 'BasePrice': '149.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Specialty Items'},
    {'ProductName': 'Premium Mahi Mahi', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Almonds Raw', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Caviar Beluga', 'BasePrice': '299.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Caviar & Roe'},
    {'ProductName': 'Fresh Date Fruit', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Cashews Raw', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Caviar Ossetra', 'BasePrice': '199.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Caviar & Roe'},
    {'ProductName': 'Premium Halibut', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Coconut Meat', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Caviar Sevruga', 'BasePrice': '149.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Caviar & Roe'},
    {'ProductName': 'Fresh Guava Fruit', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Tiger Nuts', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Seeds & Nuts'},
    {'ProductName': 'Sturgeon Smoked', 'BasePrice': '89.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Premium Arctic Char', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Cacao Nibs', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Eel Unagi Grilled', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Fresh Plantain Green', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Vanilla Beans', 'BasePrice': '49.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Octopus Spanish', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Premium Branzino', 'BasePrice': '22.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Saffron Premium', 'BasePrice': '199.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Squid Fresh Whole', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Fresh Breadfruit', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Bakery', 'Subcategory': 'Bread & Rolls'},
    {'ProductName': 'Organic Cardamom Green', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Abalone Canned', 'BasePrice': '59.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Canned & Jarred'},
    {'ProductName': 'Premium Turbot', 'BasePrice': '28.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Star Anise', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Sea Cucumber Dried', 'BasePrice': '89.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Specialty Items'},
    {'ProductName': 'Fresh Plantain Ripe', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Organic Long Pepper', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Shark Fin Soup', 'BasePrice': '199.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Canned & Jarred'},
    {'ProductName': 'Premium John Dory', 'BasePrice': '25.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Grains Paradise', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': "Bird's Nest Soup", 'BasePrice': '299.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Canned & Jarred'},
    {'ProductName': 'Fresh Yuca Root', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Sumac Berries', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Matsutake Mushroom', 'BasePrice': '149.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Specialty Items'},
    {'ProductName': 'Premium Dover Sole', 'BasePrice': '32.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': "Organic Za'atar Blend", 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Cordyceps Sinensis', 'BasePrice': '199.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Cassava Root', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Ras El Hanout', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Ginseng Root Wild', 'BasePrice': '89.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Langoustine', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Berbere Spice', 'BasePrice': '10.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Sea Lettuce Dried', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Fresh Taro Root', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Dukkah Blend', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Wakame Seaweed', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Asian Ingredients'},
    {'ProductName': 'Premium Prawns Tiger', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Harissa Paste', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Nori Sheets Premium', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Asian Ingredients'},
    {'ProductName': 'Fresh Sweet Potato', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Mole Paste', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Kombu Kelp Dried', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Asian Ingredients'},
    {'ProductName': 'Premium Shrimp Spot', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Curry Powder', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Dulse Flakes Red', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Jerusalem Artichoke', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Garam Masala', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Sea Grapes Fresh', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Specialty Items'},
    {'ProductName': 'Premium Langostino', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Chinese Five Spice', 'BasePrice': '10.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Spirulina Tablets', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Water Chestnut', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Tandoori Masala', 'BasePrice': '9.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Chlorella Powder', 'BasePrice': '21.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Crayfish', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Jerk Seasoning', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Blue Green Algae', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Lotus Root', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Cajun Seasoning', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Marine Collagen Powder', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Mud Crab', 'BasePrice': '32.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Old Bay Seasoning', 'BasePrice': '8.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Fish Collagen Peptides', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Fresh Bamboo Shoots', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Creole Seasoning', 'BasePrice': '7.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Krill Oil Capsules', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Premium King Crab', 'BasePrice': '89.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Italian Seasoning', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Cod Liver Oil', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Fresh Bean Sprouts', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Herbs Provence', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Salmon Oil Wild', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Premium Snow Crab', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Taco Seasoning', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Astaxanthin Supplement', 'BasePrice': '44.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Daikon Radish', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Ranch Seasoning', 'BasePrice': '5.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Omega 3 Algae Oil', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Premium Dungeness Crab', 'BasePrice': '28.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Onion Powder', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'DHA Algae Supplement', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Bok Choy', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Garlic Powder', 'BasePrice': '6.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'EPA Fish Oil', 'BasePrice': '22.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Premium Blue Crab', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Paprika Smoked', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Vitamin D3 Liquid', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Napa Cabbage', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Chili Powder', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Vitamin B12 Spray', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Soft Shell Crab', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Cayenne Pepper', 'BasePrice': '7.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Folate Methyl', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Chinese Broccoli', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Organic Black Pepper', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Iron Bisglycinate', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Stone Crab', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic White Pepper', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Magnesium Glycinate', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Mustard Greens', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Pink Peppercorns', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Zinc Picolinate', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Lobster Claws', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Green Peppercorns', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Selenium Methionine', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Collard Greens', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Sichuan Peppercorns', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Copper Bisglycinate', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Lobster Meat', 'BasePrice': '49.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Tellicherry Pepper', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Chromium Picolinate', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Turnip Greens', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Malabar Pepper', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Molybdenum Chelate', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium King Prawns', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Long Pepper Whole', 'BasePrice': '22.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Boron Citrate', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Swiss Chard', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Cubeb Pepper', 'BasePrice': '27.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Vanadium Chelate', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Tiger Prawns', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Pink Salt Coarse', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Manganese Bisglycinate', 'BasePrice': '8.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Arugula Wild', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Black Salt Kala', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Iodine Kelp Extract', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Jumbo Shrimp', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Red Salt Alaea', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Potassium Citrate', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Watercress', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Grey Salt Celtic', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Calcium Magnesium', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Colossal Shrimp', 'BasePrice': '32.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Fleur de Sel', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Vitamin K2 MK7', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Purslane', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Smoked Salt', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'CoQ10 Ubiquinol', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Rock Shrimp', 'BasePrice': '18.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Truffle Salt', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'PQQ Supplement', 'BasePrice': '49.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': "Fresh Lamb's Lettuce", 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Saffron Salt', 'BasePrice': '49.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'NAD Precursor', 'BasePrice': '59.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Brown Shrimp', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Vanilla Salt', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Resveratrol Extract', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Mache Lettuce', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Lavender Salt', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Curcumin Complex', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium White Shrimp', 'BasePrice': '21.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Rosemary Salt', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Green Tea Extract', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Dandelion Greens', 'BasePrice': '5.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Lemon Salt', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Grape Seed Extract', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Premium Pink Shrimp', 'BasePrice': '23.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Lime Salt', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Pine Bark Extract', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Chicory Leaves', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Orange Salt', 'BasePrice': '10.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Milk Thistle Extract', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Gulf Shrimp', 'BasePrice': '26.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Fish'},
    {'ProductName': 'Organic Chili Salt', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Saw Palmetto Extract', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Endive Belgian', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Garlic Salt', 'BasePrice': '6.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Ginkgo Biloba Extract', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Bay Scallops', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Onion Salt', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Ginseng Extract', 'BasePrice': '22.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Radicchio Red', 'BasePrice': '7.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Celery Salt', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Rhodiola Rosea', 'BasePrice': '18.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Sea Scallops', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Dill Salt', 'BasePrice': '8.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Ashwagandha Extract', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Frisee Lettuce', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Herb Salt', 'BasePrice': '9.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Bacopa Monnieri', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Diver Scallops', 'BasePrice': '49.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Mushroom Salt', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': "Lion's Mane Extract", 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Escarole', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Seaweed Salt', 'BasePrice': '11.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Cordyceps Extract', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Dry Scallops', 'BasePrice': '69.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Smoke Salt', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Reishi Extract', 'BasePrice': '22.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Butter Lettuce', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Wine Salt', 'BasePrice': '15.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Chaga Extract', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Wet Scallops', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Beer Salt', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Turkey Tail Extract', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Turkey'},
    {'ProductName': 'Fresh Red Lettuce', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Coffee Salt', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Maitake Extract', 'BasePrice': '21.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Weathervane Scallops', 'BasePrice': '44.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Chocolate Salt', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Shiitake Extract', 'BasePrice': '18.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Green Lettuce', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Caramel Salt', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Spices & Seasonings'},
    {'ProductName': 'Oyster Mushroom Extract', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Calico Scallops', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Vanilla Sugar', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Enoki Mushroom Extract', 'BasePrice': '15.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Iceberg Lettuce', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Cinnamon Sugar', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'King Oyster Extract', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Pink Scallops', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Coconut Sugar', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Chanterelle Extract', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Boston Lettuce', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Palm Sugar', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Morel Extract', 'BasePrice': '79.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Maine Scallops', 'BasePrice': '54.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Date Sugar', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Porcini Extract', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Bibb Lettuce', 'BasePrice': '5.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Maple Sugar', 'BasePrice': '18.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Black Truffle Extract', 'BasePrice': '99.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Premium Nantucket Scallops', 'BasePrice': '64.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Beet Sugar', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'White Truffle Extract', 'BasePrice': '149.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Fresh Romaine Hearts', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Cane Sugar', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Truffle Oil Extract', 'BasePrice': '34.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Premium Diver Scallops Wild', 'BasePrice': '79.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Brown Sugar', 'BasePrice': '6.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Shiitake Powder Dried', 'BasePrice': '22.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Little Gem Lettuce', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Raw Sugar', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Maitake Powder Dried', 'BasePrice': '26.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium U10 Scallops', 'BasePrice': '89.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Turbinado Sugar', 'BasePrice': '9.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Reishi Powder Dried', 'BasePrice': '32.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Red Oak Lettuce', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Demerara Sugar', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Cordyceps Powder Dried', 'BasePrice': '44.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium U15 Scallops', 'BasePrice': '69.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Muscovado Sugar', 'BasePrice': '14.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': "Lion's Mane Powder", 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Green Oak Lettuce', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Jaggery Sugar', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Turkey Tail Powder', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Turkey'},
    {'ProductName': 'Premium Sea Scallops Dry', 'BasePrice': '99.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Piloncillo Sugar', 'BasePrice': '10.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Chaga Powder Dried', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Lolla Rossa', 'BasePrice': '6.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Panela Sugar', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Oyster Mushroom Powder', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Scallops Sashimi', 'BasePrice': '119.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Sucanat Sugar', 'BasePrice': '13.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Enoki Mushroom Powder', 'BasePrice': '17.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Mizuna Leaves', 'BasePrice': '7.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Rapadura Sugar', 'BasePrice': '15.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'King Oyster Powder', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Scallops Crudo', 'BasePrice': '129.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Coconut Nectar', 'BasePrice': '18.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sweeteners'},
    {'ProductName': 'Chanterelle Powder', 'BasePrice': '49.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Tatsoi Greens', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Agave Nectar', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sweeteners'},
    {'ProductName': 'Morel Powder Dried', 'BasePrice': '119.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Premium Scallops Tartare', 'BasePrice': '139.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Yacon Syrup', 'BasePrice': '19.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sweeteners'},
    {'ProductName': 'Porcini Powder Dried', 'BasePrice': '39.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Baby Arugula', 'BasePrice': '7.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Monk Fruit', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sweeteners'},
    {'ProductName': 'Black Truffle Powder', 'BasePrice': '199.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Specialty Items'},
    {'ProductName': 'Premium Scallops Carpaccio', 'BasePrice': '149.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Stevia Extract', 'BasePrice': '16.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'White Truffle Powder', 'BasePrice': '299.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Specialty Items'},
    {'ProductName': 'Fresh Baby Spinach', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Organic Erythritol', 'BasePrice': '11.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sweeteners'},
    {'ProductName': 'Truffle Powder Mixed', 'BasePrice': '149.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Specialty Items'},
    {'ProductName': 'Premium Scallops Ceviche', 'BasePrice': '89.99', 'Department': 'Grocery', 'Category': 'Seafood', 'Subcategory': 'Shellfish'},
    {'ProductName': 'Organic Xylitol', 'BasePrice': '13.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sweeteners'},
    {'ProductName': 'Mushroom Blend Powder', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Health & Supplements'},
    {'ProductName': 'Fresh Baby Kale', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Leafy Greens'},
    {'ProductName': 'Cotton Bath Towel Set', 'BasePrice': '29.99', 'Department': 'Home & Garden', 'Category': 'Bath', 'Subcategory': 'Towels & Linens'},
    {'ProductName': 'LED Light Bulb 60W', 'BasePrice': '8.99', 'Department': 'Home & Garden', 'Category': 'Lighting', 'Subcategory': 'Light Bulbs'},
    {'ProductName': 'Memory Foam Pillow', 'BasePrice': '39.99', 'Department': 'Home & Garden', 'Category': 'Bedding', 'Subcategory': 'Pillows & Accessories'},
    {'ProductName': 'Ceramic Dinner Plate Set', 'BasePrice': '49.99', 'Department': 'Home & Garden', 'Category': 'Kitchen', 'Subcategory': 'Dinnerware'},
    {'ProductName': 'Stainless Steel Kitchen Knife', 'BasePrice': '24.99', 'Department': 'Home & Garden', 'Category': 'Kitchen', 'Subcategory': 'Cutlery & Tools'},
    {'ProductName': 'Non-Stick Frying Pan 12in', 'BasePrice': '34.99', 'Department': 'Home & Garden', 'Category': 'Kitchen', 'Subcategory': 'Cookware'},
    {'ProductName': 'Glass Food Storage Container', 'BasePrice': '19.99', 'Department': 'Home & Garden', 'Category': 'Kitchen', 'Subcategory': 'Storage & Organization'},
    {'ProductName': 'Microfiber Cleaning Cloth', 'BasePrice': '12.99', 'Department': 'Home & Garden', 'Category': 'Cleaning', 'Subcategory': 'Cleaning Supplies'},
    {'ProductName': 'All-Purpose Cleaner Spray', 'BasePrice': '4.99', 'Department': 'Home & Garden', 'Category': 'Cleaning', 'Subcategory': 'Cleaning Supplies'},
    {'ProductName': 'Wireless Bluetooth Headphones', 'BasePrice': '79.99', 'Department': 'Electronics', 'Category': 'Audio', 'Subcategory': 'Headphones & Earbuds'},
    {'ProductName': 'Smartphone Charging Cable', 'BasePrice': '14.99', 'Department': 'Electronics', 'Category': 'Accessories', 'Subcategory': 'Phone & Tablet Accessories'},
    {'ProductName': 'Portable Phone Charger', 'BasePrice': '29.99', 'Department': 'Electronics', 'Category': 'Accessories', 'Subcategory': 'Phone & Tablet Accessories'},
    {'ProductName': 'Digital Photo Frame', 'BasePrice': '89.99', 'Department': 'Electronics', 'Category': 'Home Electronics', 'Subcategory': 'Digital Cameras & Accessories'},
    {'ProductName': 'Bluetooth Speaker Portable', 'BasePrice': '49.99', 'Department': 'Electronics', 'Category': 'Audio', 'Subcategory': 'Speakers'},
    {'ProductName': 'USB Flash Drive 32GB', 'BasePrice': '19.99', 'Department': 'Electronics', 'Category': 'Computer', 'Subcategory': 'Storage & Memory'},
    {'ProductName': 'HDMI Cable 6ft', 'BasePrice': '12.99', 'Department': 'Electronics', 'Category': 'Accessories', 'Subcategory': 'Cables & Adapters'},
    {'ProductName': 'Smart Fitness Tracker', 'BasePrice': '149.99', 'Department': 'Electronics', 'Category': 'Wearables', 'Subcategory': 'Fitness Trackers'},
    {'ProductName': 'Tablet Screen Protector', 'BasePrice': '9.99', 'Department': 'Electronics', 'Category': 'Accessories', 'Subcategory': 'Phone & Tablet Accessories'},
    {'ProductName': 'Wireless Computer Mouse', 'BasePrice': '24.99', 'Department': 'Electronics', 'Category': 'Computer', 'Subcategory': 'Input Devices'},
    {'ProductName': "Men's Cotton T-Shirt", 'BasePrice': '14.99', 'Department': 'Clothing', 'Category': "Men's Apparel", 'Subcategory': 'Shirts & Tops'},
    {'ProductName': "Women's Yoga Pants", 'BasePrice': '29.99', 'Department': 'Clothing', 'Category': "Women's Apparel", 'Subcategory': 'Activewear'},
    {'ProductName': "Kids' Sneakers Size 10", 'BasePrice': '34.99', 'Department': 'Clothing', 'Category': "Children's Apparel", 'Subcategory': 'Shoes'},
    {'ProductName': 'Baseball Cap Adjustable', 'BasePrice': '19.99', 'Department': 'Clothing', 'Category': 'Accessories', 'Subcategory': 'Hats & Caps'},
    {'ProductName': "Women's Denim Jeans", 'BasePrice': '39.99', 'Department': 'Clothing', 'Category': "Women's Apparel", 'Subcategory': 'Jeans & Pants'},
    {'ProductName': "Men's Athletic Shorts", 'BasePrice': '24.99', 'Department': 'Clothing', 'Category': "Men's Apparel", 'Subcategory': 'Shorts'},
    {'ProductName': "Children's Pajama Set", 'BasePrice': '19.99', 'Department': 'Clothing', 'Category': "Children's Apparel", 'Subcategory': 'Sleepwear'},
    {'ProductName': 'Unisex Winter Gloves', 'BasePrice': '12.99', 'Department': 'Clothing', 'Category': 'Accessories', 'Subcategory': 'Gloves & Mittens'},
    {'ProductName': "Women's Running Shoes", 'BasePrice': '79.99', 'Department': 'Clothing', 'Category': "Women's Apparel", 'Subcategory': 'Athletic Shoes'},
    {'ProductName': "Men's Dress Shirt", 'BasePrice': '49.99', 'Department': 'Clothing', 'Category': "Men's Apparel", 'Subcategory': 'Dress Shirts'},
    {'ProductName': 'Multivitamin Tablets 90ct', 'BasePrice': '24.99', 'Department': 'Health & Beauty', 'Category': 'Vitamins & Supplements', 'Subcategory': 'Multivitamins'},
    {'ProductName': 'Shampoo & Conditioner Set', 'BasePrice': '16.99', 'Department': 'Health & Beauty', 'Category': 'Hair Care', 'Subcategory': 'Shampoo & Conditioner'},
    {'ProductName': 'Electric Toothbrush', 'BasePrice': '59.99', 'Department': 'Health & Beauty', 'Category': 'Oral Care', 'Subcategory': 'Toothbrushes'},
    {'ProductName': 'Face Moisturizer SPF 30', 'BasePrice': '19.99', 'Department': 'Health & Beauty', 'Category': 'Skin Care', 'Subcategory': 'Moisturizers'},
    {'ProductName': 'Pain Relief Tablets 100ct', 'BasePrice': '12.99', 'Department': 'Health & Beauty', 'Category': 'Medicine', 'Subcategory': 'Pain Relief'},
    {'ProductName': 'Hand Sanitizer Gel 8oz', 'BasePrice': '3.99', 'Department': 'Health & Beauty', 'Category': 'Personal Care', 'Subcategory': 'Hand Care'},
    {'ProductName': 'Deodorant Antiperspirant', 'BasePrice': '5.99', 'Department': 'Health & Beauty', 'Category': 'Personal Care', 'Subcategory': 'Deodorants'},
    {'ProductName': 'Body Lotion Unscented', 'BasePrice': '8.99', 'Department': 'Health & Beauty', 'Category': 'Skin Care', 'Subcategory': 'Body Moisturizers'},
    {'ProductName': 'Contact Lens Solution', 'BasePrice': '9.99', 'Department': 'Health & Beauty', 'Category': 'Vision Care', 'Subcategory': 'Contact Lens Care'},
    {'ProductName': 'Lip Balm SPF 15', 'BasePrice': '2.99', 'Department': 'Health & Beauty', 'Category': 'Personal Care', 'Subcategory': 'Lip Care'},
    {'ProductName': 'Baby Formula Powder', 'BasePrice': '28.99', 'Department': 'Baby & Kids', 'Category': 'Baby Food', 'Subcategory': 'Formula'},
    {'ProductName': 'Disposable Diapers Size 3', 'BasePrice': '34.99', 'Department': 'Baby & Kids', 'Category': 'Diaper & Potty', 'Subcategory': 'Disposable Diapers'},
    {'ProductName': 'Baby Wipes Sensitive', 'BasePrice': '6.99', 'Department': 'Baby & Kids', 'Category': 'Diaper & Potty', 'Subcategory': 'Baby Wipes'},
    {'ProductName': "Children's Toy Building Blocks", 'BasePrice': '24.99', 'Department': 'Baby & Kids', 'Category': 'Toys', 'Subcategory': 'Building & Construction'},
    {'ProductName': 'Baby Bottle 8oz', 'BasePrice': '12.99', 'Department': 'Baby & Kids', 'Category': 'Feeding', 'Subcategory': 'Bottles & Cups'},
    {'ProductName': 'Pacifier 2-Pack', 'BasePrice': '7.99', 'Department': 'Baby & Kids', 'Category': 'Feeding', 'Subcategory': 'Pacifiers & Teethers'},
    {'ProductName': 'Baby Shampoo Gentle', 'BasePrice': '8.99', 'Department': 'Baby & Kids', 'Category': 'Bath & Body', 'Subcategory': 'Shampoo & Wash'},
    {'ProductName': 'Car Seat Cover', 'BasePrice': '19.99', 'Department': 'Baby & Kids', 'Category': 'Safety', 'Subcategory': 'Car Seats & Travel'},
    {'ProductName': "Children's Picture Book", 'BasePrice': '9.99', 'Department': 'Baby & Kids', 'Category': 'Toys', 'Subcategory': 'Books & Learning'},
    {'ProductName': 'Baby Blanket Soft', 'BasePrice': '29.99', 'Department': 'Baby & Kids', 'Category': 'Nursery', 'Subcategory': 'Blankets & Swaddles'},
    {'ProductName': 'Laundry Detergent Pods 42ct', 'BasePrice': '19.99', 'Department': 'Home & Garden', 'Category': 'Laundry', 'Subcategory': 'Laundry Detergent'},
    {'ProductName': 'Fabric Softener Liquid', 'BasePrice': '7.99', 'Department': 'Home & Garden', 'Category': 'Laundry', 'Subcategory': 'Fabric Softeners'},
    {'ProductName': 'Toilet Paper 12 Roll Pack', 'BasePrice': '14.99', 'Department': 'Home & Garden', 'Category': 'Paper Products', 'Subcategory': 'Toilet Paper'},
    {'ProductName': 'Paper Towels 6 Roll Pack', 'BasePrice': '12.99', 'Department': 'Home & Garden', 'Category': 'Paper Products', 'Subcategory': 'Paper Towels'},
    {'ProductName': 'Trash Bags 13 Gallon 40ct', 'BasePrice': '11.99', 'Department': 'Home & Garden', 'Category': 'Cleaning', 'Subcategory': 'Trash Bags'},
    {'ProductName': 'Dish Soap Liquid', 'BasePrice': '3.99', 'Department': 'Home & Garden', 'Category': 'Cleaning', 'Subcategory': 'Dishwashing'},
    {'ProductName': 'Sponges Kitchen 8-Pack', 'BasePrice': '5.99', 'Department': 'Home & Garden', 'Category': 'Cleaning', 'Subcategory': 'Sponges & Scrubbers'},
    {'ProductName': 'Aluminum Foil 75 sq ft', 'BasePrice': '4.99', 'Department': 'Home & Garden', 'Category': 'Kitchen', 'Subcategory': 'Food Storage & Wraps'},
    {'ProductName': 'Plastic Food Wrap', 'BasePrice': '3.99', 'Department': 'Home & Garden', 'Category': 'Kitchen', 'Subcategory': 'Food Storage & Wraps'},
    {'ProductName': 'Oven Mitt Heat Resistant', 'BasePrice': '8.99', 'Department': 'Home & Garden', 'Category': 'Kitchen', 'Subcategory': 'Oven Mitts & Pot Holders'},
    {'ProductName': 'Dog Food Dry 15lb Bag', 'BasePrice': '39.99', 'Department': 'Pet Supplies', 'Category': 'Dog', 'Subcategory': 'Dog Food'},
    {'ProductName': 'Cat Litter Clumping 20lb', 'BasePrice': '16.99', 'Department': 'Pet Supplies', 'Category': 'Cat', 'Subcategory': 'Cat Litter'},
    {'ProductName': 'Dog Toy Rope', 'BasePrice': '7.99', 'Department': 'Pet Supplies', 'Category': 'Dog', 'Subcategory': 'Dog Toys'},
    {'ProductName': 'Cat Treats Salmon Flavor', 'BasePrice': '4.99', 'Department': 'Pet Supplies', 'Category': 'Cat', 'Subcategory': 'Cat Treats'},
    {'ProductName': 'Pet Food Bowl Stainless Steel', 'BasePrice': '12.99', 'Department': 'Pet Supplies', 'Category': 'Feeding', 'Subcategory': 'Food & Water Bowls'},
    {'ProductName': 'Dog Leash 6ft', 'BasePrice': '14.99', 'Department': 'Pet Supplies', 'Category': 'Dog', 'Subcategory': 'Leashes & Collars'},
    {'ProductName': 'Cat Scratching Post', 'BasePrice': '29.99', 'Department': 'Pet Supplies', 'Category': 'Cat', 'Subcategory': 'Scratching Posts & Pads'},
    {'ProductName': 'Pet Waste Bags 200ct', 'BasePrice': '8.99', 'Department': 'Pet Supplies', 'Category': 'Dog', 'Subcategory': 'Waste Management'},
    {'ProductName': 'Aquarium Fish Food Flakes', 'BasePrice': '6.99', 'Department': 'Pet Supplies', 'Category': 'Fish & Aquatic', 'Subcategory': 'Fish Food'},
    {'ProductName': 'Bird Seed Wild Mix 10lb', 'BasePrice': '19.99', 'Department': 'Pet Supplies', 'Category': 'Bird', 'Subcategory': 'Bird Food'},
    {'ProductName': 'Motor Oil 5W-30 5 Quart', 'BasePrice': '24.99', 'Department': 'Automotive', 'Category': 'Fluids & Chemicals', 'Subcategory': 'Motor Oil'},
    {'ProductName': 'Car Air Freshener', 'BasePrice': '2.99', 'Department': 'Automotive', 'Category': 'Interior', 'Subcategory': 'Air Fresheners'},
    {'ProductName': 'Windshield Washer Fluid', 'BasePrice': '3.99', 'Department': 'Automotive', 'Category': 'Fluids & Chemicals', 'Subcategory': 'Windshield Washer Fluid'},
    {'ProductName': 'Car Phone Mount', 'BasePrice': '19.99', 'Department': 'Automotive', 'Category': 'Electronics', 'Subcategory': 'Phone Mounts & Holders'},
    {'ProductName': 'Tire Pressure Gauge', 'BasePrice': '12.99', 'Department': 'Automotive', 'Category': 'Tools & Equipment', 'Subcategory': 'Tire Gauges & Inflators'},
    {'ProductName': 'Jumper Cables 12ft', 'BasePrice': '29.99', 'Department': 'Automotive', 'Category': 'Tools & Equipment', 'Subcategory': 'Jump Starters & Cables'},
    {'ProductName': 'Car Seat Covers', 'BasePrice': '49.99', 'Department': 'Automotive', 'Category': 'Interior', 'Subcategory': 'Seat Covers'},
    {'ProductName': 'Emergency Kit First Aid', 'BasePrice': '34.99', 'Department': 'Automotive', 'Category': 'Safety', 'Subcategory': 'Emergency Kits'},
    {'ProductName': 'Car Floor Mats', 'BasePrice': '39.99', 'Department': 'Automotive', 'Category': 'Interior', 'Subcategory': 'Floor Mats & Liners'},
    {'ProductName': 'Window Tint Film', 'BasePrice': '24.99', 'Department': 'Automotive', 'Category': 'Exterior', 'Subcategory': 'Window Tinting'},
    {'ProductName': 'Office Chair Ergonomic', 'BasePrice': '149.99', 'Department': 'Office Supplies', 'Category': 'Furniture', 'Subcategory': 'Chairs & Seating'},
    {'ProductName': 'Printer Paper 500 Sheets', 'BasePrice': '12.99', 'Department': 'Office Supplies', 'Category': 'Paper', 'Subcategory': 'Copy & Printing Paper'},
    {'ProductName': 'Black Ink Cartridge', 'BasePrice': '34.99', 'Department': 'Office Supplies', 'Category': 'Printing', 'Subcategory': 'Ink & Toner'},
    {'ProductName': 'Spiral Notebook 5-Pack', 'BasePrice': '8.99', 'Department': 'Office Supplies', 'Category': 'Paper', 'Subcategory': 'Notebooks & Pads'},
    {'ProductName': 'Ballpoint Pens 12-Pack', 'BasePrice': '5.99', 'Department': 'Office Supplies', 'Category': 'Writing', 'Subcategory': 'Pens & Pencils'},
    {'ProductName': 'Stapler Heavy Duty', 'BasePrice': '19.99', 'Department': 'Office Supplies', 'Category': 'Office Tools', 'Subcategory': 'Staplers & Staple Removers'},
    {'ProductName': 'File Folders Letter Size', 'BasePrice': '7.99', 'Department': 'Office Supplies', 'Category': 'Filing', 'Subcategory': 'Folders & Binders'},
    {'ProductName': 'Desk Lamp LED', 'BasePrice': '39.99', 'Department': 'Office Supplies', 'Category': 'Furniture', 'Subcategory': 'Desk Accessories'},
    {'ProductName': 'Wireless Keyboard', 'BasePrice': '49.99', 'Department': 'Office Supplies', 'Category': 'Computer', 'Subcategory': 'Keyboards & Mice'},
    {'ProductName': 'Paper Clips 500ct', 'BasePrice': '3.99', 'Department': 'Office Supplies', 'Category': 'Office Tools', 'Subcategory': 'Paper Clips & Fasteners'},
    {'ProductName': 'Gift Wrap Paper Roll', 'BasePrice': '6.99', 'Department': 'Seasonal', 'Category': 'Wrapping & Party', 'Subcategory': 'Gift Wrap & Bags'},
    {'ProductName': 'Birthday Candles 24ct', 'BasePrice': '3.99', 'Department': 'Seasonal', 'Category': 'Party Supplies', 'Subcategory': 'Candles & Cake Decorating'},
    {'ProductName': 'Plastic Party Plates 20ct', 'BasePrice': '4.99', 'Department': 'Seasonal', 'Category': 'Party Supplies', 'Subcategory': 'Tableware'},
    {'ProductName': 'Halloween Decoration Set', 'BasePrice': '19.99', 'Department': 'Seasonal', 'Category': 'Holiday Decor', 'Subcategory': 'Halloween'},
    {'ProductName': 'Christmas Tree Lights LED', 'BasePrice': '24.99', 'Department': 'Seasonal', 'Category': 'Holiday Decor', 'Subcategory': 'Christmas'},
    {'ProductName': "Valentine's Day Cards 32ct", 'BasePrice': '5.99', 'Department': 'Seasonal', 'Category': 'Cards & Stationery', 'Subcategory': 'Greeting Cards'},
    {'ProductName': 'Easter Egg Dye Kit', 'BasePrice': '7.99', 'Department': 'Seasonal', 'Category': 'Holiday Decor', 'Subcategory': 'Easter'},
    {'ProductName': 'Fourth of July Flag', 'BasePrice': '12.99', 'Department': 'Seasonal', 'Category': 'Holiday Decor', 'Subcategory': 'Independence Day'},
    {'ProductName': 'Thanksgiving Tablecloth', 'BasePrice': '14.99', 'Department': 'Seasonal', 'Category': 'Holiday Decor', 'Subcategory': 'Thanksgiving'},
    {'ProductName': "New Year's Party Hats", 'BasePrice': '8.99', 'Department': 'Seasonal', 'Category': 'Party Supplies', 'Subcategory': 'Party Favors'},
    {'ProductName': 'Sporting Goods Basketball', 'BasePrice': '29.99', 'Department': 'Sports & Recreation', 'Category': 'Team Sports', 'Subcategory': 'Basketballs'},
    {'ProductName': 'Yoga Mat Non-Slip', 'BasePrice': '24.99', 'Department': 'Sports & Recreation', 'Category': 'Fitness', 'Subcategory': 'Exercise Mats'},
    {'ProductName': 'Resistance Bands Set', 'BasePrice': '19.99', 'Department': 'Sports & Recreation', 'Category': 'Fitness', 'Subcategory': 'Resistance Training'},
    {'ProductName': 'Camping Tent 2-Person', 'BasePrice': '89.99', 'Department': 'Sports & Recreation', 'Category': 'Outdoor Recreation', 'Subcategory': 'Tents & Shelters'},
    {'ProductName': 'Fishing Rod Spinning', 'BasePrice': '49.99', 'Department': 'Sports & Recreation', 'Category': 'Fishing', 'Subcategory': 'Fishing Rods'},
    {'ProductName': 'Bicycle Helmet', 'BasePrice': '34.99', 'Department': 'Sports & Recreation', 'Category': 'Cycling', 'Subcategory': 'Helmets & Safety'},
    {'ProductName': 'Soccer Ball Official Size', 'BasePrice': '19.99', 'Department': 'Sports & Recreation', 'Category': 'Team Sports', 'Subcategory': 'Soccer Balls'},
    {'ProductName': 'Golf Balls 12-Pack', 'BasePrice': '24.99', 'Department': 'Sports & Recreation', 'Category': 'Golf', 'Subcategory': 'Golf Balls'},
    {'ProductName': 'Tennis Racket Lightweight', 'BasePrice': '79.99', 'Department': 'Sports & Recreation', 'Category': 'Racquet Sports', 'Subcategory': 'Tennis Rackets'},
    {'ProductName': 'Skateboard Complete', 'BasePrice': '99.99', 'Department': 'Sports & Recreation', 'Category': 'Action Sports', 'Subcategory': 'Skateboards'},
    {'ProductName': 'Hot Dog Buns 8ct', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Bakery', 'Subcategory': 'Bread & Rolls'},
    {'ProductName': 'Hamburger Buns 8ct', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Bakery', 'Subcategory': 'Bread & Rolls'},
    {'ProductName': 'All Beef Hot Dogs 10ct', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Sausage'},
    {'ProductName': 'Bratwurst Sausage 5ct', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Sausage'},
    {'ProductName': 'Italian Sausage Links 5ct', 'BasePrice': '6.49', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Sausage'},
    {'ProductName': 'Ketchup 38oz', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Yellow Mustard 20oz', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Sweet Pickle Relish 12oz', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'BBQ Sauce Original 18oz', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Potato Chips Family Size', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Snacks & Candy', 'Subcategory': 'Crackers & Chips'},
    {'ProductName': 'Tortilla Chips Family Size', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Snacks & Candy', 'Subcategory': 'Crackers & Chips'},
    {'ProductName': 'Salsa Medium 16oz', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Soda 12-Pack Cola', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Soft Drinks'},
    {'ProductName': 'Seltzer 12-Pack Lemon', 'BasePrice': '6.49', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Water & Hydration'},
    {'ProductName': 'Bagged Ice 10lb', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Water & Hydration'},
    {'ProductName': 'Charcoal Briquettes 16lb', 'BasePrice': '12.99', 'Department': 'Home & Garden', 'Category': 'Outdoor & Garden', 'Subcategory': 'Charcoal'},
    {'ProductName': 'Cranberry Sauce Canned 14oz', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Canned & Jarred'},
    {'ProductName': 'Pumpkin Pie 9in', 'BasePrice': '8.99', 'Department': 'Grocery', 'Category': 'Bakery', 'Subcategory': 'Pies & Desserts'},
    {'ProductName': 'Pie Crusts 2-Pack Frozen', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Stuffing Mix Box 12oz', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Cream of Mushroom Soup 10.5oz', 'BasePrice': '1.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Canned & Jarred'},
    {'ProductName': 'French Fried Onions 6oz', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Dinner Rolls 12ct', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Bakery', 'Subcategory': 'Bread & Rolls'},
    {'ProductName': 'Whole Turkey Fresh', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Turkey'},
    {'ProductName': 'Spiral Sliced Ham', 'BasePrice': '29.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Pork'},
    {'ProductName': 'Ham Roast Bone-In', 'BasePrice': '24.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Pork'},
    {'ProductName': 'Beef Burger Patties 6ct', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Beef'},
    {'ProductName': 'Chicken Wings Family Pack', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Chicken'},
    {'ProductName': 'Corn on the Cob 4ct', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Vegetables'},
    {'ProductName': 'Cornbread Mix 8.5oz', 'BasePrice': '1.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Paper Plates 100ct', 'BasePrice': '5.99', 'Department': 'Home & Garden', 'Category': 'Paper Products', 'Subcategory': 'Plates & Bowls'},
    {'ProductName': 'Plastic Cups 50ct', 'BasePrice': '4.99', 'Department': 'Home & Garden', 'Category': 'Paper Products', 'Subcategory': 'Cups'},
    {'ProductName': 'Dinner Napkins 200ct', 'BasePrice': '5.49', 'Department': 'Home & Garden', 'Category': 'Paper Products', 'Subcategory': 'Napkins'},
    {'ProductName': 'Picnic Cutlery Set 120ct', 'BasePrice': '6.99', 'Department': 'Home & Garden', 'Category': 'Paper Products', 'Subcategory': 'Disposable Cutlery'},
    {'ProductName': 'Christmas Ornaments Set', 'BasePrice': '19.99', 'Department': 'Seasonal', 'Category': 'Holiday Decor', 'Subcategory': 'Christmas'},
    {'ProductName': 'Christmas Garland 9ft', 'BasePrice': '14.99', 'Department': 'Seasonal', 'Category': 'Holiday Decor', 'Subcategory': 'Christmas'},
    {'ProductName': 'Turkey Gravy Mix 0.87oz', 'BasePrice': '1.29', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Brown Gravy Mix 1oz', 'BasePrice': '1.29', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Canned Yams 29oz', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Canned & Jarred'},
    {'ProductName': 'Marshmallows 16oz', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Apple Pie 9in', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Bakery', 'Subcategory': 'Pies & Desserts'},
    {'ProductName': 'Eggnog Half Gallon', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Milk & Cream'},
    {'ProductName': 'Hot Cocoa Mix 10ct', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Coffee & Tea'},
    {'ProductName': 'Candy Canes 12ct', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Snacks & Candy', 'Subcategory': 'Chocolate'},
    {'ProductName': 'Cheddar Cheese Block 8oz', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Cheese'},
    {'ProductName': 'Cottage Cheese 16oz', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Cheese'},
    {'ProductName': 'Sour Cream 16oz', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Milk & Cream'},
    {'ProductName': 'Cream Cheese 8oz', 'BasePrice': '2.79', 'Department': 'Grocery', 'Category': 'Dairy & Alternatives', 'Subcategory': 'Milk & Cream'},
    {'ProductName': 'Orange Juice 52oz', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Juice'},
    {'ProductName': 'Apple Juice 64oz', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Juice'},
    {'ProductName': 'Sports Drink 8-Pack', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Sports Drinks'},
    {'ProductName': 'Energy Drink 6-Pack', 'BasePrice': '9.99', 'Department': 'Grocery', 'Category': 'Beverages', 'Subcategory': 'Energy Drinks'},
    {'ProductName': 'Hand Soap 12oz', 'BasePrice': '2.49', 'Department': 'Home & Garden', 'Category': 'Bath', 'Subcategory': 'Hand Soap'},
    {'ProductName': 'Fluoride Toothpaste 6oz', 'BasePrice': '3.49', 'Department': 'Health & Beauty', 'Category': 'Oral Care', 'Subcategory': 'Toothpaste'},
    {'ProductName': 'Cat Food Dry 3lb', 'BasePrice': '8.99', 'Department': 'Pet Supplies', 'Category': 'Cat', 'Subcategory': 'Food'},
    {'ProductName': 'Ice Cream Vanilla 48oz', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Frozen', 'Subcategory': 'Ice Cream'},
    {'ProductName': 'Frozen Pizza Pepperoni', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Frozen', 'Subcategory': 'Pizza'},
    {'ProductName': 'Frozen Mixed Vegetables 16oz', 'BasePrice': '2.49', 'Department': 'Grocery', 'Category': 'Frozen', 'Subcategory': 'Vegetables'},
    {'ProductName': 'Frozen Strawberries 16oz', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Frozen', 'Subcategory': 'Fruit'},
    {'ProductName': 'Pancake Mix 32oz', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Breakfast & Cereal', 'Subcategory': 'Pancake & Waffle Mix'},
    {'ProductName': 'Grape Jelly 20oz', 'BasePrice': '2.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Jam & Jelly'},
    {'ProductName': 'Cooking Spray 6oz', 'BasePrice': '3.49', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Baking'},
    {'ProductName': 'Vegetable Oil 48oz', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Oils & Vinegars'},
    {'ProductName': 'Mayonnaise 30oz', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Pickles Dill Spears 24oz', 'BasePrice': '3.99', 'Department': 'Grocery', 'Category': 'Pantry', 'Subcategory': 'Sauces & Condiments'},
    {'ProductName': 'Granola Bars 12ct', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Snacks & Candy', 'Subcategory': 'Bars'},
    {'ProductName': 'Instant Oatmeal Packets 10ct', 'BasePrice': '4.49', 'Department': 'Grocery', 'Category': 'Breakfast & Cereal', 'Subcategory': 'Hot Cereal'},
    {'ProductName': 'Bacon 16oz', 'BasePrice': '6.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Pork'},
    {'ProductName': 'Ribeye Steak 1lb', 'BasePrice': '12.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Beef'},
    {'ProductName': 'Pork Chops Bone-In 1lb', 'BasePrice': '5.99', 'Department': 'Grocery', 'Category': 'Meat & Poultry', 'Subcategory': 'Pork'},
    {'ProductName': 'Navel Oranges 3lb Bag', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Produce', 'Subcategory': 'Fresh Fruit'},
    {'ProductName': 'Chocolate Chip Cookies Family Pack', 'BasePrice': '4.99', 'Department': 'Grocery', 'Category': 'Snacks & Candy', 'Subcategory': 'Cookies'},
]
