"""
Product Tags source data for supercenter retail profile.

This data is 100% synthetic and safe for demo/POC purposes.
"""

PRODUCT_TAGS = [
    {'ProductName': 'Free Range Turkey Breast', 'Tags': 'thanksgiving; turkey; main_course'},
    {'ProductName': 'Organic Sweet Potatoes', 'Tags': 'thanksgiving; yams; side_dish'},
    {'ProductName': 'Fresh Sweet Potato', 'Tags': 'thanksgiving; yams; side_dish'},
    {'ProductName': 'Fresh Green Beans', 'Tags': 'thanksgiving; green_bean_casserole; side_dish'},
    {'ProductName': 'Premium Vanilla Extract', 'Tags': 'thanksgiving; baking; christmas_foods'},
    {'ProductName': 'Coconut Flakes Unsweetened', 'Tags': 'thanksgiving; baking; christmas_foods'},
    {'ProductName': 'Quinoa Flour Organic', 'Tags': 'thanksgiving; baking; christmas_foods'},
    {'ProductName': 'Almond Flour Blanched', 'Tags': 'thanksgiving; baking; christmas_foods'},
    {'ProductName': 'Coconut Sugar Raw', 'Tags': 'thanksgiving; baking; christmas_foods'},
    {'ProductName': 'Organic Onions Yellow', 'Tags': 'thanksgiving; stuffing; casserole'},
    {'ProductName': 'Organic Celery Stalks', 'Tags': 'thanksgiving; stuffing; side_dish'},
    {'ProductName': 'Wild Rice Blend', 'Tags': 'thanksgiving; side_dish'},
    {'ProductName': 'Organic Whole Wheat Bread', 'Tags': 'thanksgiving; rolls; bread'},
    {'ProductName': 'Sprouted Grain Bread', 'Tags': 'thanksgiving; rolls; bread'},
    {'ProductName': 'Grass Fed Ground Beef', 'Tags': 'grill; burgers; july4; memorial_day; labor_day'},
    {'ProductName': 'Free Range Chicken Breast', 'Tags': 'grill; chicken; july4; memorial_day; labor_day'},
    {'ProductName': 'Free Range Chicken Thighs', 'Tags': 'grill; chicken; july4; memorial_day; labor_day'},
    {'ProductName': 'Free Range Pork Tenderloin', 'Tags': 'grill; pork; july4; memorial_day; labor_day'},
    {'ProductName': 'Wild Caught Salmon Fillet', 'Tags': 'grill; fish; july4; memorial_day; labor_day'},
    {'ProductName': 'Artisan Crackers', 'Tags': 'grill_out; chips; party_snacks'},
    {'ProductName': 'Dark Chocolate Bar', 'Tags': 'christmas_foods; candy; sweets'},
    {'ProductName': 'Gift Wrap Paper Roll', 'Tags': 'christmas_nonfood; nonfood; wrapping'},
    {'ProductName': 'Shampoo & Conditioner Set', 'Tags': 'nonfood; black_friday; xmas_nonfood'},
    {'ProductName': 'Baby Shampoo Gentle', 'Tags': 'nonfood; black_friday; xmas_nonfood'},
    {'ProductName': 'Toilet Paper 12 Roll Pack', 'Tags': 'nonfood; household'},
    {'ProductName': 'Paper Towels 6 Roll Pack', 'Tags': 'nonfood; household'},
    {'ProductName': 'Christmas Tree Lights LED', 'Tags': 'christmas_nonfood; lights; holiday; nonfood'},
    {'ProductName': 'LED Light Bulb 60W', 'Tags': 'lighting; nonfood'},
    {'ProductName': 'Fourth of July Flag', 'Tags': 'july4; holiday; nonfood; patriotic'},
    {'ProductName': 'Thanksgiving Tablecloth', 'Tags': 'thanksgiving; holiday_decor; nonfood'},
    {'ProductName': 'Halloween Decoration Set', 'Tags': 'halloween; holiday_decor; nonfood'},
    {'ProductName': 'Premium Balsamic Vinegar', 'Tags': 'grill; marinade'},
    {'ProductName': 'Premium Spice Blend', 'Tags': 'grill; marinade; spices'},
    {'ProductName': 'Free Range Duck Breast', 'Tags': 'grill; duck; july4; memorial_day; labor_day'},
    {'ProductName': 'All Beef Hot Dogs 10ct', 'Tags': 'grill; hot_dogs; july4; memorial_day; labor_day; buns; condiments'},
    {'ProductName': 'Bratwurst Sausage 5ct', 'Tags': 'grill; brats; sausage; july4; memorial_day; labor_day; buns; condiments'},
    {'ProductName': 'Italian Sausage Links 5ct', 'Tags': 'grill; sausage; july4; memorial_day; labor_day; buns; condiments'},
    {'ProductName': 'Hot Dog Buns 8ct', 'Tags': 'grill; buns; july4; memorial_day; labor_day'},
    {'ProductName': 'Hamburger Buns 8ct', 'Tags': 'grill; buns; july4; memorial_day; labor_day'},
    {'ProductName': 'Ketchup 38oz', 'Tags': 'grill; condiments; july4; memorial_day; labor_day'},
    {'ProductName': 'Yellow Mustard 20oz', 'Tags': 'grill; condiments; july4; memorial_day; labor_day'},
    {'ProductName': 'Sweet Pickle Relish 12oz', 'Tags': 'grill; condiments; july4; memorial_day; labor_day'},
    {'ProductName': 'BBQ Sauce Original 18oz', 'Tags': 'grill; condiments; july4; memorial_day; labor_day'},
    {'ProductName': 'Potato Chips Family Size', 'Tags': 'grill_out; chips; party_snacks'},
    {'ProductName': 'Tortilla Chips Family Size', 'Tags': 'grill_out; chips; party_snacks'},
    {'ProductName': 'Salsa Medium 16oz', 'Tags': 'grill_out; party_snacks'},
    {'ProductName': 'Soda 12-Pack Cola', 'Tags': 'grill_out; beverages; july4'},
    {'ProductName': 'Seltzer 12-Pack Lemon', 'Tags': 'grill_out; beverages; july4'},
    {'ProductName': 'Bagged Ice 10lb', 'Tags': 'grill_out; beverages; july4'},
    {'ProductName': 'Charcoal Briquettes 16lb', 'Tags': 'grill; charcoal; july4; memorial_day; labor_day'},
    {'ProductName': 'Cranberry Sauce Canned 14oz', 'Tags': 'thanksgiving; cranberry; side_dish'},
    {'ProductName': 'Pumpkin Pie 9in', 'Tags': 'thanksgiving; pies; dessert; christmas_foods'},
    {'ProductName': 'Pie Crusts 2-Pack Frozen', 'Tags': 'thanksgiving; baking; christmas_foods'},
    {'ProductName': 'Stuffing Mix Box 12oz', 'Tags': 'thanksgiving; stuffing; side_dish'},
    {'ProductName': 'Cream of Mushroom Soup 10.5oz', 'Tags': 'thanksgiving; casserole; green_bean_casserole'},
    {'ProductName': 'French Fried Onions 6oz', 'Tags': 'thanksgiving; casserole; green_bean_casserole'},
    {'ProductName': 'Dinner Rolls 12ct', 'Tags': 'thanksgiving; rolls; bread'},
    {'ProductName': 'Whole Turkey Fresh', 'Tags': 'thanksgiving; turkey; main_course'},
    {'ProductName': 'Spiral Sliced Ham', 'Tags': 'christmas_foods; ham; main_course'},
    {'ProductName': 'Ham Roast Bone-In', 'Tags': 'christmas_foods; ham; main_course'},
    {'ProductName': 'Beef Burger Patties 6ct', 'Tags': 'grill; burgers; july4; memorial_day; labor_day'},
    {'ProductName': 'Chicken Wings Family Pack', 'Tags': 'grill; chicken; july4; memorial_day; labor_day'},
    {'ProductName': 'Corn on the Cob 4ct', 'Tags': 'grill; side_dish; july4; memorial_day; labor_day'},
    {'ProductName': 'Cornbread Mix 8.5oz', 'Tags': 'thanksgiving; side_dish; baking'},
    {'ProductName': 'Paper Plates 100ct', 'Tags': 'grill_out; disposable; picnic'},
    {'ProductName': 'Plastic Cups 50ct', 'Tags': 'grill_out; disposable; picnic'},
    {'ProductName': 'Dinner Napkins 200ct', 'Tags': 'grill_out; disposable; picnic'},
    {'ProductName': 'Picnic Cutlery Set 120ct', 'Tags': 'grill_out; disposable; picnic'},
    {'ProductName': 'Christmas Ornaments Set', 'Tags': 'christmas_nonfood; ornaments; holiday; nonfood'},
    {'ProductName': 'Christmas Garland 9ft', 'Tags': 'christmas_nonfood; garland; holiday; nonfood'},
    {'ProductName': 'Turkey Gravy Mix 0.87oz', 'Tags': 'thanksgiving; gravy; side_dish'},
    {'ProductName': 'Brown Gravy Mix 1oz', 'Tags': 'thanksgiving; gravy; side_dish'},
    {'ProductName': 'Canned Yams 29oz', 'Tags': 'thanksgiving; yams; side_dish'},
    {'ProductName': 'Marshmallows 16oz', 'Tags': 'thanksgiving; yams; baking'},
    {'ProductName': 'Apple Pie 9in', 'Tags': 'thanksgiving; pies; dessert; christmas_foods'},
    {'ProductName': 'Eggnog Half Gallon', 'Tags': 'christmas_foods; beverage; dairy'},
    {'ProductName': 'Hot Cocoa Mix 10ct', 'Tags': 'christmas_foods; beverage; hot_chocolate'},
    {'ProductName': 'Candy Canes 12ct', 'Tags': 'christmas_foods; candy'},
]
