"""Thin write layer. Notebooks call write_to_lakehouse; tests use write_table
with a format/location override (no delta-spark dependency locally)."""

from pyspark.sql import DataFrame
from pyspark.sql import functions as F

from retail_setup.config.generation import GenerationConfig


def write_table(df: DataFrame, location: str, fmt: str = "delta") -> None:
    df.write.format(fmt).mode("overwrite").save(location)


def write_to_lakehouse(df: DataFrame, lakehouse: str, schema: str, table: str) -> None:
    """Overwrite-by-design, matching 02-historical-data-load semantics."""
    df.write.format("delta").mode("overwrite").saveAsTable(f"{lakehouse}.{schema}.{table}")


def write_all(
    tables: dict[str, DataFrame],
    gold: dict[str, DataFrame],
    cfg: GenerationConfig,
    run_id: str,
    *,
    lakehouse: str | None = None,
    base_path: str | None = None,
    fmt: str = "delta",
) -> list[str]:
    """Persist dims+facts to silver, gold to gold, then setup_run_log.

    Two modes: catalog (lakehouse=...) used by notebooks —
    saveAsTable(f"{lakehouse}.{cfg.silver_db}.{name}") — or path
    (base_path=...) used by local tests/E2E — save(f"{base_path}/{db}/{name}").
    dim_date is written as generated by the engine (±5y padding preserved —
    the semantic model's date relationships need the headroom).
    Returns the list of written table names (silver + gold); the
    setup_run_log table itself is not included in the returned list.

    The Spark session is derived from the first DataFrame in ``tables``
    (``df.sparkSession``) — no explicit session parameter is needed.
    """
    if (lakehouse is None) == (base_path is None):
        raise ValueError("Provide exactly one of lakehouse= or base_path=")

    spark = next(iter(tables.values())).sparkSession

    if lakehouse is not None:
        for db in (cfg.silver_db, cfg.gold_db):
            spark.sql(f"CREATE DATABASE IF NOT EXISTS {lakehouse}.{db}")

    def _write(df: DataFrame, db: str, name: str) -> None:
        if lakehouse is not None:
            df.write.format("delta").mode("overwrite").saveAsTable(
                f"{lakehouse}.{db}.{name}"
            )
        else:
            df.write.format(fmt).mode("overwrite").save(f"{base_path}/{db}/{name}")

    written: list[tuple[str, int]] = []
    for name, df in tables.items():
        _write(df, cfg.silver_db, name)
        written.append((name, df.count()))
    for name, df in gold.items():
        _write(df, cfg.gold_db, name)
        written.append((name, df.count()))

    log_rows = [
        (run_id, cfg.store_type, cfg.seed, cfg.start_date, cfg.end_date,
         name, count)
        for name, count in written
    ]
    log_df = spark.createDataFrame(
        log_rows,
        "run_id string, store_type string, seed long, start_date date, "
        "end_date date, table_name string, row_count long",
    ).withColumn("generated_at", F.current_timestamp())
    _write(log_df, cfg.silver_db, "setup_run_log")

    return [name for name, _ in written]
