"""Thin write layer. Notebooks call write_to_lakehouse; tests use write_table
with a format/location override (no delta-spark dependency locally)."""

from pathlib import Path

from pyspark.sql import DataFrame
from pyspark.sql import functions as F

from retail_setup.config.generation import GenerationConfig


def write_table(df: DataFrame, location: str, fmt: str = "delta") -> None:
    df.write.format(fmt).mode("overwrite").save(location)


def write_to_lakehouse(df: DataFrame, lakehouse: str, schema: str, table: str) -> None:
    """Overwrite-by-design, matching 02-historical-data-load semantics."""
    df.write.format("delta").mode("overwrite").saveAsTable(f"{lakehouse}.{schema}.{table}")


def write_all(
    tables: dict[str, DataFrame],
    gold: dict[str, DataFrame],
    cfg: GenerationConfig,
    run_id: str,
    *,
    lakehouse: str | None = None,
    base_path: str | None = None,
    fmt: str = "delta",
) -> list[str]:
    """Persist dims+facts to silver, gold to gold, then setup_run_log.

    Two modes: catalog (lakehouse=...) used by notebooks —
    saveAsTable(f"{lakehouse}.{cfg.silver_db}.{name}") — or path
    (base_path=...) used by local tests/E2E — save(f"{base_path}/{db}/{name}").
    dim_date is written as generated by the engine (±5y padding preserved —
    the semantic model's date relationships need the headroom).
    Returns the list of written table names (silver + gold); the
    setup_run_log table itself is not included in the returned list.

    The Spark session is derived from the first DataFrame in ``tables``
    (``df.sparkSession``) — no explicit session parameter is needed.
    """
    if (lakehouse is None) == (base_path is None):
        raise ValueError("Provide exactly one of lakehouse= or base_path=")

    spark = next(iter(tables.values())).sparkSession

    if lakehouse is not None:
        for db in (cfg.silver_db, cfg.gold_db):
            spark.sql(f"CREATE DATABASE IF NOT EXISTS {lakehouse}.{db}")

    def _write(df: DataFrame, db: str, name: str) -> None:
        if lakehouse is not None:
            df.write.format("delta").mode("overwrite").saveAsTable(f"{lakehouse}.{db}.{name}")
        else:
            df.write.format(fmt).mode("overwrite").save(f"{base_path}/{db}/{name}")

    def _count(db: str, name: str) -> int:
        # Count the just-written table, not the in-memory df: df.count() would
        # re-execute the entire (deterministic) generation lineage a second time,
        # while a freshly written Delta/Parquet table answers count() from file
        # metadata. Same value, a fraction of the work.
        if lakehouse is not None:
            return spark.table(f"{lakehouse}.{db}.{name}").count()
        return spark.read.format(fmt).load(f"{base_path}/{db}/{name}").count()

    log_name = "setup_run_log"
    log_table = f"{lakehouse}.{cfg.silver_db}.{log_name}" if lakehouse is not None else None
    log_path = f"{base_path}/{cfg.silver_db}/{log_name}" if base_path is not None else None

    def _log_exists() -> bool:
        if log_table is not None:
            return spark.catalog.tableExists(log_table)
        return Path(str(log_path)).exists()

    def _read_log() -> DataFrame:
        if log_table is not None:
            return spark.table(log_table)
        return spark.read.format(fmt).load(str(log_path))

    def _append_log(
        table_name: str,
        row_count: int | None,
        status: str,
        error: str | None = None,
    ) -> None:
        row = [
            (
                run_id,
                cfg.store_type,
                cfg.seed,
                cfg.start_date,
                cfg.end_date,
                table_name,
                row_count,
                status,
                error,
            )
        ]
        log_df = spark.createDataFrame(
            row,
            "run_id string, store_type string, seed long, start_date date, "
            "end_date date, table_name string, row_count long, status string, "
            "error string",
        ).withColumn("generated_at", F.current_timestamp())
        writer = log_df.write.format("delta" if log_table is not None else fmt)
        writer = writer.mode("append").option("mergeSchema", "true")
        if log_table is not None:
            writer.saveAsTable(log_table)
        else:
            writer.save(str(log_path))

    if _log_exists() and _read_log().filter(F.col("run_id") == run_id).limit(1).count():
        raise ValueError(f"setup run_id already exists: {run_id!r}")

    _append_log("__run__", None, "STARTED")

    written: list[tuple[str, int]] = []
    for db, frames in ((cfg.silver_db, tables), (cfg.gold_db, gold)):
        for name, df in frames.items():
            try:
                _write(df, db, name)
                count = _count(db, name)
            except Exception as exc:
                error = f"{type(exc).__name__}: {exc}"[:1000]
                try:
                    _append_log(name, None, "FAILED", error)
                    _append_log("__run__", None, "FAILED", error)
                except Exception as log_exc:
                    raise RuntimeError(
                        f"writing {name!r} failed and setup_run_log could not "
                        f"record the failure: {log_exc}"
                    ) from exc
                raise
            written.append((name, count))
            _append_log(name, count, "COMPLETED")

    _append_log("__run__", len(written), "COMPLETED")

    return [name for name, _ in written]
