"""Repository-wide immutable dependency and privileged execution contracts."""

from __future__ import annotations

import ast
import re
from collections.abc import Iterator
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
WORKFLOWS = REPO_ROOT / ".github" / "workflows"
FULL_COMMIT_SHA = re.compile(r"^[0-9a-f]{40}$")
LOCK_FILES = (
    REPO_ROOT / "requirements-docs.txt",
    REPO_ROOT / "requirements-test.txt",
    REPO_ROOT / "utility" / "requirements-ci.txt",
    REPO_ROOT / "utility" / "requirements-deploy.txt",
)
NOTEBOOK_TEMPLATES = (
    REPO_ROOT / "utility" / "notebooks" / "templates" / "driver-02-dimensions.py",
    REPO_ROOT / "utility" / "notebooks" / "templates" / "driver-03-facts.py",
    REPO_ROOT / "utility" / "notebooks" / "templates" / "driver-04-gold.py",
)


def _workflow_steps(workflow: dict) -> Iterator[dict]:
    for job in workflow.get("jobs", {}).values():
        yield from job.get("steps", [])


def _workflows() -> Iterator[tuple[Path, dict]]:
    for path in sorted((*WORKFLOWS.glob("*.yml"), *WORKFLOWS.glob("*.yaml"))):
        yield path, yaml.safe_load(path.read_text(encoding="utf-8"))


def _requirement_blocks(text: str) -> list[str]:
    blocks: list[list[str]] = []
    current: list[str] = []
    for line in text.splitlines():
        if line and not line[0].isspace() and not line.startswith("#"):
            if current:
                blocks.append(current)
            current = [line]
        elif current:
            current.append(line)
    if current:
        blocks.append(current)
    return ["\n".join(block) for block in blocks]


def test_plugin_marketplaces_use_sha_pinned_local_checkouts() -> None:
    for path, workflow in _workflows():
        checkout_paths: dict[str, tuple[str, str]] = {}
        steps = list(_workflow_steps(workflow))
        for step in steps:
            uses = str(step.get("uses", ""))
            options = step.get("with", {})
            if not uses.startswith("actions/checkout@") or "repository" not in options:
                continue
            checkout_path = str(options.get("path", "")).removeprefix("./").rstrip("/")
            checkout_paths[checkout_path] = (
                str(options["repository"]),
                str(options.get("ref", "")),
            )

        for step in steps:
            marketplaces = step.get("with", {}).get("plugin_marketplaces")
            if not marketplaces:
                continue
            for marketplace in str(marketplaces).splitlines():
                marketplace = marketplace.strip()
                assert marketplace.startswith("./"), (
                    f"{path.name}: plugin marketplace must be a local pinned checkout: "
                    f"{marketplace!r}"
                )
                checkout_path = marketplace.removeprefix("./").rstrip("/")
                assert checkout_path in checkout_paths, (
                    f"{path.name}: no external checkout supplies {marketplace!r}"
                )
                repository, ref = checkout_paths[checkout_path]
                assert repository and FULL_COMMIT_SHA.fullmatch(ref), (
                    f"{path.name}: {repository} marketplace ref must be a full SHA: "
                    f"{ref!r}"
                )


def test_checkout_actions_never_persist_credentials() -> None:
    violations: list[str] = []

    for path, workflow in _workflows():
        for step in _workflow_steps(workflow):
            if not str(step.get("uses", "")).startswith("actions/checkout@"):
                continue
            if step.get("with", {}).get("persist-credentials") is not False:
                violations.append(f"{path.name}: {step.get('name', 'checkout')}")

    assert not violations, f"checkout credentials must not persist: {violations}"


def test_write_token_is_configured_only_after_dependency_install() -> None:
    docs = yaml.safe_load((WORKFLOWS / "docs.yml").read_text(encoding="utf-8"))
    steps = docs["jobs"]["docs"]["steps"]
    names = [step.get("name", "") for step in steps]

    credential_index = names.index("Configure publish credentials")
    assert names.index("Install documentation tools") < credential_index
    assert credential_index < names.index("Publish")
    assert "GH_PAGES_TOKEN" in steps[credential_index]["env"]


def test_python_lockfiles_are_hash_complete() -> None:
    for path in LOCK_FILES:
        text = path.read_text(encoding="utf-8")
        assert "autogenerated by uv" in text
        assert "git+" not in text
        blocks = _requirement_blocks(text)
        assert blocks, f"{path} contains no locked requirements"
        for block in blocks:
            first_line = block.splitlines()[0]
            assert "==" in first_line or " @ https://" in first_line, (
                f"{path}: mutable requirement {first_line!r}"
            )
            assert "--hash=sha256:" in block, (
                f"{path}: requirement lacks a SHA-256 hash: {first_line!r}"
            )


def test_workflow_pip_installs_are_locked_or_dependency_free() -> None:
    violations: list[str] = []

    for path, workflow in _workflows():
        for step in _workflow_steps(workflow):
            for line in str(step.get("run", "")).splitlines():
                command = line.strip()
                if "pip install" not in command:
                    continue
                if "--require-hashes" in command:
                    continue
                if "--no-deps" in command and " -e " in f" {command} ":
                    continue
                violations.append(f"{path.name}: {command}")

    assert not violations, (
        f"workflow pip installs must use reviewed locks: {violations}"
    )


def test_fabric_provider_is_exact_and_multi_platform_locked() -> None:
    terraform_root = REPO_ROOT / "deploy" / "terraform"
    providers = (terraform_root / "providers.tf").read_text(encoding="utf-8")
    lock = (terraform_root / ".terraform.lock.hcl").read_text(encoding="utf-8")

    version_match = re.search(
        r'source\s*=\s*"microsoft/fabric"\s+version\s*=\s*"([^"]+)"',
        providers,
    )
    assert version_match
    version = version_match.group(1)
    assert re.fullmatch(r"\d+\.\d+\.\d+", version)
    assert f'version     = "{version}"' in lock
    assert f'constraints = "{version}"' in lock
    assert lock.count('"h1:') >= 6
    assert lock.count('"zh:') >= 6


def test_notebook_runtime_installs_are_exactly_pinned() -> None:
    for path in NOTEBOOK_TEMPLATES:
        tree = ast.parse(path.read_text(encoding="utf-8"))
        pip_requirements: list[str] = []
        for call in (node for node in ast.walk(tree) if isinstance(node, ast.Call)):
            if (
                not isinstance(call.func, ast.Attribute)
                or call.func.attr != "check_call"
            ):
                continue
            if not call.args or not isinstance(call.args[0], ast.List):
                continue
            values = [
                item.value
                for item in call.args[0].elts
                if isinstance(item, ast.Constant) and isinstance(item.value, str)
            ]
            if "pip" in values and "install" in values:
                install_index = values.index("install")
                requirements = [
                    value
                    for value in values[install_index + 1 :]
                    if not value.startswith("-")
                ]
                pip_requirements.extend(requirements)

        assert pip_requirements, f"{path.name}: expected pinned runtime dependencies"
        assert all(
            re.fullmatch(r"[A-Za-z0-9_-]+==[0-9][A-Za-z0-9._-]*", requirement)
            for requirement in pip_requirements
        )


def test_miniforge_bootstraps_are_pinned_and_verified() -> None:
    shell = (REPO_ROOT / "scripts" / "setup.sh").read_text(encoding="utf-8")
    powershell = (REPO_ROOT / "scripts" / "setup.ps1").read_text(encoding="utf-8")

    assert 'MiniforgeVersion="26.3.2-3"' in shell
    assert "releases/latest" not in shell
    assert shell.count("sha256") >= 5
    assert shell.index('verify_sha256 "$installer"') < shell.index('bash "$installer"')
    assert "$MiniforgeVersion = '26.3.2-3'" in powershell
    assert "--version $MiniforgeVersion --source winget" in powershell
